// lib/localization/en_US.dart

const Map<String, String> enUS = {
  // ===================================
  // Common & General
  // ===================================
  'common.add': 'Add',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.viewAll': 'View All',
  'common.select': 'Select',
  'common.search': 'Search',
  'common.find': 'Find',
  'common.publish': 'Publish',
  'common.saveAndAdd': 'Save & Add',
  'common.upload': 'Upload',
  'common.addFile': 'Add File',
  'common.savePhotos': 'Save Photos',
  'common.saveMemory': 'Save Memory',
  'common.loading': 'Loading...',
  'common.error': 'Something went wrong. Please try again.',
  'common.success': 'Success',
  'common.productPublished': 'Product Published Successfully!',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.maybe': 'May Be',
  'common.select_country': 'Select Country',
  'common.submit': 'Submit',
  'common.done': 'Done',
  'common.next': 'Next',
  'common.continue': 'Continue',
  'common.all': 'All',
  'common.seeAll': 'See All',
  'common.father': 'Father',
  'common.mother': 'Mother',
  'common.sister': 'Sister',
  'common.brother': 'Brother',
  'common.approved' :'Approved',



  // ===================================
  // Auth Screen
  // ===================================
  'auth.kincore': 'Kincore',
  'auth.connect': 'Connect to your Roots!',
  'auth.welcomeBack': 'Welcome Back!',
  'auth.detailsPrompt': 'Enter your Details to Log in or create an account.',
  'auth.signUp': 'Sign Up',
  'auth.logIn': 'Sign In',
  'auth.nameLabel': 'Enter Your Name',
  'auth.nameHint': 'First name last name',
  'auth.emailLabel': 'Email Address',
  'auth.emailHint': 'abc@gmail.com',
  'auth.passwordLabel': 'Password',
  'auth.passwordHint': '••••••••',
  'auth.confirmPasswordLabel': 'Confirm Password',
  'auth.forgotPassword': 'Forgot Password?',
  'auth.continueWith': 'Or Continue with',
  'auth.google': 'Google',
  'auth.facebook': 'Facebook',
  'auth.dateOfBirth': 'Date Of Birth',
  'auth.lastName': 'Last Name',
  'auth.firstName': 'First Name',
  'auth.forgotPasswordTitle': 'Forgot Password',
  'auth.forgotPasswordHeading': 'Forgot Password?',
  'auth.forgotPasswordDesc': 'Don\'t worry! It happens. Please enter the email address associated with your account.',
  'auth.enterEmail': 'Enter your email',
  'auth.sending': 'Sending...',
  'auth.sendCode': 'Send Code',
  'profile.logoutTitle': 'Logout',
  'profile.logoutSuccessMsg': 'Successfully logged out',
  'auth.back': 'Back',
  'auth.firstNameHint': 'Enter first name',
  'auth.lastNameHint': 'Enter last name',
  'auth.dob': 'Date of Birth (Optional)',
  'auth.dobHint': 'DD/MM/YYYY',


  // ===================================
  // Home Screen
  // ===================================
  'home.title': 'Home',
  'home.goodMorning': 'Good morning',
  'home.upcomingBirthdays': 'Upcoming birthdays',
  'home.viewCalendar': 'View Calendar',
  'home.timeline': 'Timeline',
  'home.startBuilding': 'Start Building Your Family Tree',
  'home.startBuildingDesc': 'Add family members to see your heritage grow.',
  'home.addFirstMember': 'Add First Member',
  'home.recentMemories': 'Recent Memories',
  'home.noMemories': 'No recent memories found.',
  'home.addFirstMemory': 'Add Your First Memory',
  'home.upcomingEvents': 'Upcoming Events',
  'home.noEvents': 'No upcoming events.',
  'home.familyEvents': 'Family Events',
  'home.familyBio': 'Family Bio',
  'home.secretSanta': 'Secret Santa',
  'home.kinshipCalculator': 'Kinship Calculator',
  'home.identityApproval': 'Identity Approval',
  'home.migrationMap': 'Migration Map',
  'home.quickModules': 'Quick Modules',
  'home.calculator': 'Calculator',
  'home.giftSwap': 'Gift Swap',
  'home.savedFeed': 'Saved Feed',
  'home.exploreMore': 'Explore More',
  'home.marketplace': 'Marketplace',
  'home.reels': 'Reels',

  // ===================================
  // Market Place
  // ===================================
  'marketplace.title': 'Marketplace',
  'marketplace.searchHint': 'Search products, categories...',
  'marketplace.bannerTitle': 'Summer Sale is Live!',
  'marketplace.bannerSub': 'Find the best deals near you.',
  'marketplace.noProducts': 'No products found!',
  'marketplace.catAll': 'All',
  'marketplace.catVehicles': 'Vehicles',
  'marketplace.catProperty': 'Property',
  'marketplace.catElectronics': 'Electronics',
  'marketplace.catFurniture': 'Furniture',
  'marketplace.catFashion': 'Fashion',
  'marketplace.msgAvailable': 'Hi, is this still available?',
  'marketplace.timeJustNow': 'Just now',
  'marketplace.timeYesterday': 'Yesterday',
  'marketplace.messages': 'Messages',
  'marketplace.noMessages': 'No messages yet.',

  // ===================================
  // Family Bio
  // ===================================
  'familyBio.title': 'Family Bio',
  'familyBio.migrationStoryDate': 'Nov 4, 1920 · Sicily to New York',
  'familyBio.existingMember': 'Existing Family Member',
  'familyBio.migrationStoryContent': 'The Great Migration, a pivotal moment in history, saw millions of individuals embark on journeys to new lands, seeking opportunities and a fresh start. Among them was Maria Rossi, a young woman from Sicily, who set sail for New York in 1920. Her story, like many others, is a testament to courage, resilience, and the enduring human spirit.',
  'familyBio.migrationStoryQuote': '"The journey was long and arduous, but the hope of a better life kept us going." – Maria Rossi',
  'familyBio.gallery': 'Gallery',
  'familyBio.nextInHistory': 'Next in History',
  'familyBio.theRoaringTwenties': 'The Roaring Twenties',
  'familyBio.roaringTwentiesDate': '1920 - 1929',

  // ===================================
  // Navigation
  // ===================================
  'nav.home': 'Home',
  'nav.feed': 'Feed',
  'nav.tree': 'Tree',
  'nav.mall': 'Mall',
  'nav.profile': 'Menu',
  'nav.memory': 'Memory',
  'nav.family': 'Family',
  'nav.events': 'Events',

  // ===================================
  // Tree Screen
  // ===================================
  'tree.title': 'The Harrison Clan',
  'tree.generations': '@count Generation / @members Member',
  'tree.webContentView': 'Web Content View',
  'tree.allView': 'All View',
  'tree.directLinage': 'Direct Lineage', // (Spelling fix kar di hai 'Lineage')
  'tree.birthday': 'Birthday',
  'tree.anniversary': 'Anniversary',

  // ===================================
  // Family Bio Screen
  // ===================================
  'familyBio.addTitle': 'Add Family bio',
  'familyBio.addMedia': 'Add Media',
  'familyBio.dragAndDrop': 'Drag and drop or browse to upload',
  'familyBio.basicInfo': 'Basic Info',
  'familyBio.storyName': 'Story Name',
  'familyBio.location': 'Location',
  'familyBio.birthDate': 'Birth Date',
  'familyBio.selectDate': 'Select Date',
  'familyBio.storyBio': 'Story(Bio)',
  'familyBio.addBioHint': 'Add bio here...',
  'familyBio.publishBio': 'Publish Bio',
  'familyBio.errorTitle': 'Error',
  'familyBio.nameRequired': 'Story Name is required',
  'familyBio.successTitle': 'Success',
  'familyBio.publishedMsg': 'Bio Published!',

  // ===================================
  // Add Family Member Screens (General)
  // ===================================
  'addMember.title': 'Add Family Member',
  'addMember.basicInfo': 'Basic Information',
  'addMember.firstName': 'First Name',
  'addMember.lastName': 'Last Name',
  'addMember.gender': 'Gender',
  'addMember.male': 'Male',
  'addMember.female': 'Female',
  'addMember.other': 'Other',
  'addMember.dateOfBirth': 'Date of Birth',
  'addMember.dateFormatHint': 'MM/DD/YYYY',
  'addMember.relationshipSetup': 'Relationship Setup',
  'addMember.relationshipType': 'Relationship Type',
  'addMember.relationship.spouse': 'Spouse',
  'addMember.relationship.sibling': 'Sibling',
  'addMember.relationship.parent': 'Parent',
  'addMember.findFamilyMember': 'Find Family Member',
  'addMember.spouseName': 'Spouse Name',
  'addMember.anniversaryDate': 'Anniversary Date',
  'addMember.additionalDetail': 'Additional Detail',
  'addMember.addLocation': 'Add location',
  'addMember.occupation': 'Occupation',
  'addMember.bioNotes': 'Bio / Notes',
  'addMember.privacyVisibility': 'Privacy & Visibility',
  'addMember.visibleToAll': 'Visible to all members',
  'addMember.addParentsTitle': 'Add Parents',
  'addMember.addOtherMember': 'Add Other Family Member',
  'addMember.placeOfBirth': 'Place Of Birth',
  'addMember.currentLocation': 'Current Location',
  'addMember.addChildTitle': 'Add Child',
  'addMember.schoolAndCollege': 'School & Collage',
  'addMember.qualification': 'Qualification',
  'addMember.studyLocation': 'Study Location',
  'addMember.changePhoto': 'Change Photos',
  'addMember.livingStatus': 'Living Status',
  'addMember.isAlive': 'Is the Person Still Alive?',
  'addMember.alive': 'Alive',
  'addMember.deceased': 'Deceased',
  'addMember.phoneNumber': 'Phone Number',
  'addMember.phoneHint': '00000 00000',

  // ===================================
  // Memory Screen
  // ===================================
  'memory.title': 'Memory',
  'memory.addTitle': 'Add Memory',
  'memory.tabAll': 'All',
  'memory.tabPhotos': 'Photos',
  'memory.tabVideos': 'Videos',
  'memory.addMemoryPhotos': 'Add Memory Photos',
  'memory.addMemoryVideos': 'Add Memory Videos',
  'memory.uploadSupport': 'Upload PNG, JPG File Support',

  // ===================================
  // K-Mall & Products
  // ===================================
  'mall.title': 'Mall',
  'mall.searchHint': 'Find Products',
  'mall.filter': 'Filter',
  'mall.categories': 'Categories',
  'mall.featured': 'Featured',
  'mall.mostPopular': 'Most Popular',
  'mall.onSale': 'On Sale',
  'mall.wishlistTitle': 'My Wishlist',
  'mall.noItemsWishlist': 'Your wishlist is empty!',
  'mall.exploreProducts': 'Explore Products',
  'mall.productDetails': 'Product Details',
  'mall.description': 'Description',
  'mall.selectSize': 'Select Size',
  'mall.selectColor': 'Select Color',
  'mall.quantity': 'Quantity',
  'mall.addToCart': 'Add to Cart',
  'mall.buyNow': 'Buy Now',
  'mall.reviews': 'Reviews',
  'mall.noReviews': 'No reviews yet for this product.',
  'mall.sellerInfo': 'Seller Information',
  'mall.viewShop': 'View Shop',
  'mall.relatedProducts': 'Related Products',
  'mall.addedToCart': '@productName added to cart',
  'mall.filterPrice': 'Price Range',
  'mall.filterColor': 'Colour',
  'mall.filterGender': 'Gender',
  'mall.category.fashion': 'Fashion',
  'mall.category.electronics': 'Electronics',
  'mall.category.appliances': 'Appliances',
  'mall.category.beauty': 'Beauty',
  'mall.category.furniture': 'Furniture',
  'mall.banner.title': 'New Collection',
  'mall.banner.discount': '50% OFF',
  'mall.banner.for': 'For Children',
  'mall.productReview': '@rating (@count Review)',
  'mall.tag.homeMade': 'Home Made',
  'mall.tag.newCollection': 'New collection',
  'addProduct.title': 'Add New Product',
  'addProduct.detailsPrompt': 'Enter all the details to list your product',
  'addProduct.uploadImagesTitle': 'Upload Product Images',
  'addProduct.uploadImagesDesc':
      'Use clear, high-resolution images. First image will be the cover.',
  'addProduct.addMedia': 'Add Media',
  'addProduct.dragAndDrop': 'Drag and drop or browse to upload',
  'addProduct.basicInfo': 'Basic Info',
  'addProduct.productNameLabel': 'Product Name (required)',
  'addProduct.priceLabel': 'Price',
  'addProduct.discountLabel': 'Discount%',
  'addProduct.descriptionLabel': 'Description',
  'addProduct.sizeLabel': 'Size',
  'addProduct.conditionsLabel': 'Conditions',
  'addProduct.brandNameLabel': 'Brand Name',
  'addProduct.profileLabel': 'Select Your Profile',
  'addProduct.categoryLabel': 'Category',
  'addProduct.subCategoryLabel': 'Sub-Category',
  'addProduct.quantityLabel': 'Quantity',
  'addProduct.publishButton': 'Publish Product',

  // ===================================
  // Redeem Coin Screen
  // ===================================
  'redeem.title': 'Redeem KCC Coins',
  'redeem.totalBalance': 'TOTAL BALANCE',
  'redeem.kccBalance': 'KCC Balance',
  'redeem.currency': 'KCC',
  'redeem.waysToRedeem': 'Ways to Redeem',
  'redeem.waysToEarn': 'Ways to Earn',
  'redeem.recentActivity': 'Recent Activity',
  'redeem.vintageCase': 'Vintage Case',
  'redeem.kmallPurchase': 'mall Purchase',
  'redeem.redeemedKcc': '-455 KCC',
  'redeem.shopAndSave': 'Shop & Save',
  'redeem.redeemForCash': 'Redeem for Cash',
  'redeem.shopNow': 'Shop Now',
  'redeem.redeemNow': 'Redeem Now',
  'earn.referral': 'Refer a Friend',
  'earn.referralSub': 'Earn 20 KCC',


  // ===================================
  // Coin Card Level
  // ===================================
  'profile.levelBadge': 'Level @level @title',

  // ===================================
  // Create Event Screen
  // ===================================
  'createEvent.title': 'Create Event',
  'createEvent.saveDraft': 'Save',
  'createEvent.addCoverPhoto': 'Add Cover Photo',
  'createEvent.uploadSupport': 'Upload PNG, JPG File Support',
  'createEvent.detailTitle': 'Event Detail',
  'createEvent.eventTitleLabel': 'Event Title',
  'createEvent.eventTitleHint': 'Enter Title',
  'createEvent.locationLabel': 'Location',
  'createEvent.locationHint': 'Enter Address Location',
  'createEvent.descriptionLabel': 'Description',
  'createEvent.descriptionHint': 'Write here...',
  'createEvent.startDateLabel': 'Start Date',
  'createEvent.endDateLabel': 'End Date',
  'createEvent.timeLabel': 'Time',
  'createEvent.timeHint': 'Enter Time',
  'createEvent.inviteMemberTitle': 'Invite Family Member',
  'createEvent.starts': 'Starts',
  'createEvent.ends': 'Ends',
  'createEvent.requestRSVP': 'Request RSVP',
  'createEvent.requestRSVPSub': 'Guests must confirm attendance',
  'createEvent.sendReminders': 'Send Reminders',
  'createEvent.sendRemindersSub': 'Notify guests 1 day before',
  'createEvent.includeGiftExchange': 'Include Gift Exchange',
  'createEvent.includeGiftExchangeSub': 'e.g., Secret Santa or Gift Swap',
  'createEvent.nextAddGift': 'Next & Add Gift',
  'createEvent.createEventBtn': 'Create Event',
  'createEvent.eventCreatedTitle': 'Event Created',
  'createEvent.eventCreatedMsg': 'Your Event is Created Successfully!',

  // ===================================
  // Feed & Posts
  // ===================================
  'feed.title': 'Family Feed',
  'feed.myStory': 'My Story',
  'feed.whatsHappening': "What's Happening?",
  'feed.createPost': 'Create Post',
  'feed.archive': 'Archive',
  'feed.writeCommentHint': 'Write a comment...',
  'feed.viewComments': 'View all @count comments',
  'postSettings.title': 'Post Setting',
  'postSettings.postSettings': 'Post Settings',
  'postSettings.whoCanSee': 'Who can see your posts?',
  'postSettings.visibility.public': 'Public',
  'postSettings.visibility.friends': 'Friends',
  'postSettings.visibility.friendsExcept': 'Friends Except',
  'postSettings.visibility.specificFriends': 'Specific Friends',
  'postSettings.whoCanComment': 'Who can comment on this post?',
  'postSettings.comments.followersOnly': 'Your Followers only',
  'postSettings.comments.friends': 'Friends',
  'postSettings.comments.chosenFriends': 'Chosen Friends',
  'postSettings.saveChanges': 'Save Changes',
  'feed.postAnonymously': 'Post Anonymously',
  'feed.allowComments': 'Allow Comments',
  'feed.saveToDevice': 'Save to device',
  'feed.reportPost': 'Report Post',
  'createPost.title': 'Create Post',
  'createPost.hint': 'What’s on your mind?',
  'createPost.addMedia': 'Add media',
  'createPost.tagPeople': 'Tag people',
  'createPost.postButton': 'Post',
  'report.title': 'Report Issue',
  'report.anonymousHelp':
      'You Report Is Anonymous. Help Us Keep The Family Tree Community Safe By Telling Us What’s Happening.',
  'report.reasonTitle': 'Reason for Report',
  'report.spam': "It's Spam",
  'report.nudity': 'Nudity Or Sexual Activity',
  'report.hateSpeech': 'Hate Speech Or Symbols',
  'report.falseInfo': 'False Information',
  'report.harassment': 'Harassment Or Bullying',
  'report.other': 'Something Else',
  'report.additionalDetails': 'Additional Detail(Optional)',
  'report.describeIssue': 'Please Describe The Issue to Help Our Review',
  'report.submitReport': 'Submit Report',
  'report.dialog.discardTitle': 'Discard Report?',
  'report.dialog.discardBody':
      'Are you sure you want to cancel this report? Your progress will be lost.',
  'report.dialog.stay': 'No, Stay',
  'report.dialog.discard': 'Yes, Discard',
  'feed.archiveMenu': 'Archive',
  'feed.reportMenu': 'Report',
  'feed.archiveMsg': 'Post added to your archive.',
  'feed.savedTitle': 'Saved',
  'feed.savedMsg': 'Post saved to your collection.',
  'feed.removedTitle': 'Removed',
  'feed.removedMsg': 'Post removed from saved.',
  'feed.caughtUp': 'You\'re all caught up!',
  'feed.findMore': 'Find more family members',
  'feed.writeComment': 'Write a comment...',
  'createPost.successTitle': 'Success',
  'createPost.successMsg': 'Post created successfully!',
  'createPost.errorTitle': 'Error',
  'createPost.errorMsg': 'Please enter some text or add media.',
  'feed.savedCollection': 'Saved Collection',
  'feed.noSavedPosts': 'No saved posts yet',
  'feed.removeFromCollection': 'Remove from collection',

  // ===================================
  // Seller Dashboard
  // ===================================
  'seller.title': 'Dashboard',
  'seller.overview': 'Overview',
  'seller.totalRevenue': 'Total Revenue',
  'seller.orders': 'Orders',
  'seller.avgOrderValue': 'Average Order Value',
  'seller.products': 'Products',
  'seller.topProducts': 'Top Products',
  'seller.recentOrders': 'Recent Orders',
  'seller.orderId': 'Order',
  'seller.noProducts': 'No products to display.',
  'seller.noOrders': 'No recent orders.',
  'seller.noData': 'No Data Available',

  // ===================================
  // Profile & Settings
  // ===================================
  'profile.title': 'My Profile',
  'profile.followers': 'Followers',
  'profile.following': 'Following',
  'profile.editProfile': 'Edit Profile',
  'profile.addMember': 'Add Member',
  'profile.addMemory': 'Add Memory',
  'profile.vitalStats': 'Vital Statistics',
  'profile.stat.fullName': 'Full Name',
  'profile.stat.born': 'Born',
  'profile.stat.location': 'Location',
  'profile.stat.occupation': 'Occupation',
  'profile.familyMember': 'Family Member',
  'profile.keyLifeEvents': 'Key Life Events',
  'profile.viewMoreTimeline': 'View More Timeline',
  'profile.memories': 'Memories',
  'profile.shareProfile': 'Share Profile',
  'profile.personal': 'Personal',
  'profile.business': 'Business',
  'profile.posts': 'Posts',
  'profile.photos': 'Photos',
  'profile.videos': 'Videos',
  'profile.tagged': 'Tagged',
  'profile.myProfile': 'My Profile',
  'profile.sellerDashboard': 'Seller Dashboard',
  'profile.identityApproval': 'Identity Approval',
  'profile.redeemCoins': 'Redeem Coins',
  'profile.settings': 'Settings',
  'profile.logout': 'Logout',
  'profile.logoutConfirm': 'Are you sure you want to log out?',
  'profile.personalProfile': 'Personal Profile',
  'profile.roleAccess': 'Your Role & Access',
  'profile.viewDashboard': 'Seller Dashboard',
  'profile.addProduct': 'Add Product',
  'profile.account': 'Account',
  'profile.personalInfo': 'Personal Information',
  'profile.personalInfoSub': 'Name, Email, Phone Number',
  'profile.privacy': 'Privacy & Security',
  'profile.privacySub': 'Family Tree Visibility, Password',
  'profile.notifications': 'Notification',
  'profile.notificationsSub': 'Events, update, Messages',
  'profile.darkMode': 'Dark Mode',
  'profile.darkModeSub': 'Toggle application theme',
  'profile.myOrders': 'My Orders',
  'profile.myOrdersSub': 'Order History, Returns',
  'profile.myListings': 'My listings',
  'profile.myListingsSub': 'Management For Sale',
  'editProfile.title': 'Edit Profile',
  'editProfile.changePhoto': 'Change Photos',
  'editProfile.firstNameLabel': 'First Name',
  'editProfile.firstNameHint': 'Enter First Name',
  'editProfile.lastNameLabel': 'Last Name',
  'editProfile.lastNameHint': 'Enter Last Name',
  'editProfile.endDateLabel': 'End Date',
  'editProfile.locationLabel': 'Location',
  'editProfile.locationHint': 'Enter Address Location',
  'editProfile.occupationLabel': 'Occupation',
  'editProfile.occupationHint': 'Enter Occupation',
  'editProfile.designationLabel': 'Designation',
  'editProfile.designationHint': 'Enter Description',
  'editProfile.companyNameLabel': 'Company Name',
  'editProfile.companyNameHint': 'Enter Company Name',
  'editProfile.websiteLabel': 'Website',
  'editProfile.websiteHint': 'Paste Your Website',
  'editProfile.linkedInLabel': 'Linked In',
  'editProfile.linkedInHint': 'Paste LinkedIn Link',
  'editProfile.instagramLabel': 'Instagram',
  'editProfile.instagramHint': 'Paste Instagram Link',
  'editProfile.facebookLabel': 'FaceBook',
  'editProfile.facebookHint': 'Paste Facebook Link',
  'editProfile.otherLinkLabel': 'Other Link',
  'editProfile.otherLinkHint': 'Paste other Link',
  'editProfile.addOtherLink': 'Add Other Link',
  'editProfile.claimIdentity': 'Claim Identity',
  'profile.privacyLocked': 'Privacy: Locked',
  'profile.privacyUnlocked': 'Privacy: Unlocked',
  'profile.message': 'Message',
  'profile.viewFeed': 'View Feed',
  'profile.viewStory': 'View Story',
  'profile.viewProfilePic': 'View Profile Picture',
  'profile.viewUserFeed': 'View User Feed',
  'profile.privacyLockedTitle': 'Privacy Locked 🔒',
  'profile.privacyUnlockedTitle': 'Privacy Unlocked 🔓',
  'profile.privacyLockedMsg': 'Your profile is now private.',
  'profile.privacyUnlockedMsg': 'Your profile is now visible to others.',
  'profile.requestHistory': 'Request History',
  'profile.requestHistorySub': 'Check Your Request History',
  'profile.saveFeed': 'Saved Feed',
  'profile.saveFeedSub': 'Saved Feed Collection',
  'profile.giftSwap': 'Gift Swap',
  'profile.giftSwapSub': 'Your Gift Swap',
  'profile.displayMode': 'Display Mode',
  'profile.displayModeSub': 'Adjust appearance (Light/Dark)',
  'profile.display': 'Display',
  'profile.chooseAppearance': 'Choose Appearance',
  'profile.lightMode': 'Light Mode',
  'profile.systemPref': 'System Preference',
  'profile.systemPrefSub': 'Adjust to device settings',

  // ===================================
  // Events
  // ===================================
  'event.status.attended': 'Attended',
  'event.status.notAttended': 'Not Attended',
  'event.status.joinnow': 'Join Now',
  'event.detailTitle': 'Event Detail',
  'event.hostedBy': 'HOSTED BY',
  'event.areYouGoing': 'Are You Going?',
  'event.responseRequired': 'Response Required',
  'event.going': 'Going',
  'familyEvents.title': 'Family Events',
  'familyEvents.findHint': 'Find Event',
  'familyEvents.tabUpcoming': 'UpComing',
  'familyEvents.tabPast': 'Past',

  // ===================================
  // Family Member List
  // ===================================
  'memberList.title': 'All Family Member',
  'memberList.tabFamilies': 'Families',
  'memberList.tabPeople': 'People',
  'memberList.noMembers': 'No members found',
  'memberList.present': 'Present',
  'memberList.location': 'California, USA',

  // ===================================
  // Find Yourself / Member
  // ===================================
  'findYourself.title': 'Find Yourself',
  'findYourself.searchHint': 'Find Name/Birthday Date',
  'findYourself.bestMatches': 'Best Matches',
  'findYourself.foundCount': '@count Found',
  'findYourself.notListed': 'Not Listed? Please Create Profile',
  'findYourself.thisIsMe': 'This is Me',
  'findMember.title': 'Find Family Member',
  'findMember.searchHint': 'Find Family Member',
  'findMember.lastViewed': 'Last Viewed',
  'findYourself.subtitle': 'Search for your name to link your account to\nthe existing family tree record.',
  'findYourself.possibleMatches': 'Possible Matches',
  'findYourself.selectionReqTitle': 'Selection Required',
  'findYourself.selectionReqMsg': 'Please select your profile first.',
  'findYourself.firstName': 'First Name',
  'findYourself.lastName': 'Last Name',
  'findYourself.gender': 'Gender',
  'findYourself.selectGender': 'Select Gender',
  'findYourself.dob': 'Date of Birth',
  'findYourself.yearOnly': 'Year-only match',
  'findYourself.searchBtn': 'Search',
  'findYourself.clearBtn': 'Clear',
  'findYourself.initialMsg': 'Enter at least one field and tap Search.',
  'findYourself.noResults': 'No Results Found',
  'findYourself.noResultsSub': 'Try adjusting your search terms or clear filters.',
  'findYourself.resultsCount': '@count Results Found',
  'findYourself.validationMsg': 'Please enter at least one field to search.',
  'findYourself.male': 'Male',
  'findYourself.female': 'Female',
  'findYourself.other': 'Other',
  'findYourself.firstNameHint': 'Enter first name',
  'findYourself.lastNameHint': 'Enter last name',
  'findYourself.dobHint': 'Select date',

  // ===================================
  // Role & Access
  // ===================================
  'role.title': 'Role & Access',
  'role.currentRole': 'Current Role: @role',
  'role.familySpace': 'Smith Family Space',
  'role.adminAccessTitle': 'Administration Access',
  'role.adminAccessDesc':
      'Admins have Full Control Over the Family Space. They can manage members and configure settings.',
  'role.permission.editTree': 'Family Tree Editing',
  'role.permission.editTreeSub': 'Add Edit Or Deleted Any Profile',
  'role.permission.memberMgmt': 'Member Management',
  'role.permission.memberMgmtSub': 'Invite New Users And Assign Roles',
  'role.permission.spaceSettings': 'Space Settings',
  'role.permission.spaceSettingsSub': 'Change Privacy And Notifications',
  'role.permission.contentModeration': 'Content Moderation',
  'role.permission.contentModerationSub': 'Manage Albums And Deleted Posts',
  'role.warning':
      'Only The Family Creator Can Transfer Ownership Or Deleted The Entire Family Space.',
  'role.changePermission': 'Need To Change Your Permissions?',
  'role.contactCreator': 'Contact Family Creator',
  'role.saveAndCreate': 'Save & create',
  'role.limitedAccess': 'Limited Access',
  'role.limitedAccessDesc':
      'Cannot view sensitive information or edit the tree.',
  'role.fullAccess': 'Full Access',
  'role.fullAccessDesc': 'Can view all information and edit the family tree.',
  'role.admin': 'Admin',
  'role.member': 'Member',
  'role.guest': 'Guest',
  'roleAccess.title': 'Role & Access',
  'roleAccess.manager': 'Manager',
  'roleAccess.permissions': 'Permissions',
  'roleAccess.viewTree': 'View Family Tree',
  'roleAccess.editTree': 'Edit Family Tree',
  'roleAccess.addMembers': 'Add Family Members',
  'roleAccess.deleteMembers': 'Delete Family Members',
  'roleAccess.manageRoles': 'Manage Roles & Permissions',
  'roleAccess.postFeed': 'Post to Family Feed',
  'roleAccess.viewMemories': 'View Memories',
  'roleAccess.createEvents': 'Create Events',
  'roleSelection.title': 'Select Your Role',
  'roleSelection.grandparent': 'Grandparent',
  'roleSelection.parent': 'Parent',
  'roleSelection.adult': 'Adult',
  'roleSelection.teenager': 'Teenager',
  'roleSelection.child': 'Child',

  // Add these new keys to your existing _enUS map

  // Redeem Controller Data
  'redeem.option.shop.title': 'Shop mall',
  'redeem.option.shop.description':
      'Use coins to buy exclusive family heritage Products.',
  'redeem.option.shop.button': 'Browse Mall',
  'redeem.option.support.title': 'Support Families',
  'redeem.option.support.description': 'Transfer coins to Support a relative.',
  'redeem.option.support.button': 'Send Gift',
  'redeem.option.boost.title': 'Boost Listing',
  'redeem.option.boost.description': 'Promote your products for higher sell.',
  'redeem.option.boost.button': 'Promote Now',

  'earn.completeProfile.title': 'Complete Your Profile',
  'earn.completeProfile.subtitle': 'Earn 60KCC',
  'earn.addPhoto.title': 'Add Family Photo',
  'earn.addPhoto.subtitle': 'Earn 20KCC',
  'earn.inviteMember.title': 'Invite Family Member',
  'earn.inviteMember.subtitle': 'Earn 20KCC',
  'earn.attendEvent.title': 'Attend Family Event',
  'earn.attendEvent.subtitle': 'Earn 45KCC',
  'redeem.featuredRewards': 'Featured Rewards',
  'redeem.completeProfile': 'Complete your profile',
  'redeem.earnKcc': 'Earn @points KCC',

  // ===================================
  // Identity Approval
  // ===================================
  'identity.title': 'Identity Approvals',
  'identity.pendingRequests': 'Pending Requests',
  'identity.noRequests': 'No pending requests',
  'identity.claiming': 'CLAIMING IDENTITY',
  'identity.proof.photo': 'Photo Proof',
  'identity.proof.birth': 'Birth Chart',
  'identity.reject': 'Reject',
  'identity.requestFrom': 'Request From',
  'identity.approve': 'Approve',
  'identity.decline': 'Decline',
  'requestHistory.requestApproved': 'Request Approved',
  'requestHistory.dataChange': 'Data Change',
  'requestHistory.requestSubmitted': 'Request Submitted',
  'requestHistory.adminComment': '“Verified with birth certificate provided via email.”',
  'requestHistory.reviewedBy': 'Reviewed By @admin (Admin)',
  'requestHistory.changeTo': ' change to ',
  'requestHistory.dummyApprovedTime': 'Oct 22, 2025/10:30 Am',
  'requestHistory.dummySubmittedTime': 'Oct 20, 2023 / you',


  // ===================================
  // Family Space
  // ===================================
  'space.switch': 'Switch Space',
  'space.current': 'Current Space',
  'space.other': 'Other Space',
  'space.confirmSwitch': 'Confirm Switch',
  'space.switchedTo': 'You are now in @spaceName',
  'space.online': 'Online',
  'space.members': '@count Member',
  'space.active': 'Active',
  'chooseSpace.welcome': 'Welcome to Kincore!',
  'chooseSpace.subtitle': 'How would you like to start your family journey? Choose an option below.',
  'chooseSpace.createTitle': 'Create New Family Space',
  'chooseSpace.createSubtitle': 'Set up a fresh space for your family to connect, share, and grow.',
  'chooseSpace.joinTitle': 'Join Existing Space',
  'chooseSpace.joinSubtitle': 'Have an invite code or link? Join your family members here.',
  'chooseSpace.joinSnackbarTitle': 'Join Space',
  'chooseSpace.joinSnackbarMsg': 'Navigating to Join Space Screen...',
  'createSpace.appBarTitle': 'Create Family Space',
  'createSpace.welcome': 'Welcome to Kincore!',
  'createSpace.subtitle': 'Set up a dedicated space to connect, share, and grow with your family members.',
  'createSpace.uploadPhoto': 'Upload Space Photo',
  'createSpace.nameLabel': 'Family Space Name',
  'createSpace.nameHint': 'e.g., The Anderson Family',
  'createSpace.descLabel': 'Description (Optional)',
  'createSpace.descHint': 'Write a short bio for your family...',
  'createSpace.createBtn': 'Create Space',
  'createSpace.selectImageTitle': 'Select Image',
  'createSpace.selectImageMsg': 'Image picker will open here.',
  'createSpace.validationErrorTitle': 'Validation Error',
  'createSpace.validationErrorMsg': 'Please enter your Family Space Name.',
  'createSpace.successTitle': 'Success',
  'createSpace.successMsg': 'Family Space \'@name\' created successfully!',
  'chooseSpace.joinOptionsTitle': 'Join a Space',
  'chooseSpace.scanQr': 'Scan QR Code',
  'chooseSpace.scanQrSub': 'Join instantly using a family QR',
  'chooseSpace.joinUrl': 'Join via URL',
  'chooseSpace.joinUrlSub': 'Paste an invite link',
  'chooseSpace.findYourself': 'Find Yourself',
  'chooseSpace.findYourselfSub': 'Search for your profile in a family tree',


  // Add these new keys to your existing _enUS map

  // ===================================
  // Generation Screen
  // ===================================
  'generation.title': 'Generation',
  'generation.noData': 'No Data Found',
  'generation.genSuffix': '@level Generation',
  'generation.members': 'Member',
  'generation.generation': 'Generation',
  'generation.years': 'Year',


  // ===================================
  // Gift & Draw Screens
  // ===================================
  'gift.letsDraw': "Let's draw!",
  'gift.surpriseBegin': 'Let The Surprise Begin!',
  'gift.spinning': 'Spinning...',
  'gift.spinWheel': 'Spin Wheel',
  'gift.exchangeDetails': 'Gift Exchange Details',
  'gift.senderName': "Gift Sender's Name",
  'gift.receiverName': "Gift Receiver's Name",
  'gift.exchangeName': 'Name Your Gift Exchange',
  'gift.selectDate': 'Select Date',
  'gift.budget': 'Gift Budget',
  'gift.addNote': 'Add Note',
  'gift.addGiftPhoto': 'Add Gift Photo',
  'gift.uploadSupport': 'Upload PNG, JPG File Support',
  'gift.sendGift': 'Send Gift',
  'gift.addGiftExchange': 'Add Gift Exchange',
  'gift.eventDetails': 'Event Details',
  'gift.eventName': 'Event Name',
  'gift.festivalType': 'Festival Type',
  'gift.description': 'Description',
  'gift.scope': 'Scope',
  'gift.deadlines': 'Deadlines',
  'gift.signupDeadline': 'Signup Deadline',
  'gift.drawDeadline': 'Draw Deadline',
  'gift.giftDeadline': 'Gift Deadline',
  'gift.budgetPreference': 'Budget & Preference',
  'gift.budgetRange': 'Budget Range: ₹@value',
  'gift.preferredGiftType': 'Preferred Gift Type',
  'gift.anonymity': 'Anonymity',
  'gift.anonymitySub': 'Keep participants secret',
  'gift.createExchange': 'Create Gift Exchange',
  'gift.swapTitle': 'Gift Swap',
  'gift.yourName': 'Your Name',
  'gift.addFriendName': "Add Friend's Name",
  'gift.friendName': "Friend's Name",
  'gift.addMore': '+ Add More',
  'gift.draw': 'Draw',
  'giftSwap.eventDashboard': 'Event Dashboard',
  'giftSwap.budgetDate': 'Budget: @amount • @date',
  'giftSwap.drawResults': 'Draw Results',
  'giftSwap.reshuffle': 'Reshuffle',
  'giftSwap.reshuffleMsg': 'Redrawing pairs based on restrictions...',
  'giftSwap.adminViewOnly': 'Only you (Admin) can see who drew whom.',
  'giftSwap.backToHome': 'Back to Home Screen',
  'giftSwap.setRestrictions': 'Set Draw Restrictions',
  'giftSwap.setRestrictionsSub': 'Prevent certain members from drawing each other',
  'giftSwap.restrictionsTitle': 'Restrictions',
  'giftSwap.restrictionsMsg': 'Here admin can set rules like A cannot draw B.',
  'giftSwap.successTitle': 'Success',
  'giftSwap.createdMsg': 'Gift Swap Event Created Successfully!',
  'gift.selectParticipant': 'Select',
  'gift.selectParticipantsTitle': 'Select Participants',
  'gift.done': 'Done',


  // ===================================
  // Checkout & Order History
  // ===================================
  'checkout.title': 'Checkout',
  'checkout.selectedProduct': 'Selected Product',
  'checkout.shippingAddress': 'Shipping Address',
  'checkout.addressName': 'Home',
  'checkout.addressDetail': 'Near post office, velnath chowk, Junagadh',
  'checkout.paymentMethod': 'Payment Method',
  'checkout.payment.card': 'Credit/Debit Card',
  'checkout.payment.upi': 'UPI',
  'checkout.payment.netbanking': 'Net banking',
  'checkout.applyRewards': 'Apply Rewards',
  'checkout.applyKcc': 'Apply KCC Coins',
  'checkout.apply': 'Apply',
  'checkout.youHaveKcc': 'You have {count} KCC Coins',
  'checkout.billDetails': 'Bill details',
  'checkout.subtotal': 'Subtotal',
  'checkout.shippingFee': 'Shipping Fee',
  'checkout.tax': 'Tax ({percent}%)',
  'checkout.totalAmount': 'Total Amount',
  'checkout.total': 'TOTAL',
  'checkout.placeOrder': 'Place Order',
  'checkout.proceedingSnackbar': 'Redirecting to payment...',
  'checkout.emptyCartSnackbar': 'Add some items first!',
  'cart.title': 'My Cart',
  'cart.empty': 'Your cart is empty',
  'cart.buyNow': 'Buy Now',
  'cart.remove': 'Remove',
  'orderHistory.title': 'Order History',
  'orderHistory.searchHint': 'Search by order id or product',
  'orderHistory.netQty': 'Net Qty. 1',
  'orderHistory.trackOrder': 'Track Order',
  'orderHistory.status.shipped': 'Shipped',
  'orderHistory.status.current': 'Current',
  'orderHistory.status.ago': '2 days Ago',
  'trackOrder.title': 'Track Order',
  'trackOrder.orderId': 'Order ID',
  'trackOrder.expectedDelivery': 'Expected Delivery',
  'trackOrder.trackingHistory': 'Tracking History',
  'trackOrder.stepPlaced': 'Order Placed',
  'trackOrder.stepPayment': 'Payment Confirmed',
  'trackOrder.stepShipped': 'Order Shipped',
  'trackOrder.stepOutForDelivery': 'Out for Delivery',
  'trackOrder.stepDelivered': 'Delivered',
  'trackOrder.expectedToday': 'Expected Today',
  'trackOrder.pending': 'Pending',

  // ===================================
  // Invoice Screen
  // ===================================
  'invoice.title': 'Invoice',
  'invoice.downloadingTitle': 'Download',
  'invoice.downloadingMsg': 'Invoice PDF is downloading...',
  'invoice.taxInvoice': 'Tax Invoice / Bill of Supply',
  'invoice.orderId': 'Order ID',
  'invoice.orderDate': 'Order Date',
  'invoice.paymentMode': 'Payment Mode',
  'invoice.status': 'Status',
  'invoice.paid': 'Paid',
  'invoice.shippingDetails': 'Shipping Details',
  'invoice.orderSummary': 'Order Summary',
  'invoice.shippingFee': 'Shipping Fee',
  'invoice.tax': 'Tax (10%)',
  'invoice.totalAmount': 'Total Amount',
  'invoice.downloadPdf': 'Download PDF',

  // ===================================
  // Scanner Screen
  // ===================================
  'scanner.title': 'My Scanner',
  'scanner.connect': 'Connect With Loved Ones',
  'scanner.instruction': 'Enter An Invite Link OR code To Join\nYour Family\'s Space.',
  'scanner.inviteLinkLabel': 'Invite Link',
  'scanner.inviteLinkHint': 'https://family.app/join/....',
  'scanner.joinBtn': 'Join Space',
  'scanner.myLink': 'My Link',
  'scanner.copiedTitle': 'Link Copied',
  'scanner.copiedMsg': 'Your link has been copied to clipboard.',
  'scanner.or': 'OR',
  'scanner.shareBtn': 'Share QR Code',
  'scanner.shareText': 'Hey! Join my family space on Kincore using my link: @link',
  'scanner.shareSubject': 'Join my Family Space on Kincore',
  'scanner.askAdmin': 'Ask a family Admin to Show you their QR\nCode From Their Profile Settings.',

  'joinOptions.title': 'Join a Space',
  'joinOptions.scanTitle': 'Scan QR Code',
  'joinOptions.scanSub': 'Scan a family QR from camera or gallery',
  'joinOptions.urlTitle': 'Join via URL',
  'joinOptions.urlSub': 'Paste an invitation link here',
  'joinOptions.findTitle': 'Find Yourself',
  'joinOptions.findSub': 'Search your name and claim your identity',
  'urlJoin.title': 'Join via Link',
  'urlJoin.subtitle': 'Paste the family space invitation link below to join instantly.',
  'urlJoin.hint': 'Paste URL here...',
  'urlJoin.submit': 'Join Space',
  'scanner.subtitle': 'Align the family QR code within the frame to scan',
  'scanner.galleryBtn': 'Upload from Gallery',

  // ===================================
  // Security & Privacy
  // ===================================
  'security.title': 'Security & Locking',
  'security.lockProfile': 'Lock Profile',
  'security.lockProfileSub': 'Only confirmed family members can see your photos and posts on your timeline.',
  'security.searchVisibility': 'Search Visibility',
  'security.visibility.everyone': 'Everyone',
  'security.visibility.friends': 'Friends of Friends',
  'security.visibility.family': 'Family Only',
  'security.contactPrivacy': 'Contact Privacy',
  'security.hideEmail': 'Hide Email',
  'security.hideEmailSub': 'Your email will be hidden from everyone except yourself.',
  'security.hidePhone': 'Hide Phone Number',
  'security.hidePhoneSub': 'Your contact number will not be visible to any other users.',
  'security.saveChanges': 'Save Changes',


  // ===================================
  // Kinship Calculator
  // ===================================
  'kinship.resultTitle': 'Kinship Result',
  'kinship.path': 'Path',
  'kinship.details': 'Details',
  'kinship.meaning': 'Meaning',
  'kinship.meaningSub': "The mother of one's mother.",
  'kinship.englishTerm': 'English Term',
  'kinship.englishTermSub': 'Maternal Grandmother',
  'kinship.newCalculation': 'New Calculation',
  'kinship.editPath': 'Edit Path',
  'kinship.pathTitle': 'Relationship Path',
  'kinship.selectPath': 'Select Path',
  'kinship.addNextStep': 'Add Next Step',
  'kinship.calculate': 'Calculate Relationship',


  // ===================================
  // Migration Map
  // ===================================
  'migration.mapTitle': 'Migration Map',
  'migration.historyTitle': 'Migration History',
  'migration.findMember': 'Find Family Member',
  'migration.arrivalYear': 'Arrival: @year',
  'migration.reason': 'Migration Reason',
  'migration.familyMemberCount': 'Family Member(@count)',
  'migration.viewHistory': 'View Migration History',
  'migration.timeline.familyMigration': 'Schmidt Family Migration',
  'migration.timeline.from': 'From',
  'migration.timeline.to': 'To',
  'migration.timeline.viewRoute': 'View Route',


  // ===================================
  // Claim Identity & Request History
  // ===================================
  'claim.title': 'Claim Identity',
  'claim.description': 'To Access Private family Data And Contribute To The Tree,\nPlease Verify Your Identity Securely.',
  'claim.tab.verify': 'Verify Code',
  'claim.tab.confirm': 'Conformation',
  'claim.tab.submit': 'Submit',
  'claim.inviteCode': 'Invited Code',
  'claim.inviteCodeHint': 'Enter the 8-digit Alphanumeric Code From Your Invite.',
  'claim.profileMatch': 'PROFILE MATCH FOUND',
  'claim.thisIsMe': 'Yes, This Is Me',
  'claim.confirmProfile': 'I Confirm This Profile Data Is Accurate',
  'claim.verifyOwnership': 'Verify Ownership',
  'claim.emailHint': 'Enter your email address',
  'claim.govId': 'Government ID (Optional)',
  'claim.addGovId': 'Add Government ID Photo',
  'claim.submitClaim': 'Submit Claim',
  'identity.statusTitle': 'Identity Status',
  'identity.claimPending': 'Claim Pending',
  'identity.status.pending': 'Pending',
  'identity.status.description': 'We Have Received Your Claim For Joseph Ancestor. This Usually Tasks 24-48 Hours.',
  'identity.submittedOn': 'Submitted On',
  'identity.relationship': 'Relationship',
  'identity.relationshipValue': 'Grandfather',
  'identity.verificationProgress': 'Verification Progress',
  'identity.progress.submitted': 'Request Submitted',
  'identity.progress.submittedSub': 'Your Document Were Received',
  'identity.progress.inProgress': 'Verification In Progress',
  'identity.progress.inProgressSub': 'Our Team Is Reviewing Your ID And Relationship Proof.',
  'identity.progress.decision': 'Final Decision',
  'identity.progress.decisionSub': 'Approval Or Request For More Info.',
  'identity.addProof': 'Upload Additional Proof',
  'identity.addProofPhoto': 'Add Additional Proof Photo',
  'identity.backToProfile': 'Back To Profile',
  'requestHistory.title': 'Request History',
  'requestHistory.thisMonth': 'This Month',
  'requestHistory.birthdateUpdate' :'Birthdate Update',
  'changeRelationship.title': 'Change Relationship',
  'changeRelationship.add': 'Add',
  'changeRelationship.remove': 'Remove',
  'changeRelationship.detailTitle': 'Relationship Detail',
  'changeRelationship.typeHint': 'Relationship type',
  'changeRelationship.personHint': 'Select Relates Person',
  'changeRelationship.reasonHint': 'Reason For Change (Required)',
  'changeRelationship.supportDocs': 'Supporting Documents',
  'changeRelationship.security': 'Your Document Are Securely Stored And Visible To Family Admins For Verification Purposes.',
  'changeRelationship.saveNext': 'Save & Next',


  'All': 'All',
  'Pending': 'Pending',
  'Approved': 'Approved',
  'Rejected': 'Rejected',

};
