// lib/localization/es_ES.dart
// Spanish translations for Kincore app

const Map<String, String> esES = {
  // ===================================
  // Common & General
  // ===================================
  'common.add': 'Añadir',
  'common.save': 'Guardar',
  'common.cancel': 'Cancelar',
  'common.delete': 'Eliminar',
  'common.edit': 'Editar',
  'common.viewAll': 'Ver Todo',
  'common.select': 'Seleccionar',
  'common.search': 'Buscar',
  'common.find': 'Encontrar',
  'common.publish': 'Publicar',
  'common.saveAndAdd': 'Guardar y Añadir',
  'common.upload': 'Subir',
  'common.addFile': 'Añadir Archivo',
  'common.savePhotos': 'Guardar Fotos',
  'common.saveMemory': 'Guardar Recuerdo',
  'common.loading': 'Cargando...',
  'common.error': 'Algo salió mal. Por favor, intenta de nuevo.',
  'common.success': 'Éxito',
  'common.productPublished': '¡Producto Publicado Exitosamente!',
  'common.yes': 'Sí',
  'common.no': 'No',
  'common.maybe': 'Quizás',
  'common.select_country': 'Seleccionar País',
  'common.submit': 'Enviar',
  'common.done': 'Hecho',
  'common.next': 'Siguiente',
  'common.continue': 'Continuar',
  'common.all': 'Todo',
  'common.seeAll': 'Ver Todo',
  'common.father': 'Padre',
  'common.mother': 'Madre',
  'common.sister': 'Hermana',
  'common.brother': 'Hermano',
  'common.approved': 'Aprobado',

  // ===================================
  // Auth Screen
  // ===================================
  'auth.kincore': 'Kincore',
  'auth.connect': '¡Conéctate a tus Raíces!',
  'auth.welcomeBack': '¡Bienvenido!',
  'auth.detailsPrompt': 'Ingresa tus Detalles para Iniciar Sesión o crear una cuenta.',
  'auth.signUp': 'Registrarse',
  'auth.logIn': 'Iniciar Sesión',
  'auth.nameLabel': 'Ingresa tu Nombre',
  'auth.nameHint': 'Nombre Apellido',
  'auth.emailLabel': 'Dirección de Email',
  'auth.emailHint': 'abc@gmail.com',
  'auth.passwordLabel': 'Contraseña',
  'auth.passwordHint': '••••••••',
  'auth.confirmPasswordLabel': 'Confirmar Contraseña',
  'auth.forgotPassword': '¿Olvidaste tu Contraseña?',
  'auth.continueWith': 'O Continúa con',
  'auth.google': 'Google',
  'auth.facebook': 'Facebook',
  'auth.back': 'Volver',
  'auth.firstName': 'Nombre',
  'auth.firstNameHint': 'Juan',
  'auth.lastName': 'Apellido',
  'auth.lastNameHint': 'Pérez',
  'auth.dob': 'Fecha de nacimiento (Opcional)',
  'auth.dobHint': 'DD/MM/AAAA',
  'auth.forgotPasswordTitle': 'Olvidé mi contraseña',
  'auth.forgotPasswordHeading': '¿Olvidaste tu contraseña?',
  'auth.forgotPasswordDesc': '¡No te preocupes! Suele pasar. Ingresa la dirección de correo electrónico asociada a tu cuenta.',
  'auth.enterEmail': 'Ingresa tu correo electrónico',
  'auth.sending': 'Enviando...',
  'auth.sendCode': 'Enviar código',

  // ===================================
  // Home Screen
  // ===================================
  'home.title': 'Inicio',
  'home.goodMorning': 'Buenos días',
  'home.upcomingBirthdays': 'Próximos cumpleaños',
  'home.viewCalendar': 'Ver Calendario',
  'home.timeline': 'Línea de Tiempo',
  'home.startBuilding': 'Comienza a Construir tu Árbol Genealógico',
  'home.startBuildingDesc': 'Añade miembros de la familia para ver crecer tu herencia.',
  'home.addFirstMember': 'Añadir Primer Miembro',
  'home.recentMemories': 'Recuerdos Recientes',
  'home.noMemories': 'No se encontraron recuerdos recientes.',
  'home.addFirstMemory': 'Añade tu Primer Recuerdo',
  'home.upcomingEvents': 'Próximos Eventos',
  'home.noEvents': 'No hay eventos próximos.',
  'home.familyEvents': 'Eventos Familiares',
  'home.familyBio': 'Biografía Familiar',
  'home.secretSanta': 'Papá Noel Secreto',
  'home.kinshipCalculator': 'Calculadora de Parentesco',
  'home.identityApproval': 'Aprobación de Identidad',
  'home.migrationMap': 'Mapa de Migración',
  'home.quickModules': 'Módulos Rápidos',
  'home.calculator': 'Calculadora',
  'home.giftSwap': 'Intercambio de Regalos',
  'home.savedFeed': 'Feed Guardado',
  'home.exploreMore': 'Explorar Más',
  'home.marketplace': 'Mercado',
  'home.reels': 'Reels',

  // ===================================
  // Navigation
  // ===================================
  'nav.home': 'Inicio',
  'nav.feed': 'Feed',
  'nav.tree': 'Árbol',
  'nav.mall': 'Centro Comercial',
  'nav.profile': 'Perfil',
  'nav.memory': 'Recuerdo',
  'nav.family': 'Familia',
  'nav.events': 'Eventos',

  // ===================================
  // Tree Screen
  // ===================================
  'tree.title': 'El Clan Harrison',
  'tree.generations': '@count Generación / @members Miembro',
  'tree.webContentView': 'Vista de contenido web',
  'tree.allView': 'Vista completa',
  'tree.directLinage': 'Linaje directo',
  'tree.birthday': 'Cumpleaños',
  'tree.anniversary': 'Aniversario',

  // ===================================
  // Family Bio Screen
  // ===================================
  'familyBio.addTitle': 'Añadir biografía familiar',
  'familyBio.addMedia': 'Añadir Medios',
  'familyBio.dragAndDrop': 'Arrastra y suelta o examina para subir',
  'familyBio.basicInfo': 'Información Básica',
  'familyBio.storyName': 'Nombre de la Historia',
  'familyBio.location': 'Ubicación',
  'familyBio.birthDate': 'Fecha de Nacimiento',
  'familyBio.selectDate': 'Seleccionar Fecha',
  'familyBio.storyBio': 'Historia(Biografía)',
  'familyBio.addBioHint': 'Añade biografía aquí...',
  'familyBio.publishBio': 'Publicar Biografía',
  'familyBio.title': 'Biografía familiar',
  'familyBio.gallery': 'Galería',
  'familyBio.nextInHistory': 'Siguiente en la Historia',
  'familyBio.existingMember': 'Miembro de Familia Existente',
  'familyBio.theRoaringTwenties': 'Los Años Veinte',
  'familyBio.roaringTwentiesDate': '1920 - 1929',
  'familyBio.migrationStoryDate': '4 de Nov, 1920 · Sicilia a Nueva York',
  'familyBio.migrationStoryContent': 'La Gran Migración, un momento crucial en la historia, vio a millones de personas emprender viajes a nuevas tierras, buscando oportunidades y un nuevo comienzo. Entre ellos estaba María Rossi, una joven mujer de Sicilia, que zarpó hacia Nueva York en 1920. Su historia, como la de muchos otros, es un testimonio de valentía, resiliencia y el espíritu humano perdurable.',
  'familyBio.migrationStoryQuote': '"El viaje fue largo y arduo, pero la esperanza de una vida mejor nos mantuvo adelante." – María Rossi',
  'familyBio.errorTitle': 'Error',
  'familyBio.nameRequired': 'El nombre de la historia es obligatorio',
  'familyBio.successTitle': 'Éxito',
  'familyBio.publishedMsg': '¡Biografía publicada!',

  // ===================================
  // Market Place
  // ===================================
  'marketplace.title': 'Mercado',
  'marketplace.searchHint': 'Buscar productos, categorías...',
  'marketplace.bannerTitle': '¡La venta de verano ya está aquí!',
  'marketplace.bannerSub': 'Encuentra las mejores ofertas cerca de ti.',
  'marketplace.noProducts': '¡No se encontraron productos!',
  'marketplace.catAll': 'Todo',
  'marketplace.catVehicles': 'Vehículos',
  'marketplace.catProperty': 'Propiedad',
  'marketplace.catElectronics': 'Electrónica',
  'marketplace.catFurniture': 'Muebles',
  'marketplace.catFashion': 'Moda',
  'marketplace.msgAvailable': 'Hola, ¿sigue disponible?',
  'marketplace.timeJustNow': 'Justo ahora',
  'marketplace.timeYesterday': 'Ayer',
  'marketplace.messages': 'Mensajes',
  'marketplace.noMessages': 'Aún no hay mensajes.',

  // ===================================
  // Add Family Member
  // ===================================
  'addMember.title': 'Añadir Miembro de Familia',
  'addMember.basicInfo': 'Información Básica',
  'addMember.firstName': 'Nombre',
  'addMember.lastName': 'Apellido',
  'addMember.gender': 'Género',
  'addMember.male': 'Masculino',
  'addMember.female': 'Femenino',
  'addMember.other': 'Otro',
  'addMember.dateOfBirth': 'Fecha de Nacimiento',
  'addMember.dateFormatHint': 'MM/DD/YYYY',
  'addMember.relationshipSetup': 'Configuración de Relación',
  'addMember.relationshipType': 'Tipo de Relación',
  'addMember.relationship.spouse': 'Cónyuge',
  'addMember.relationship.sibling': 'Hermano/a',
  'addMember.relationship.parent': 'Padre/Madre',
  'addMember.findFamilyMember': 'Encontrar Miembro de Familia',
  'addMember.spouseName': 'Nombre del Cónyuge',
  'addMember.anniversaryDate': 'Fecha de Aniversario',
  'addMember.additionalDetail': 'Detalle Adicional',
  'addMember.addLocation': 'Añadir ubicación',
  'addMember.occupation': 'Ocupación',
  'addMember.bioNotes': 'Biografía / Notas',
  'addMember.privacyVisibility': 'Privacidad y Visibilidad',
  'addMember.visibleToAll': 'Visible para todos los miembros',
  'addMember.addParentsTitle': 'Añadir Padres',
  'addMember.addOtherMember': 'Añadir Otro Miembro de Familia',
  'addMember.placeOfBirth': 'Lugar de Nacimiento',
  'addMember.currentLocation': 'Ubicación Actual',
  'addMember.addChildTitle': 'Añadir Hijo',
  'addMember.schoolAndCollege': 'Escuela y Universidad',
  'addMember.qualification': 'Calificación',
  'addMember.studyLocation': 'Ubicación de Estudio',
  'addMember.changePhoto': 'Cambiar Fotos',
  'addMember.livingStatus': 'Estado de Vida',
  'addMember.isAlive': '¿La persona aún está viva?',
  'addMember.alive': 'Vivo',
  'addMember.deceased': 'Fallecido',
  'addMember.phoneNumber': 'Número de Teléfono',
  'addMember.phoneHint': '00000 00000',

  // ===================================
  // Memory Screen
  // ===================================
  'memory.title': 'Recuerdo',
  'memory.addTitle': 'Añadir Recuerdo',
  'memory.tabAll': 'Todo',
  'memory.tabPhotos': 'Fotos',
  'memory.tabVideos': 'Videos',
  'memory.addMemoryPhotos': 'Añadir Fotos de Recuerdo',
  'memory.addMemoryVideos': 'Añadir Videos de Recuerdo',
  'memory.uploadSupport': 'Soporte de Archivo PNG, JPG',

  // ===================================
  // K-Mall & Products
  // ===================================
  'mall.title': 'Centro Comercial',
  'mall.searchHint': 'Buscar Productos',
  'mall.filter': 'Filtrar',
  'mall.categories': 'Categorías',
  'mall.featured': 'Destacado',
  'mall.mostPopular': 'Más Popular',
  'mall.onSale': 'En Venta',
  'mall.wishlistTitle': 'Mi Lista de Deseos',
  'mall.noItemsWishlist': '¡Tu lista de deseos está vacía!',
  'mall.exploreProducts': 'Explorar Productos',
  'mall.productDetails': 'Detalles del Producto',
  'mall.description': 'Descripción',
  'mall.selectSize': 'Seleccionar Tamaño',
  'mall.selectColor': 'Seleccionar Color',
  'mall.quantity': 'Cantidad',
  'mall.addToCart': 'Añadir al Carrito',
  'mall.buyNow': 'Comprar Ahora',
  'mall.reviews': 'Reseñas',
  'mall.noReviews': 'Sin reseñas aún para este producto.',
  'mall.sellerInfo': 'Información del Vendedor',
  'mall.viewShop': 'Ver Tienda',
  'mall.relatedProducts': 'Productos Relacionados',
  'mall.addedToCart': '@productName añadido al carrito',
  'mall.filterPrice': 'Rango de Precio',
  'mall.filterColor': 'Color',
  'mall.filterGender': 'Género',
  'mall.category.fashion': 'Moda',
  'mall.category.electronics': 'Electrónica',
  'mall.category.appliances': 'Electrodomésticos',
  'mall.category.beauty': 'Belleza',
  'mall.category.furniture': 'Muebles',
  'mall.banner.title': 'Nueva Colección',
  'mall.banner.discount': '50% DESCUENTO',
  'mall.banner.for': 'Para Niños',
  'mall.productReview': '@rating (@count Reseña)',
  'mall.tag.homeMade': 'Hecho en Casa',
  'mall.tag.newCollection': 'Nueva colección',

  // ===================================
  // Add Product
  // ===================================
  'addProduct.title': 'Añadir Nuevo Producto',
  'addProduct.detailsPrompt': 'Ingresa todos los detalles para listar tu producto',
  'addProduct.uploadImagesTitle': 'Subir Imágenes del Producto',
  'addProduct.uploadImagesDesc': 'Usa imágenes claras de alta resolución. La primera imagen será la portada.',
  'addProduct.addMedia': 'Añadir Medios',
  'addProduct.dragAndDrop': 'Arrastra y suelta o examina para subir',
  'addProduct.basicInfo': 'Información Básica',
  'addProduct.productNameLabel': 'Nombre del Producto (requerido)',
  'addProduct.priceLabel': 'Precio',
  'addProduct.discountLabel': 'Descuento%',
  'addProduct.descriptionLabel': 'Descripción',
  'addProduct.sizeLabel': 'Tamaño',
  'addProduct.conditionsLabel': 'Condiciones',
  'addProduct.brandNameLabel': 'Nombre de Marca',
  'addProduct.profileLabel': 'Selecciona tu Perfil',
  'addProduct.categoryLabel': 'Categoría',
  'addProduct.subCategoryLabel': 'Sub-Categoría',
  'addProduct.quantityLabel': 'Cantidad',
  'addProduct.publishButton': 'Publicar Producto',

  // ===================================
  // Redeem Coin Screen
  // ===================================
  'redeem.title': 'Canjear Monedas KCC',
  'redeem.totalBalance': 'SALDO TOTAL',
  'redeem.kccBalance': 'Saldo KCC',
  'redeem.currency': 'KCC',
  'redeem.waysToRedeem': 'Formas de Canjear',
  'redeem.waysToEarn': 'Formas de Ganar',
  'redeem.recentActivity': 'Actividad Reciente',
  'redeem.vintageCase': 'Caja Vintage',
  'redeem.kmallPurchase': 'Compra en Centro Comercial',
  'redeem.redeemedKcc': '-455 KCC',
  'redeem.shopAndSave': 'Compra y Ahorra',
  'redeem.redeemForCash': 'Canjear por Efectivo',
  'redeem.shopNow': 'Comprar Ahora',
  'redeem.redeemNow': 'Canjear Ahora',
  'redeem.option.shop.title': 'Compra en Centro Comercial',
  'redeem.option.shop.description': 'Usa monedas para comprar productos exclusivos de herencia familiar.',
  'redeem.option.shop.button': 'Explorar Centro Comercial',
  'redeem.option.support.title': 'Apoyar Familias',
  'redeem.option.support.description': 'Transfiere monedas para apoyar a un pariente.',
  'redeem.option.support.button': 'Enviar Regalo',
  'redeem.option.boost.title': 'Impulsar Listado',
  'redeem.option.boost.description': 'Promociona tus productos para mayores ventas.',
  'redeem.option.boost.button': 'Promocionar Ahora',
  'redeem.featuredRewards': 'Recompensas destacadas',
  'redeem.completeProfile': 'Completa tu perfil',
  'redeem.earnKcc': 'Gana @points KCC',

  // ===================================
  // Coin Card Level
  // ===================================
  'profile.levelBadge': 'Nivel @level @title',

  // ===================================
  // Earn
  // ===================================
  'earn.referral': 'Referir un Amigo',
  'earn.referralSub': 'Gana 20 KCC',
  'earn.completeProfile.title': 'Completa tu Perfil',
  'earn.completeProfile.subtitle': 'Gana 60KCC',
  'earn.addPhoto.title': 'Añadir Foto Familiar',
  'earn.addPhoto.subtitle': 'Gana 20KCC',
  'earn.inviteMember.title': 'Invitar Miembro de Familia',
  'earn.inviteMember.subtitle': 'Gana 20KCC',
  'earn.attendEvent.title': 'Asistir a Evento Familiar',
  'earn.attendEvent.subtitle': 'Gana 45KCC',

  // ===================================
  // Create Event Screen
  // ===================================
  'createEvent.title': 'Crear Evento',
  'createEvent.saveDraft': 'Guardar',
  'createEvent.addCoverPhoto': 'Añadir Foto de Portada',
  'createEvent.uploadSupport': 'Soporte de Archivo PNG, JPG',
  'createEvent.detailTitle': 'Detalle del Evento',
  'createEvent.eventTitleLabel': 'Título del Evento',
  'createEvent.eventTitleHint': 'Ingresa Título',
  'createEvent.locationLabel': 'Ubicación',
  'createEvent.locationHint': 'Ingresa Ubicación de Dirección',
  'createEvent.descriptionLabel': 'Descripción',
  'createEvent.descriptionHint': 'Escribe aquí...',
  'createEvent.startDateLabel': 'Fecha de Inicio',
  'createEvent.endDateLabel': 'Fecha de Fin',
  'createEvent.timeLabel': 'Hora',
  'createEvent.timeHint': 'Ingresa Hora',
  'createEvent.inviteMemberTitle': 'Invitar Miembro de Familia',
  'createEvent.starts': 'Inicia',
  'createEvent.ends': 'Termina',
  'createEvent.requestRSVP': 'Solicitar RSVP',
  'createEvent.requestRSVPSub': 'Los invitados deben confirmar asistencia',
  'createEvent.sendReminders': 'Enviar recordatorios',
  'createEvent.sendRemindersSub': 'Notificar a los invitados 1 día antes',
  'createEvent.includeGiftExchange': 'Incluir intercambio de regalos',
  'createEvent.includeGiftExchangeSub': 'ej., Amigo Secreto o Intercambio',
  'createEvent.nextAddGift': 'Siguiente y Añadir Regalo',
  'createEvent.createEventBtn': 'Crear Evento',
  'createEvent.eventCreatedTitle': 'Evento Creado',
  'createEvent.eventCreatedMsg': '¡Tu evento ha sido creado exitosamente!',

  // ===================================
  // Feed & Posts
  // ===================================
  'feed.title': 'Feed Familiar',
  'feed.myStory': 'Mi Historia',
  'feed.whatsHappening': '¿Qué está pasando?',
  'feed.createPost': 'Crear Publicación',
  'feed.archive': 'Archivo',
  'feed.writeCommentHint': 'Escribe un comentario...',
  'feed.viewComments': 'Ver los @count comentarios',
  'feed.postAnonymously': 'Publicar Anónimamente',
  'feed.allowComments': 'Permitir Comentarios',
  'feed.saveToDevice': 'Guardar en dispositivo',
  'feed.reportPost': 'Reportar Publicación',
  'feed.archiveMenu': 'Archivar',
  'feed.reportMenu': 'Reportar',
  'feed.archiveMsg': 'Publicación añadida a tu archivo.',
  'feed.savedTitle': 'Guardado',
  'feed.savedMsg': 'Publicación guardada en tu colección.',
  'feed.removedTitle': 'Eliminado',
  'feed.removedMsg': 'Publicación eliminada de guardados.',
  'feed.caughtUp': '¡Estás al día!',
  'feed.findMore': 'Encuentra más miembros de la familia',
  'feed.writeComment': 'Escribe un comentario...',
  'createPost.successTitle': 'Éxito',
  'createPost.successMsg': '¡Publicación creada con éxito!',
  'createPost.errorTitle': 'Error',
  'createPost.errorMsg': 'Por favor ingresa texto o agrega multimedia.',
  'feed.savedCollection': 'Colección guardada',
  'feed.noSavedPosts': 'Aún no hay publicaciones guardadas',
  'feed.removeFromCollection': 'Eliminar de la colección',

  // ===================================
  // Post Settings
  // ===================================
  'postSettings.title': 'Configuración de Publicación',
  'postSettings.postSettings': 'Configuración de Publicación',
  'postSettings.whoCanSee': '¿Quién puede ver tus publicaciones?',
  'postSettings.visibility.public': 'Público',
  'postSettings.visibility.friends': 'Amigos',
  'postSettings.visibility.friendsExcept': 'Amigos Excepto',
  'postSettings.visibility.specificFriends': 'Amigos Específicos',
  'postSettings.whoCanComment': '¿Quién puede comentar en esta publicación?',
  'postSettings.comments.followersOnly': 'Solo tus Seguidores',
  'postSettings.comments.friends': 'Amigos',
  'postSettings.comments.chosenFriends': 'Amigos Seleccionados',
  'postSettings.saveChanges': 'Guardar Cambios',

  // ===================================
  // Create Post
  // ===================================
  'createPost.title': 'Crear Publicación',
  'createPost.hint': '¿En qué estás pensando?',
  'createPost.addMedia': 'Añadir medios',
  'createPost.tagPeople': 'Etiquetar personas',
  'createPost.postButton': 'Publicar',

  // ===================================
  // Report
  // ===================================
  'report.title': 'Reportar Problema',
  'report.anonymousHelp': 'Tu Reporte es Anónimo. Ayúdanos a Mantener la Comunidad del Árbol Genealógico Segura Diciéndonos Qué está Pasando.',
  'report.reasonTitle': 'Razón del Reporte',
  'report.spam': 'Es Spam',
  'report.nudity': 'Desnudez o Actividad Sexual',
  'report.hateSpeech': 'Discurso de Odio o Símbolos',
  'report.falseInfo': 'Información Falsa',
  'report.harassment': 'Acoso o Bullying',
  'report.other': 'Otra Cosa',
  'report.additionalDetails': 'Detalle Adicional(Opcional)',
  'report.describeIssue': 'Por Favor Describe el Problema para Ayudar Nuestra Revisión',
  'report.submitReport': 'Enviar Reporte',
  'report.dialog.discardTitle': '¿Descartar Reporte?',
  'report.dialog.discardBody': '¿Estás seguro de que quieres cancelar este reporte? Tu progreso se perderá.',
  'report.dialog.stay': 'No, Quedarse',
  'report.dialog.discard': 'Sí, Descartar',

  // ===================================
  // Seller Dashboard
  // ===================================
  'seller.title': 'Panel',
  'seller.overview': 'Descripción General',
  'seller.totalRevenue': 'Ingresos Totales',
  'seller.orders': 'Pedidos',
  'seller.avgOrderValue': 'Valor Promedio de Pedido',
  'seller.products': 'Productos',
  'seller.topProducts': 'Productos Destacados',
  'seller.recentOrders': 'Pedidos Recientes',
  'seller.orderId': 'Pedido',
  'seller.noProducts': 'No hay productos para mostrar.',
  'seller.noOrders': 'Sin pedidos recientes.',
  'seller.noData': 'Datos No Disponibles',

  // ===================================
  // Profile & Settings
  // ===================================
  'profile.title': 'Mi Perfil',
  'profile.followers': 'Seguidores',
  'profile.following': 'Siguiendo',
  'profile.editProfile': 'Editar Perfil',
  'profile.addMember': 'Añadir Miembro',
  'profile.addMemory': 'Añadir Recuerdo',
  'profile.vitalStats': 'Estadísticas Vitales',
  'profile.stat.fullName': 'Nombre Completo',
  'profile.stat.born': 'Nacido',
  'profile.stat.location': 'Ubicación',
  'profile.stat.occupation': 'Ocupación',
  'profile.familyMember': 'Miembro de Familia',
  'profile.keyLifeEvents': 'Eventos Clave de Vida',
  'profile.viewMoreTimeline': 'Ver Más Línea de Tiempo',
  'profile.memories': 'Recuerdos',
  'profile.shareProfile': 'Compartir Perfil',
  'profile.personal': 'Personal',
  'profile.business': 'Negocio',
  'profile.posts': 'Publicaciones',
  'profile.photos': 'Fotos',
  'profile.videos': 'Videos',
  'profile.tagged': 'Etiquetado',
  'profile.myProfile': 'Mi Perfil',
  'profile.sellerDashboard': 'Panel de Vendedor',
  'profile.identityApproval': 'Aprobación de Identidad',
  'profile.redeemCoins': 'Canjear Monedas',
  'profile.settings': 'Configuración',
  'profile.logout': 'Cerrar Sesión',
  'profile.logoutConfirm': '¿Estás seguro de que quieres cerrar sesión?',
  'profile.personalProfile': 'Perfil Personal',
  'profile.roleAccess': 'Tu Rol y Permisos',
  'profile.viewDashboard': 'Ver mi Panel del Vendedor',
  'profile.addProduct': 'Añadir Producto',
  'profile.account': 'Cuenta',
  'profile.personalInfo': 'Información Personal',
  'profile.personalInfoSub': 'Nombre, Email, Número de Teléfono',
  'profile.privacy': 'Privacidad y Seguridad',
  'profile.privacySub': 'Visibilidad del Árbol Genealógico, Contraseña',
  'profile.notifications': 'Notificación',
  'profile.notificationsSub': 'Eventos, actualización, Mensajes',
  'profile.darkMode': 'Modo Oscuro',
  'profile.darkModeSub': 'Alternar tema de aplicación',
  'profile.myOrders': 'Mis Pedidos',
  'profile.myOrdersSub': 'Historial de Pedidos, Devoluciones',
  'profile.myListings': 'Mis listados',
  'profile.myListingsSub': 'Gestión Para Venta',
  'profile.privacyLocked': 'Privacidad: Bloqueada',
  'profile.privacyUnlocked': 'Privacidad: Desbloqueada',
  'profile.message': 'Mensaje',
  'profile.viewFeed': 'Ver Feed',
  'profile.viewStory': 'Ver Historia',
  'profile.viewProfilePic': 'Ver Foto de Perfil',
  'profile.viewUserFeed': 'Ver Feed del Usuario',
  'profile.privacyLockedTitle': 'Privacidad bloqueada 🔒',
  'profile.privacyUnlockedTitle': 'Privacidad desbloqueada 🔓',
  'profile.privacyLockedMsg': 'Tu perfil ahora es privado.',
  'profile.privacyUnlockedMsg': 'Tu perfil ahora es visible para los demás.',
  'profile.requestHistory': 'Historial de Solicitudes',
  'profile.requestHistorySub': 'Revisa tu historial de solicitudes',
  'profile.saveFeed': 'Feed Guardado',
  'profile.saveFeedSub': 'Colección de Feed Guardado',
  'profile.giftSwap': 'Intercambio de Regalos',
  'profile.giftSwapSub': 'Tu Intercambio de Regalos',
  'profile.displayMode': 'Modo de Visualización',
  'profile.displayModeSub': 'Ajustar apariencia (Claro/Oscuro)',
  'giftSwap.setRestrictions': 'Establecer restricciones de sorteo',
  'giftSwap.setRestrictionsSub': 'Evitar que ciertos miembros se sorteen entre sí',
  'giftSwap.restrictionsTitle': 'Restricciones',
  'giftSwap.restrictionsMsg': 'Aquí el administrador puede establecer reglas como que A no puede sortear a B.',
  'giftSwap.successTitle': 'Éxito',
  'giftSwap.createdMsg': '¡Evento de intercambio de regalos creado con éxito!',
  'profile.display': 'Pantalla',
  'profile.chooseAppearance': 'Elegir apariencia',
  'profile.lightMode': 'Modo Claro',
  'profile.systemPref': 'Preferencia del Sistema',
  'profile.systemPrefSub': 'Ajustar a la configuración del dispositivo',

  // ===================================
  // Edit Profile
  // ===================================
  'editProfile.title': 'Editar Perfil',
  'editProfile.changePhoto': 'Cambiar Fotos',
  'editProfile.firstNameLabel': 'Nombre',
  'editProfile.firstNameHint': 'Ingresa Nombre',
  'editProfile.lastNameLabel': 'Apellido',
  'editProfile.lastNameHint': 'Ingresa Apellido',
  'editProfile.endDateLabel': 'Fecha de Fin',
  'editProfile.locationLabel': 'Ubicación',
  'editProfile.locationHint': 'Ingresa Ubicación de Dirección',
  'editProfile.occupationLabel': 'Ocupación',
  'editProfile.occupationHint': 'Ingresa Ocupación',
  'editProfile.designationLabel': 'Designación',
  'editProfile.designationHint': 'Ingresa Descripción',
  'editProfile.companyNameLabel': 'Nombre de Empresa',
  'editProfile.companyNameHint': 'Ingresa Nombre de Empresa',
  'editProfile.websiteLabel': 'Sitio Web',
  'editProfile.websiteHint': 'Pega tu Sitio Web',
  'editProfile.linkedInLabel': 'LinkedIn',
  'editProfile.linkedInHint': 'Pega Enlace de LinkedIn',
  'editProfile.instagramLabel': 'Instagram',
  'editProfile.instagramHint': 'Pega Enlace de Instagram',
  'editProfile.facebookLabel': 'Facebook',
  'editProfile.facebookHint': 'Pega Enlace de Facebook',
  'editProfile.otherLinkLabel': 'Otro Enlace',
  'editProfile.otherLinkHint': 'Pega otro Enlace',
  'editProfile.addOtherLink': 'Añadir Otro Enlace',
  'editProfile.claimIdentity': 'Reclamar Identidad',

  // ===================================
  // Events
  // ===================================
  'event.status.attended': 'Asistió',
  'event.status.notAttended': 'No Asistió',
  'event.status.joinnow': 'Únete Ahora',
  'event.detailTitle': 'Detalle del Evento',
  'event.hostedBy': 'ALOJADO POR',
  'event.areYouGoing': '¿Vas a ir?',
  'event.responseRequired': 'Respuesta Requerida',
  'event.going': 'Yendo',

  // ===================================
  // Family Events
  // ===================================
  'familyEvents.title': 'Eventos Familiares',
  'familyEvents.findHint': 'Encontrar Evento',
  'familyEvents.tabUpcoming': 'Próximo',
  'familyEvents.tabPast': 'Pasado',

  // ===================================
  // Member List
  // ===================================
  'memberList.title': 'Todos los Miembros de Familia',
  'memberList.tabFamilies': 'Familias',
  'memberList.tabPeople': 'Personas',
  'memberList.noMembers': 'No se encontraron miembros',
  'memberList.present': 'Presente',
  'memberList.location': 'California, USA',

  // ===================================
  // Find Yourself
  // ===================================
  'findYourself.title': 'Encuéntrate a Ti Mismo',
  'findYourself.searchHint': 'Encontrar Nombre/Fecha de Cumpleaños',
  'findYourself.bestMatches': 'Mejores Coincidencias',
  'findYourself.foundCount': '@count Encontrado',
  'findYourself.notListed': '¿No Listado? Por Favor Crear Perfil',
  'findYourself.thisIsMe': 'Este Soy Yo',
  'findYourself.subtitle': 'Busca tu nombre para vincular tu cuenta al\nregistro del árbol genealógico existente.',
  'findYourself.possibleMatches': 'Coincidencias posibles',
  'findYourself.selectionReqTitle': 'Selección requerida',
  'findYourself.selectionReqMsg': 'Por favor, selecciona tu perfil primero.',
  'findYourself.firstName': 'Nombre',
  'findYourself.lastName': 'Apellido',
  'findYourself.gender': 'Género',
  'findYourself.selectGender': 'Seleccionar género',
  'findYourself.dob': 'Fecha de nacimiento',
  'findYourself.yearOnly': 'Coincidencia solo por año',
  'findYourself.searchBtn': 'Buscar',
  'findYourself.clearBtn': 'Borrar',
  'findYourself.initialMsg': 'Introduce al menos un campo y toca Buscar.',
  'findYourself.noResults': 'No se encontraron resultados',
  'findYourself.noResultsSub': 'Intenta ajustar tus términos de búsqueda o borrar los filtros.',
  'findYourself.resultsCount': '@count resultados encontrados',
  'findYourself.validationMsg': 'Por favor, introduce al menos un campo para buscar.',
  'findYourself.male': 'Masculino',
  'findYourself.female': 'Femenino',
  'findYourself.other': 'Otro',
  'findYourself.firstNameHint': 'Ingresar nombre',
  'findYourself.lastNameHint': 'Ingresar apellido',
  'findYourself.dobHint': 'Seleccionar fecha',

  // ===================================
  // Find Member
  // ===================================
  'findMember.title': 'Encontrar Miembro de Familia',
  'findMember.searchHint': 'Encontrar Miembro de Familia',
  'findMember.lastViewed': 'Últimamente Visto',

  // ===================================
  // Role & Access
  // ===================================
  'role.title': 'Rol y Acceso',
  'role.currentRole': 'Rol Actual: @role',
  'role.familySpace': 'Espacio de Familia Smith',
  'role.adminAccessTitle': 'Acceso de Administración',
  'role.adminAccessDesc': 'Los Administradores tienen Control Total sobre el Espacio de Familia. Pueden gestionar miembros y configurar ajustes.',
  'role.permission.editTree': 'Edición del Árbol Genealógico',
  'role.permission.editTreeSub': 'Agregar Editar O Eliminar Cualquier Perfil',
  'role.permission.memberMgmt': 'Gestión de Miembros',
  'role.permission.memberMgmtSub': 'Invitar Nuevos Usuarios y Asignar Roles',
  'role.permission.spaceSettings': 'Configuración del Espacio',
  'role.permission.spaceSettingsSub': 'Cambiar Privacidad y Notificaciones',
  'role.permission.contentModeration': 'Moderación de Contenido',
  'role.permission.contentModerationSub': 'Gestionar Álbumes y Publicaciones Eliminadas',
  'role.warning': 'Solo el Creador de Familia Puede Transferir la Propiedad O Eliminar Todo el Espacio de Familia.',
  'role.changePermission': '¿Necesitas Cambiar tus Permisos?',
  'role.contactCreator': 'Contactar al Creador de Familia',
  'role.saveAndCreate': 'Guardar y crear',
  'role.limitedAccess': 'Acceso Limitado',
  'role.limitedAccessDesc': 'No puede ver información confidencial o editar el árbol.',
  'role.fullAccess': 'Acceso Completo',
  'role.fullAccessDesc': 'Puede ver toda la información y editar el árbol genealógico.',
  'role.admin': 'Administrador',
  'role.member': 'Miembro',
  'role.guest': 'Invitado',

  // ===================================
  // Family Space
  // ===================================
  'chooseSpace.welcome': '¡Bienvenido a Kincore!',
  'chooseSpace.subtitle': '¿Cómo te gustaría comenzar tu viaje familiar? Elige una opción a continuación.',
  'chooseSpace.createTitle': 'Crear nuevo espacio familiar',
  'chooseSpace.createSubtitle': 'Configura un nuevo espacio para que tu familia se conecte, comparta y crezca.',
  'chooseSpace.joinTitle': 'Unirse a un espacio existente',
  'chooseSpace.joinSubtitle': '¿Tienes un código de invitación o enlace? Únete a los miembros de tu familia aquí.',
  'chooseSpace.joinSnackbarTitle': 'Unirse al espacio',
  'chooseSpace.joinSnackbarMsg': 'Navegando a la pantalla de unirse al espacio...',
  'createSpace.appBarTitle': 'Crear espacio familiar',
  'createSpace.welcome': '¡Bienvenido a Kincore!',
  'createSpace.subtitle': 'Configura un espacio dedicado para conectarte, compartir y crecer con los miembros de tu familia.',
  'createSpace.uploadPhoto': 'Subir foto del espacio',
  'createSpace.nameLabel': 'Nombre del espacio familiar',
  'createSpace.nameHint': 'Ej., La familia Anderson',
  'createSpace.descLabel': 'Descripción (Opcional)',
  'createSpace.descHint': 'Escribe una breve biografía para tu familia...',
  'createSpace.createBtn': 'Crear espacio',
  'createSpace.selectImageTitle': 'Seleccionar imagen',
  'createSpace.selectImageMsg': 'El selector de imágenes se abrirá aquí.',
  'createSpace.validationErrorTitle': 'Error de validación',
  'createSpace.validationErrorMsg': 'Por favor ingresa el nombre de tu espacio familiar.',
  'createSpace.successTitle': 'Éxito',
  'createSpace.successMsg': '¡Espacio familiar \'@name\' creado con éxito!',
  'chooseSpace.joinOptionsTitle': '加入空间',
  'chooseSpace.scanQr': '扫描二维码',
  'chooseSpace.scanQrSub': '使用家庭二维码立即加入',
  'chooseSpace.joinUrl': '通过 URL 加入',
  'chooseSpace.joinUrlSub': '粘贴邀请链接',
  'chooseSpace.findYourself': '找到你自己',
  'chooseSpace.findYourselfSub': '在主页树中搜索您的个人资料',
  'joinOptions.title': 'Unirse a un espacio',
  'joinOptions.scanTitle': 'Escanear código QR',
  'joinOptions.scanSub': 'Escanea un QR familiar desde la cámara o galería',
  'joinOptions.urlTitle': 'Unirse a través de URL',
  'joinOptions.urlSub': 'Pega un enlace de invitación aquí',
  'joinOptions.findTitle': 'Encuéntrate a ti mismo',
  'joinOptions.findSub': 'Busca tu nombre y reclama tu identidad',
  'urlJoin.title': 'Unirse a través de enlace',
  'urlJoin.subtitle': 'Pega el enlace de invitación del espacio familiar a continuación.',
  'urlJoin.hint': 'Pega la URL aquí...',
  'urlJoin.submit': 'Unirse al espacio',
  'scanner.title': 'Escanear código QR',
  'scanner.subtitle': 'Alinea el código QR familiar dentro del marco',
  'scanner.galleryBtn': 'Subir desde la galería',

  // ===================================
  // Role Access
  // ===================================
  'roleAccess.title': 'Rol y Acceso',
  'roleAccess.manager': 'Gerente',
  'roleAccess.permissions': 'Permisos',
  'roleAccess.viewTree': 'Ver Árbol Genealógico',
  'roleAccess.editTree': 'Editar Árbol Genealógico',
  'roleAccess.addMembers': 'Añadir Miembros de Familia',
  'roleAccess.deleteMembers': 'Eliminar Miembros de Familia',
  'roleAccess.manageRoles': 'Gestionar Roles y Permisos',
  'roleAccess.postFeed': 'Publicar en Feed Familiar',
  'roleAccess.viewMemories': 'Ver Recuerdos',
  'roleAccess.createEvents': 'Crear Eventos',

  // ===================================
  // Role Selection
  // ===================================
  'roleSelection.title': 'Selecciona tu Rol',
  'roleSelection.grandparent': 'Abuelo/a',
  'roleSelection.parent': 'Padre/Madre',
  'roleSelection.adult': 'Adulto',
  'roleSelection.teenager': 'Adolescente',
  'roleSelection.child': 'Niño',

  // ===================================
  // Identity Approval
  // ===================================
  'identity.title': 'Aprobaciones de Identidad',
  'identity.pendingRequests': 'Solicitudes Pendientes',
  'identity.noRequests': 'Sin solicitudes pendientes',
  'identity.claiming': 'RECLAMANDO IDENTIDAD',
  'identity.proof.photo': 'Prueba Fotográfica',
  'identity.proof.birth': 'Certificado de Nacimiento',
  'identity.reject': 'Rechazar',
  'identity.requestFrom': 'Solicitud de',
  'identity.approve': 'Aprobar',
  'identity.decline': 'Rechazar',
  'identity.statusTitle': 'Estado de Identidad',
  'identity.claimPending': 'Reclamo Pendiente',
  'identity.status.pending': 'Pendiente',
  'identity.status.description': 'Hemos Recibido tu Reclamo para Joseph Antepasado. Esto Usualmente Toma 24-48 Horas.',
  'identity.submittedOn': 'Enviado el',
  'identity.relationship': 'Relación',
  'identity.relationshipValue': 'Abuelo',
  'identity.verificationProgress': 'Progreso de Verificación',
  'identity.progress.submitted': 'Solicitud Enviada',
  'identity.progress.submittedSub': 'Tus Documentos Fueron Recibidos',
  'identity.progress.inProgress': 'Verificación en Progreso',
  'identity.progress.inProgressSub': 'Nuestro Equipo está Revisando tu ID y Prueba de Relación.',
  'identity.progress.decision': 'Decisión Final',
  'identity.progress.decisionSub': 'Aprobación O Solicitud de Más Información.',
  'identity.addProof': 'Subir Prueba Adicional',
  'identity.addProofPhoto': 'Añadir Foto de Prueba Adicional',
  'identity.backToProfile': 'Volver al Perfil',
  'requestHistory.requestApproved': 'Solicitud aprobada',
  'requestHistory.dataChange': 'Cambio de datos',
  'requestHistory.requestSubmitted': 'Solicitud enviada',
  'requestHistory.adminComment': '“Verificado con certificado de nacimiento proporcionado por correo electrónico.”',
  'requestHistory.reviewedBy': 'Revisado por @admin (Administrador)',
  'requestHistory.changeTo': ' cambiar a ',
  'requestHistory.dummyApprovedTime': '22 Oct, 2025/10:30 Am',
  'requestHistory.dummySubmittedTime': '20 Oct, 2023 / tú',

  // ===================================
  // Space Management
  // ===================================
  'space.switch': 'Cambiar Espacio',
  'space.current': 'Espacio Actual',
  'space.other': 'Otro Espacio',
  'space.confirmSwitch': 'Confirmar Cambio',
  'space.switchedTo': 'Ahora estás en @spaceName',
  'space.online': 'En Línea',
  'space.members': '@count Miembro',
  'space.active': 'Activo',

  // ===================================
  // Generation Screen
  // ===================================
  'generation.title': 'Generación',
  'generation.noData': 'No Se Encontraron Datos',
  'generation.genSuffix': '@level Generación',
  'generation.members': 'Miembro',
  'generation.generation': 'Generación',
  'generation.years': 'Año',

  // ===================================
  // Gift & Draw Screens
  // ===================================
  'gift.letsDraw': '¡Vamos a sortear!',
  'gift.surpriseBegin': '¡Que Comience la Sorpresa!',
  'gift.spinning': 'Girando...',
  'gift.spinWheel': 'Girar Rueda',
  'gift.exchangeDetails': 'Detalles del Intercambio de Regalo',
  'gift.senderName': 'Nombre del Remitente de Regalo',
  'gift.receiverName': 'Nombre del Receptor de Regalo',
  'gift.exchangeName': 'Nombra tu Intercambio de Regalo',
  'gift.selectDate': 'Seleccionar Fecha',
  'gift.budget': 'Presupuesto de Regalo',
  'gift.addNote': 'Añadir Nota',
  'gift.addGiftPhoto': 'Añadir Foto de Regalo',
  'gift.uploadSupport': 'Soporte de Archivo PNG, JPG',
  'gift.sendGift': 'Enviar Regalo',
  'gift.addGiftExchange': 'Añadir Intercambio de Regalo',
  'gift.eventDetails': 'Detalles del Evento',
  'gift.eventName': 'Nombre del Evento',
  'gift.festivalType': 'Tipo de Festival',
  'gift.description': 'Descripción',
  'gift.scope': 'Alcance',
  'gift.deadlines': 'Fechas Límite',
  'gift.signupDeadline': 'Fecha Límite de Inscripción',
  'gift.drawDeadline': 'Fecha Límite de Sorteo',
  'gift.giftDeadline': 'Fecha Límite de Regalo',
  'gift.budgetPreference': 'Presupuesto y Preferencia',
  'gift.budgetRange': 'Rango de Presupuesto: ₹@value',
  'gift.preferredGiftType': 'Tipo de Regalo Preferido',
  'gift.anonymity': 'Anonimato',
  'gift.anonymitySub': 'Mantén a los participantes en secreto',
  'gift.createExchange': 'Crear Intercambio de Regalo',
  'gift.swapTitle': 'Intercambio de Regalos',
  'gift.yourName': 'Tu Nombre',
  'gift.addFriendName': 'Añadir Nombre de Amigo',
  'gift.friendName': 'Nombre del Amigo',
  'gift.addMore': '+ Añadir Más',
  'gift.draw': 'Sortear',
  'giftSwap.eventDashboard': 'Panel del Evento',
  'giftSwap.budgetDate': 'Presupuesto: @amount • @date',
  'giftSwap.drawResults': 'Resultados del Sorteo',
  'giftSwap.reshuffle': 'Reorganizar',
  'giftSwap.reshuffleMsg': 'Redibujando pares basados en restricciones...',
  'giftSwap.adminViewOnly': 'Solo tú (Administrador) puedes ver quién sorteó a quién.',
  'giftSwap.backToHome': 'Volver a la pantalla de inicio',
  'gift.selectParticipant': 'Seleccionar',
  'gift.selectParticipantsTitle': 'Seleccionar Participantes',
  'gift.done': 'Hecho',

  // ===================================
  // Checkout & Order History
  // ===================================
  'checkout.title': 'Finalizar Compra',
  'checkout.selectedProduct': 'Producto Seleccionado',
  'checkout.shippingAddress': 'Dirección de Envío',
  'checkout.addressName': 'Casa',
  'checkout.addressDetail': 'Cerca de la oficina de correos, velnath chowk, Junagadh',
  'checkout.paymentMethod': 'Método de Pago',
  'checkout.payment.card': 'Tarjeta de Crédito/Débito',
  'checkout.payment.upi': 'UPI',
  'checkout.payment.netbanking': 'Banca en Línea',
  'checkout.applyRewards': 'Aplicar Recompensas',
  'checkout.applyKcc': 'Aplicar Monedas KCC',
  'checkout.apply': 'Aplicar',
  'checkout.youHaveKcc': 'Tienes {count} Monedas KCC',
  'checkout.billDetails': 'Detalles de la Factura',
  'checkout.subtotal': 'Subtotal',
  'checkout.shippingFee': 'Costo de Envío',
  'checkout.tax': 'Impuesto ({percent}%)',
  'checkout.totalAmount': 'Monto Total',
  'checkout.total': 'TOTAL',
  'checkout.placeOrder': 'Realizar Pedido',
  'checkout.proceedingSnackbar': 'Redirigiendo al pago...',
  'checkout.emptyCartSnackbar': '¡Añade algunos artículos primero!',
  'trackOrder.title': 'Rastrear Pedido',
  'trackOrder.orderId': 'ID del Pedido',
  'trackOrder.expectedDelivery': 'Entrega Esperada',
  'trackOrder.trackingHistory': 'Historial de Rastreo',
  'trackOrder.stepPlaced': 'Pedido Realizado',
  'trackOrder.stepPayment': 'Pago Confirmado',
  'trackOrder.stepShipped': 'Pedido Enviado',
  'trackOrder.stepOutForDelivery': 'En Camino',
  'trackOrder.stepDelivered': 'Entregado',
  'trackOrder.expectedToday': 'Esperado Hoy',
  'trackOrder.pending': 'Pendiente',

  // ===================================
  // Invoice Screen
  // ===================================
  'invoice.title': 'Factura',
  'invoice.downloadingTitle': 'Descargar',
  'invoice.downloadingMsg': 'Descargando el PDF de la factura...',
  'invoice.taxInvoice': 'Factura de impuestos / Factura de suministro',
  'invoice.orderId': 'ID del pedido',
  'invoice.orderDate': 'Fecha del pedido',
  'invoice.paymentMode': 'Método de pago',
  'invoice.status': 'Estado',
  'invoice.paid': 'Pagado',
  'invoice.shippingDetails': 'Detalles de envío',
  'invoice.orderSummary': 'Resumen del pedido',
  'invoice.shippingFee': 'Tarifa de envío',
  'invoice.tax': 'Impuestos (10%)',
  'invoice.totalAmount': 'Cantidad total',
  'invoice.downloadPdf': 'Descargar PDF',

  // ===================================
  // Scanner Screen
  // ===================================
  'scanner.connect': 'Conéctate con tus seres queridos',
  'scanner.instruction': 'Ingresa un enlace de invitación O código para unirte\nal espacio de tu familia.',
  'scanner.inviteLinkLabel': 'Enlace de invitación',
  'scanner.inviteLinkHint': 'https://family.app/join/....',
  'scanner.joinBtn': 'Unirse al espacio',
  'scanner.myLink': 'Mi enlace',
  'scanner.copiedTitle': 'Enlace copiado',
  'scanner.copiedMsg': 'Tu enlace ha sido copiado al portapapeles.',
  'scanner.or': 'O',
  'scanner.shareBtn': 'Compartir código QR',
  'scanner.shareText': '¡Oye! Únete a mi espacio familiar en Kincore usando mi enlace: @link',
  'scanner.shareSubject': 'Únete a mi espacio familiar en Kincore',
  'scanner.askAdmin': 'Pídele a un administrador familiar que te muestre su código QR\ndesde la configuración de su perfil.',

  // ===================================
  // Cart
  // ===================================
  'cart.title': 'Mi Carrito',
  'cart.empty': 'Tu carrito está vacío',
  'cart.buyNow': 'Comprar Ahora',
  'cart.remove': 'Eliminar',

  // ===================================
  // Order History
  // ===================================
  'orderHistory.title': 'Historial de Pedidos',
  'orderHistory.searchHint': 'Busca por ID de pedido o producto',
  'orderHistory.netQty': 'Cantidad Neta. 1',
  'orderHistory.trackOrder': 'Rastrear Pedido',
  'orderHistory.status.shipped': 'Enviado',
  'orderHistory.status.current': 'Actual',
  'orderHistory.status.ago': 'Hace 2 días',

  // ===================================
  // Security & Privacy
  // ===================================
  'security.title': 'Seguridad y Bloqueo',
  'security.lockProfile': 'Bloquear Perfil',
  'security.lockProfileSub': 'Solo los miembros de la familia confirmados pueden ver tus fotos y publicaciones en tu línea de tiempo.',
  'security.searchVisibility': 'Visibilidad de Búsqueda',
  'security.visibility.everyone': 'Todos',
  'security.visibility.friends': 'Amigos de Amigos',
  'security.visibility.family': 'Solo Familia',
  'security.contactPrivacy': 'Privacidad de Contacto',
  'security.hideEmail': 'Ocultar Email',
  'security.hideEmailSub': 'Tu email será ocultado de todos excepto de ti.',
  'security.hidePhone': 'Ocultar Número de Teléfono',
  'security.hidePhoneSub': 'Tu número de contacto no será visible para otros usuarios.',
  'security.saveChanges': 'Guardar Cambios',

  // ===================================
  // Kinship Calculator
  // ===================================
  'kinship.resultTitle': 'Resultado de Parentesco',
  'kinship.path': 'Ruta',
  'kinship.details': 'Detalles',
  'kinship.meaning': 'Significado',
  'kinship.meaningSub': 'La madre de la madre de una persona.',
  'kinship.englishTerm': 'Término en Inglés',
  'kinship.englishTermSub': 'Abuela Materna',
  'kinship.newCalculation': 'Nuevo Cálculo',
  'kinship.editPath': 'Editar Ruta',
  'kinship.pathTitle': 'Ruta de Relación',
  'kinship.selectPath': 'Seleccionar Ruta',
  'kinship.addNextStep': 'Añadir Siguiente Paso',
  'kinship.calculate': 'Calcular Relación',

  // ===================================
  // Migration Map
  // ===================================
  'migration.mapTitle': 'Mapa de Migración',
  'migration.historyTitle': 'Historial de Migración',
  'migration.findMember': 'Encontrar Miembro de Familia',
  'migration.arrivalYear': 'Llegada: @year',
  'migration.reason': 'Razón de Migración',
  'migration.familyMemberCount': 'Miembro de Familia(@count)',
  'migration.viewHistory': 'Ver Historial de Migración',
  'migration.timeline.familyMigration': 'Migración de la Familia Schmidt',
  'migration.timeline.from': 'De',
  'migration.timeline.to': 'A',
  'migration.timeline.viewRoute': 'Ver Ruta',

  // ===================================
  // Claim Identity
  // ===================================
  'claim.title': 'Reclamar Identidad',
  'claim.description': 'Para Acceder a Datos Familiares Privados Y Contribuir al Árbol,\nPor Favor Verifica tu Identidad de Forma Segura.',
  'claim.tab.verify': 'Verificar Código',
  'claim.tab.confirm': 'Confirmación',
  'claim.tab.submit': 'Enviar',
  'claim.inviteCode': 'Código Invitado',
  'claim.inviteCodeHint': 'Ingresa el Código Alfanumérico de 8 Dígitos de tu Invitación.',
  'claim.profileMatch': 'COINCIDENCIA DE PERFIL ENCONTRADA',
  'claim.thisIsMe': 'Sí, Este Soy Yo',
  'claim.confirmProfile': 'Confirmo que los Datos de este Perfil son Precisos',
  'claim.verifyOwnership': 'Verificar Propiedad',
  'claim.emailHint': 'Ingresa tu dirección de email',
  'claim.govId': 'ID del Gobierno (Opcional)',
  'claim.addGovId': 'Añadir Foto de ID del Gobierno',
  'claim.submitClaim': 'Enviar Reclamación',

  // ===================================
  // Request History
  // ===================================
  'requestHistory.title': 'Historial de Solicitudes',
  'requestHistory.thisMonth': 'Este Mes',
  'requestHistory.birthdateUpdate': 'Actualización de Fecha de Nacimiento',

  // ===================================
  // Change Relationship
  // ===================================
  'changeRelationship.title': 'Cambiar Relación',
  'changeRelationship.add': 'Añadir',
  'changeRelationship.remove': 'Eliminar',
  'changeRelationship.detailTitle': 'Detalle de Relación',
  'changeRelationship.typeHint': 'Tipo de relación',
  'changeRelationship.personHint': 'Seleccionar Persona Relacionada',
  'changeRelationship.reasonHint': 'Razón del Cambio (Requerido)',
  'changeRelationship.supportDocs': 'Documentos de Apoyo',
  'changeRelationship.security': 'Tus Documentos Se Almacenan de Forma Segura Y Son Visibles para Los Administradores de Familia para Fines de Verificación.',
  'changeRelationship.saveNext': 'Guardar y Siguiente',

  'All': 'Todos',
  'Pending': 'Pendiente',
  'Approved': 'Aprobado',
  'Rejected': 'Rechazado',
};
