/// Japanese translations for Kincore app
/// 日本語の翻訳
const Map<String, String> jaJP_ = {
  /// ===================== COMMON & GENERAL =====================
  'app.name': 'Kincore',
  'btn.confirm': '確認',
  'btn.cancel': 'キャンセル',
  'btn.save': '保存',
  'btn.delete': '削除',
  'btn.edit': '編集',
  'btn.next': '次へ',
  'btn.back': '戻る',
  'btn.submit': '送信',
  'btn.skip': 'スキップ',
  'btn.done': '完了',
  'btn.continue': '続行',
  'btn.clear': 'クリア',
  'btn.upload': 'アップロード',
  'btn.view_all': 'すべて表示',
  'btn.no_stay': 'いいえ、留まる',
  'btn.yes_discard': 'はい、削除',
  'btn.approve': '承認',
  'btn.decline': '却下',
  'msg.loading': '読み込み中...',
  'msg.error': '問題が発生しました',
  'msg.success': '成功！',
  'msg.confirm_action': 'よろしいですか?',

  /// ===================== LANGUAGE SELECTION =====================
  'lang.select_title': '言語を選択してください',
  'lang.select_desc': '使用する言語を選択して開始してください。',
  'lang.confirm_btn': '言語を確認',
  'lang.english': 'English',
  'lang.chinese': '中文',
  'lang.spanish': 'Español',
  'lang.malay': 'Bahasa Melayu',
  'lang.japanese': '日本語',

  /// ===================== AUTHENTICATION =====================
  'auth.app_title': 'Kincore',
  'auth.app_tagline': 'あなたのルーツに接続しましょう！',
  'auth.welcome_back': 'おかえりなさい！',
  'auth.form_desc': 'ログインするか、アカウントを作成するには詳細を入力してください。',
  'auth.signup_tab': 'サインアップ',
  'auth.login_tab': 'ログイン',
  'auth.email_label': 'メールアドレス',
  'auth.email_hint': 'abc@gmail.com',
  'auth.password_label': 'パスワード',
  'auth.password_hint': '••••••••',
  'auth.confirm_password_label': 'パスワードを確認',
  'auth.name_label': 'フルネーム',
  'auth.name_hint': '太郎 山田',
  'auth.phone_label': '電話番号',
  'auth.phone_hint': '電話番号を入力',
  'auth.terms_agreement': '利用規約に同意します',
  'auth.terms_desc': 'サインアップすることで、当社の利用規約とプライバシーポリシーに同意したことになります。',
  'auth.forgot_password': 'パスワードをお忘れですか？',
  'auth.dont_have_account': 'アカウントをお持ちですか?',
  'auth.already_have_account': 'すでにアカウントをお持ちですか？',
  'auth.signup_btn': 'サインアップ',
  'auth.login_btn': 'ログイン',
  'auth.otp_verify': 'OTPを確認',
  'auth.resend_otp': 'OTPを再送信',
  'auth.otp_sent': 'OTPがメールアドレスに送信されました',
  'auth.google' : 'Google',
  'auth.facebook' : 'Facebook',
  'auth.continue' : 'Or Continue With',


  /// ===================== SPLASH SCREEN =====================
  'splash.loading': 'ファミリーツリーを読み込み中...',

  /// ===================== DASHBOARD & NAVIGATION =====================
  'nav.home': 'ホーム',
  'nav.family': 'ファミリー',
  'nav.events': 'イベント',
  'nav.feed': 'フィード',
  'nav.profile': 'プロフィール',
  'nav.tree': 'ツリー',
  'nav.mall': 'モール',
  'nav.memory': 'メモリー',

  /// ===================== HOME SCREEN =====================
  'home.welcome': 'ファミリーツリーへようこそ',
  'home.quick_actions': 'クイックアクション',
  'home.recent_activity': '最近のアクティビティ',
  'home.upcoming_events': '今後のイベント',
  'home.bio' : 'Family Bio',
  'home.secret_santa' : 'Secret Santa',
  'home.kinship_calc' : 'Kinship Calculator',
  'home.identity_Approval' : 'Identity Approval',
  'home.map' : "Migration Map",

  /// ===================== FAMILY MEMBERS =====================
  'family.add_member': 'ファミリーメンバーを追加',
  'family.member_list': 'ファミリーメンバー',
  'family.total_members': 'メンバー総数',
  'family.generations': 'ジェネレーション',
  'family.first_name': 'ファーストネーム',
  'family.last_name': 'ラストネーム',
  'family.date_of_birth': '生年月日',
  'family.place_of_birth': '出生地',
  'family.gender': '性別',
  'family.gender_male': 'オス',
  'family.gender_female': 'メス',
  'family.gender_other': 'その他',
  'family.living_status': '生活状況',
  'family.is_alive': 'この人はまだ生きていますか?',
  'family.alive': '生存',
  'family.deceased': '故人',
  'family.spouse_name': '配偶者の名前',
  'family.anniversary_date': '記念日',
  'family.occupation': '職業',
  'family.current_location': '現在地',
  'family.school_college': '学校と大学',
  'family.qualification': '資格',
  'family.study_location': '学習場所',
  'family.bio': '経歴',
  'family.add_location': '追加',
  'family.relationship': '関係',
  'family.parent': '親',
  'family.child': '子供',
  'family.sibling': '兄弟姉妹',
  'family.spouse': '配偶者',
  'family.edit_member': 'ファミリーメンバーを編集',
  'family.delete_member': 'メンバーを削除',
  'family.confirm_delete': 'このメンバーを削除してもよろしいですか？',

  /// ===================== ADD CHILD SCREEN =====================
  'child.add_child': '子供を追加',
  'child.select_parents': '親を選択',
  'child.birth_details': '出生詳細',

  /// ===================== ADD PARENTS SCREEN =====================
  'parents.add_parents': '親を追加',
  'parents.father': '父親',
  'parents.mother': '母親',

  /// ===================== EVENTS =====================
  'event.title': 'イベント',
  'event.create_event': 'イベントを作成',
  'event.family_events': 'ファミリーイベント',
  'event.event_name': 'イベント名',
  'event.event_date': '日付',
  'event.event_time': '時間',
  'event.event_location': '場所',
  'event.event_description': '説明',
  'event.event_type': 'イベントタイプ',
  'event.birthday': '誕生日',
  'event.anniversary': '記念日',
  'event.wedding': '結婚式',
  'event.reunion': 'ファミリー再会',
  'event.other': 'その他',
  'event.invite_guests': 'ゲストを招待',
  'event.rsvp': 'RSVP',
  'event.yes': 'はい',
  'event.maybe': 'もしかして',
  'event.no': 'いいえ',
  'event.rsvp_status': 'RSVP状態',
  'event.attending': '参加予定',
  'event.not_attending': '参加しない',
  'event.maybe_attending': 'たぶん参加',
  'event.view_details': '詳細を表示',
  'event.edit_event': 'イベントを編集',
  'event.delete_event': 'イベントを削除',

  /// ===================== FEED SCREEN =====================
  'feed.title': 'ファミリーフィード',
  'feed.create_post': '投稿を作成',
  'feed.what_new': '何か新しい？',
  'feed.share_moment': 'ご家族と瞬間を共有',
  'feed.post_content': 'コンテンツを投稿',
  'feed.add_photo': '写真を追加',
  'feed.add_video': 'ビデオを追加',
  'feed.post': '投稿',
  'feed.like': '好き',
  'feed.comment': 'コメント',
  'feed.share': '共有',
  'feed.edit_post': '投稿を編集',
  'feed.delete_post': '投稿を削除',
  'feed.repost_issue': '問題を報告',
  'feed.report_reason': '報告の理由',
  'feed.spam': 'スパム',
  'feed.nudity': 'ヌードまたは性的活動',
  'feed.hate_speech': 'ヘイトスピーチまたはシンボル',
  'feed.false_info': '虚偽の情報',
  'feed.harassment': 'ハラスメントまたはいじめ',
  'feed.something_else': '何か他のもの',
  'feed.additional_details': '追加詳細（オプション）',
  'feed.confirm_report': 'この投稿を報告してもよろしいですか？',

  /// ===================== MEMORY SCREEN =====================
  'memory.title': 'メモリー',
  'memory.add_memory': 'メモリーを追加',
  'memory.upload_memory': 'メモリーをアップロード',
  'memory.memory_name': 'メモリー名',
  'memory.memory_date': '日付',
  'memory.memory_description': '説明',
  'memory.photos': '写真',
  'memory.videos': 'ビデオ',
  'memory.documents': 'ドキュメント',
  'memory.select_tab': 'タブを選択してファイルをアップロード',
  'memory.pick_files': 'ファイルを選択',
  'memory.no_files': 'ファイルが選択されていません',

  /// ===================== PROFILE SCREEN =====================
  'profile.title': 'プロフィール',
  'profile.edit_profile': 'プロフィールを編集',
  'profile.view_profile': 'プロフィールを表示',
  'profile.my_profile': 'マイプロフィール',
  'profile.settings': '設定',
  'profile.change_password': 'パスワードを変更',
  'profile.privacy_settings': 'プライバシー設定',
  'profile.notifications': '通知',
  'profile.help': 'ヘルプとサポート',
  'profile.about': 'について',
  'profile.logout': 'ログアウト',
  'profile.confirm_logout': 'ログアウトしてもよろしいですか？',
  'profile.joined': '参加日',
  'profile.family_role': 'ファミリーロール',
  'profile.stats': '統計情報',

  /// ===================== K-MALL SCREEN =====================
  'mall.title': 'K-モール',
  'mall.coins_balance': 'コイン残高',
  'mall.redeem_coins': 'コインを引き換え',
  'mall.categories': 'カテゴリ',
  'mall.featured': 'フィーチャー',
  'mall.on_sale': 'セール中',
  'mall.my_purchases': 'マイ購入',
  'mall.add_to_cart': 'カートに追加',
  'mall.buy_now': '今すぐ購入',
  'mall.price': '価格',
  'mall.coins': 'コイン',
  'mall.no_items': '利用可能なアイテムなし',

  /// ===================== REDEEM COINS =====================
  'redeem.title': 'コインを引き換え',
  'redeem.available_coins': '利用可能なコイン',
  'redeem.redeem_options': '引き換えオプション',
  'redeem.gift_cards': 'ギフトカード',
  'redeem.cash_back': 'キャッシュバック',
  'redeem.vouchers': 'バウチャー',
  'redeem.discount_codes': 'ディスカウントコード',
  'redeem.enter_amount': '金額を入力',
  'redeem.confirm_redeem': '引き換えを確認',
  'redeem.success': '正常に引き換えられました！',
  'redeem.failed': '交換に失敗しました',

  /// ===================== TREE VIEW =====================
  'tree.title': 'ファミリーツリー',
  'tree.tree_view': 'ウェブファミリーツリーコンテンツ',
  'tree.generation_count': 'ジェネレーション / メンバー',
  'tree.zoom_in': 'ズームイン',
  'tree.zoom_out': 'ズームアウト',
  'tree.reset_zoom': 'ズームをリセット',
  'tree.search_member': 'ファミリーメンバーを検索...',

  /// ===================== SWITCH SPACE =====================
  'space.title': 'スペースを切り替え',
  'space.family_spaces': 'ファミリースペース',
  'space.current_space' : 'Current Space',
  'space.other_space' : 'Other Space',
  'space.confirm' : 'Confirm Switch',
  'space.switched' : 'Space Switched',
  'space.active_space': 'アクティブスペース',
  'space.create_space': '新しいスペースを作成',
  'space.space_name': 'スペース名',
  'space.members': 'メンバー',
  'space.invite_family': 'ファミリーメンバーを招待',

  /// ===================== ROLE SELECTION =====================
  'role.title': 'ロールを選択',
  'role.select_role': '家族でのあなたのロールは何ですか?',
  'role.grandparent': '祖父母',
  'role.parent': '親',
  'role.adult': '成人',
  'role.teenager': 'ティーンエージャー',
  'role.child': '子供',

  /// ===================== VALIDATION & ERRORS =====================
  'error.required_field': 'このフィールドは必須です',
  'error.invalid_email': '有効なメールアドレスを入力してください',
  'error.password_mismatch': 'パスワードが一致しません',
  'error.weak_password': 'パスワードが弱すぎます',
  'error.network_error': 'ネットワークエラー。接続を確認してください。',
  'error.server_error': 'サーバーエラー。後でもう一度お試しください。',
  'error.invalid_input': '入力が無効です',
  'error.file_too_large': 'ファイルが大きすぎます',
  'error.unsupported_format': 'サポートされていないファイル形式',

  /// ===================== SUCCESS MESSAGES =====================
  'success.profile_updated': 'プロフィールが正常に更新されました',
  'success.member_added': 'ファミリーメンバーが正常に追加されました',
  'success.member_updated': 'ファミリーメンバーが正常に更新されました',
  'success.member_deleted': 'ファミリーメンバーが削除されました',
  'success.event_created': 'イベントが正常に作成されました',
  'success.post_created': '投稿が正常に作成されました',
  'success.memory_added': 'メモリーが正常に追加されました',
  'success.saved': '正常に保存されました',
  'success.deleted': '正常に削除されました',

  /// ===================== HINTS & PLACEHOLDERS =====================
  'hint.search': '検索...',
  'hint.enter_name': 'フルネームを入力',
  'hint.enter_email': 'メールアドレスを入力',
  'hint.enter_password': 'パスワードを入力',
  'hint.select_date': 'MM/DD/YYYY',
  'hint.add_location': '場所を追加',
  'hint.write_comment': 'コメントを書く...',
  'hint.write_message': 'メッセージを書く...',

  /// ===================== SCANNER / JOIN SPACE =====================

  'scanner.title': 'Connect With Loved Ones',
  'scanner.subtitle':
  'Enter an invite link or code to join\nyour family\'s space.',

  'scanner.invite_link.label': 'Invite Link',
  'scanner.invite_link.hint': 'https://family.app/join/....',

  'scanner.join_space': 'Join Space',
  'scanner.or': 'OR',

  'scanner.share_qr': 'Share QR Code',

  'scanner.footer':
  'Ask a family admin to show you their QR\ncode from their profile settings.',
  ///=================coins=============================

  'coin.total_balance' : 'TOTAL BALANCE',
  'coin.redeem_coin' : 'Redeem Coins',
};
