// lib/localization/ja_JP.dart
// Japanese translations for Kincore app

const Map<String, String> jaJP = {
  // ===================================
  // Common & General
  // ===================================
  'common.add': '追加',
  'common.save': '保存',
  'common.cancel': 'キャンセル',
  'common.delete': '削除',
  'common.edit': '編集',
  'common.viewAll': 'すべて表示',
  'common.select': '選択',
  'common.search': '検索',
  'common.find': '見つける',
  'common.publish': '公開',
  'common.saveAndAdd': '保存して追加',
  'common.upload': 'アップロード',
  'common.addFile': 'ファイルを追加',
  'common.savePhotos': '写真を保存',
  'common.saveMemory': '思い出を保存',
  'common.loading': '読み込み中...',
  'common.error': '問題が発生しました。もう一度やり直してください。',
  'common.success': '成功',
  'common.productPublished': '製品が正常に公開されました！',
  'common.yes': 'はい',
  'common.no': 'いいえ',
  'common.maybe': 'かもしれません',
  'common.select_country': '国を選択',
  'common.submit': '送信',
  'common.done': '完了',
  'common.next': '次へ',
  'common.continue': '続ける',
  'common.all': 'すべて',
  'common.seeAll': 'すべて見る',
  'common.father': '父',
  'common.mother': '母',
  'common.sister': '姉妹',
  'common.brother': '兄弟',
  'common.approved': '承認済み',

  // ===================================
  // Auth Screen
  // ===================================
  'auth.kincore': 'Kincore',
  'auth.connect': 'あなたのルーツに接続！',
  'auth.welcomeBack': 'おかえりなさい！',
  'auth.detailsPrompt': 'ログインまたはアカウントを作成するには詳細を入力してください。',
  'auth.signUp': 'サインアップ',
  'auth.logIn': 'ログイン',
  'auth.nameLabel': 'あなたの名前を入力してください',
  'auth.nameHint': '名前 姓',
  'auth.emailLabel': 'メールアドレス',
  'auth.emailHint': 'abc@gmail.com',
  'auth.passwordLabel': 'パスワード',
  'auth.passwordHint': '••••••••',
  'auth.confirmPasswordLabel': 'パスワードを確認',
  'auth.forgotPassword': 'パスワードをお忘れですか？',
  'auth.continueWith': 'または次で続行',
  'auth.google': 'Google',
  'auth.facebook': 'Facebook',
  'auth.back': '戻る',
  'auth.firstName': '名',
  'auth.firstNameHint': '太郎',
  'auth.lastName': '姓',
  'auth.lastNameHint': '山田',
  'auth.dob': '生年月日（任意）',
  'auth.dobHint': '年/月/日 (YYYY/MM/DD)',
  'auth.forgotPasswordTitle': 'パスワードを忘れた場合',
  'auth.forgotPasswordHeading': 'パスワードをお忘れですか？',
  'auth.forgotPasswordDesc': 'ご心配なく！よくあることです。アカウントに関連付けられているメールアドレスを入力してください。',
  'auth.enterEmail': 'メールアドレスを入力',
  'auth.sending': '送信中...',
  'auth.sendCode': 'コードを送信',
  'profile.logoutTitle': 'ログアウト',
  'profile.logoutSuccessMsg': '正常にログアウトしました',

  // ===================================
  // Home Screen
  // ===================================
  'home.title': 'ホーム',
  'home.goodMorning': 'おはようございます',
  'home.upcomingBirthdays': 'upcoming誕生日',
  'home.viewCalendar': 'カレンダーを表示',
  'home.timeline': 'タイムライン',
  'home.startBuilding': 'ファミリーツリーの構築を開始',
  'home.startBuildingDesc': 'ファミリーメンバーを追加して、あなたの遺産が成長するのを見てください。',
  'home.addFirstMember': '最初のメンバーを追加',
  'home.recentMemories': '最近の思い出',
  'home.noMemories': '最近の思い出は見つかりませんでした。',
  'home.addFirstMemory': '最初の思い出を追加',
  'home.upcomingEvents': '今後のイベント',
  'home.noEvents': '今後のイベントはありません。',
  'home.familyEvents': 'ファミリーイベント',
  'home.familyBio': 'ファミリーバイオグラフィ',
  'home.secretSanta': 'シークレットサンタ',
  'home.kinshipCalculator': '親族計算機',
  'home.identityApproval': 'アイデンティティ承認',
  'home.migrationMap': '移行マップ',
  'home.quickModules': 'クイックモジュール',
  'home.calculator': '計算機',
  'home.giftSwap': 'ギフト交換',
  'home.savedFeed': '保存されたフィード',
  'home.exploreMore': 'もっと探す',
  'home.marketplace': 'マーケットプレイス',
  'home.reels': 'リール',

  // ===================================
  // Navigation
  // ===================================
  'nav.home': 'ホーム',
  'nav.feed': 'フィード',
  'nav.tree': 'ツリー',
  'nav.mall': 'モール',
  'nav.profile': 'プロフィール',
  'nav.memory': '思い出',
  'nav.family': 'ファミリー',
  'nav.events': 'イベント',

  // ===================================
  // Tree Screen
  // ===================================
  'tree.title': 'ハリソン一族',
  'tree.generations': '@count 世代 / @members メンバー',
  'tree.webContentView': 'Webコンテンツビュー',
  'tree.allView': '全ビュー',
  'tree.directLinage': '直系',
  'tree.birthday': '誕生日',
  'tree.anniversary': '記念日',

  // ===================================
  // Family Bio Screen
  // ===================================
  'familyBio.addTitle': 'ファミリーバイオグラフィを追加',
  'familyBio.addMedia': 'メディアを追加',
  'familyBio.dragAndDrop': 'ドラッグしてドロップするか、アップロードするためにブラウズ',
  'familyBio.basicInfo': '基本情報',
  'familyBio.storyName': 'ストーリーの名前',
  'familyBio.location': 'ロケーション',
  'familyBio.birthDate': '生年月日',
  'familyBio.selectDate': '日付を選択',
  'familyBio.storyBio': 'ストーリー（伝記）',
  'familyBio.addBioHint': 'ここに伝記を追加...',
  'familyBio.publishBio': '伝記を公開',
  'familyBio.title': 'ファミリーバイオグラフィ',
  'familyBio.gallery': 'ギャラリー',
  'familyBio.nextInHistory': '履歴の次',
  'familyBio.existingMember': '既存のファミリーメンバー',
  'familyBio.theRoaringTwenties': 'ロアリング トゥエンティーズ',
  'familyBio.roaringTwentiesDate': '1920 - 1929',
  'familyBio.migrationStoryDate': '1920年11月4日 · シチリアからニューヨークへ',
  'familyBio.migrationStoryContent': '大移動は歴史的な重要な瞬間であり、数百万人が新しい土地への旅に乗り出し、新しい機会と新しい始まりを求めました。その中にはシチリアから1920年にニューヨークに向かった若い女性マリア・ロッシがいました。彼女の物語は多くの人々の物語と同様に、勇気、回復力、そして永遠の人間精神の証です。',
  'familyBio.migrationStoryQuote': '「旅は長く困難でしたが、より良い人生への希望が私たちを前に進ませました。」– マリア・ロッシ',
  'familyBio.errorTitle': 'エラー',
  'familyBio.nameRequired': 'ストーリー名は必須です',
  'familyBio.successTitle': '成功',
  'familyBio.publishedMsg': '伝記が公開されました！',

  // ===================================
  // Market Place
  // ===================================
  'marketplace.title': 'マーケットプレイス',
  'marketplace.searchHint': '製品、カテゴリを検索...',
  'marketplace.bannerTitle': 'サマーセール開催中！',
  'marketplace.bannerSub': 'お近くの最高のお得な情報を見つけましょう。',
  'marketplace.noProducts': '製品が見つかりません！',
  'marketplace.catAll': 'すべて',
  'marketplace.catVehicles': '車両',
  'marketplace.catProperty': '不動産',
  'marketplace.catElectronics': 'エレクトロニクス',
  'marketplace.catFurniture': '家具',
  'marketplace.catFashion': 'ファッション',
  'marketplace.msgAvailable': 'こんにちは、まだありますか？',
  'marketplace.timeJustNow': 'たった今',
  'marketplace.timeYesterday': '昨日',
  'marketplace.messages': 'メッセージ',
  'marketplace.noMessages': 'まだメッセージはありません。',

  // ===================================
  // Add Family Member
  // ===================================
  'addMember.title': 'ファミリーメンバーを追加',
  'addMember.basicInfo': '基本情報',
  'addMember.firstName': '名前',
  'addMember.lastName': '姓',
  'addMember.gender': '性別',
  'addMember.male': '男性',
  'addMember.female': '女性',
  'addMember.other': 'その他',
  'addMember.dateOfBirth': '生年月日',
  'addMember.dateFormatHint': 'MM/DD/YYYY',
  'addMember.relationshipSetup': '関係設定',
  'addMember.relationshipType': '関係タイプ',
  'addMember.relationship.spouse': '配偶者',
  'addMember.relationship.sibling': '兄弟姉妹',
  'addMember.relationship.parent': '親',
  'addMember.findFamilyMember': 'ファミリーメンバーを見つける',
  'addMember.spouseName': '配偶者の名前',
  'addMember.anniversaryDate': '記念日',
  'addMember.additionalDetail': '追加の詳細',
  'addMember.addLocation': 'ロケーションを追加',
  'addMember.occupation': '職業',
  'addMember.bioNotes': '伝記/注記',
  'addMember.privacyVisibility': 'プライバシーと可視性',
  'addMember.visibleToAll': 'すべてのメンバーに表示',
  'addMember.addParentsTitle': '親を追加',
  'addMember.addOtherMember': 'ファミリーの別のメンバーを追加',
  'addMember.placeOfBirth': '出生地',
  'addMember.currentLocation': '現在地',
  'addMember.addChildTitle': 'お子さんを追加',
  'addMember.schoolAndCollege': '学校と大学',
  'addMember.qualification': '資格',
  'addMember.studyLocation': '勉強の場所',
  'addMember.changePhoto': '写真を変更',
  'addMember.livingStatus': '生活状況',
  'addMember.isAlive': 'その人はまだ生きていますか？',
  'addMember.alive': '生きている',
  'addMember.deceased': '故人',
  'addMember.phoneNumber': '電話番号',
  'addMember.phoneHint': '00000 00000',

  // ===================================
  // Memory Screen
  // ===================================
  'memory.title': '思い出',
  'memory.addTitle': '思い出を追加',
  'memory.tabAll': 'すべて',
  'memory.tabPhotos': '写真',
  'memory.tabVideos': 'ビデオ',
  'memory.addMemoryPhotos': '思い出の写真を追加',
  'memory.addMemoryVideos': '思い出のビデオを追加',
  'memory.uploadSupport': 'PNG、JPGファイルサポート',

  // ===================================
  // K-Mall & Products
  // ===================================
  'mall.title': 'モール',
  'mall.searchHint': '製品を検索',
  'mall.filter': 'フィルター',
  'mall.categories': 'カテゴリ',
  'mall.featured': '特集',
  'mall.mostPopular': '最も人気',
  'mall.onSale': 'セール中',
  'mall.wishlistTitle': 'My wishlist',
  'mall.noItemsWishlist': 'あなたのウィッシュリストは空です！',
  'mall.exploreProducts': '製品を探索',
  'mall.productDetails': '製品の詳細',
  'mall.description': '説明',
  'mall.selectSize': 'サイズを選択',
  'mall.selectColor': '色を選択',
  'mall.quantity': '数量',
  'mall.addToCart': 'カートに追加',
  'mall.buyNow': '今すぐ購入',
  'mall.reviews': 'レビュー',
  'mall.noReviews': 'この製品のレビューはまだありません。',
  'mall.sellerInfo': 'セラー情報',
  'mall.viewShop': 'ショップを表示',
  'mall.relatedProducts': '関連製品',
  'mall.addedToCart': '@productNameがカートに追加されました',
  'mall.filterPrice': '価格帯',
  'mall.filterColor': '色',
  'mall.filterGender': 'ジェンダー',
  'mall.category.fashion': 'ファッション',
  'mall.category.electronics': '電子機器',
  'mall.category.appliances': '家電',
  'mall.category.beauty': 'ビューティー',
  'mall.category.furniture': '家具',
  'mall.banner.title': '新しいコレクション',
  'mall.banner.discount': '50％割引',
  'mall.banner.for': 'キッズ用',
  'mall.productReview': '@rating（@count レビュー）',
  'mall.tag.homeMade': 'ホームメイド',
  'mall.tag.newCollection': '新しいコレクション',

  // ===================================
  // Add Product
  // ===================================
  'addProduct.title': '新しい製品を追加',
  'addProduct.detailsPrompt': '製品をリストするためにすべての詳細を入力',
  'addProduct.uploadImagesTitle': '製品画像をアップロード',
  'addProduct.uploadImagesDesc': '鮮明な高解像度画像を使用してください。最初の画像が表紙になります。',
  'addProduct.addMedia': 'メディアを追加',
  'addProduct.dragAndDrop': 'ドラッグしてドロップするか、アップロードするためにブラウズ',
  'addProduct.basicInfo': '基本情報',
  'addProduct.productNameLabel': '製品名（必須）',
  'addProduct.priceLabel': '価格',
  'addProduct.discountLabel': '割引％',
  'addProduct.descriptionLabel': '説明',
  'addProduct.sizeLabel': 'サイズ',
  'addProduct.conditionsLabel': '条件',
  'addProduct.brandNameLabel': 'ブランド名',
  'addProduct.profileLabel': 'プロフィールを選択',
  'addProduct.categoryLabel': 'カテゴリ',
  'addProduct.subCategoryLabel': 'サブカテゴリ',
  'addProduct.quantityLabel': '数量',
  'addProduct.publishButton': '製品を公開',

  // ===================================
  // Redeem Coin Screen
  // ===================================
  'redeem.title': 'KCCコインを交換',
  'redeem.totalBalance': '総残高',
  'redeem.kccBalance': 'KCC残高',
  'redeem.currency': 'KCC',
  'redeem.waysToRedeem': '交換する方法',
  'redeem.waysToEarn': '稼ぐ方法',
  'redeem.recentActivity': '最近のアクティビティ',
  'redeem.vintageCase': 'ビンテージケース',
  'redeem.kmallPurchase': 'モールでの購入',
  'redeem.redeemedKcc': '-455 KCC',
  'redeem.shopAndSave': '買い物して節約',
  'redeem.redeemForCash': '現金と交換',
  'redeem.shopNow': '今すぐ買い物',
  'redeem.redeemNow': '今すぐ交換',
  'redeem.option.shop.title': 'モールで買い物',
  'redeem.option.shop.description': 'コインを使ってファミリーヘリテージの独占製品を購入します。',
  'redeem.option.shop.button': 'モールを探索',
  'redeem.option.support.title': 'ファミリーをサポート',
  'redeem.option.support.description': 'コインを転送して親戚をサポートします。',
  'redeem.option.support.button': 'ギフトを送信',
  'redeem.option.boost.title': 'リストをブースト',
  'redeem.option.boost.description': '製品をプロモートして販売を促進します。',
  'redeem.option.boost.button': '今すぐプロモート',
  'redeem.featuredRewards': '注目の特典',
  'redeem.completeProfile': 'プロフィールを完成させる',
  'redeem.earnKcc': '@points KCCを獲得',

  // ===================================
  // Coin Card Level
  // ===================================
  'profile.levelBadge': 'レベル @level @title',

  // ===================================
  // Earn
  // ===================================
  'earn.referral': '友人を紹介',
  'earn.referralSub': '20 KCCを稼ぐ',
  'earn.completeProfile.title': 'プロフィールを完成させる',
  'earn.completeProfile.subtitle': '60KCCを稼ぐ',
  'earn.addPhoto.title': 'ファミリー写真を追加',
  'earn.addPhoto.subtitle': '20KCCを稼ぐ',
  'earn.inviteMember.title': 'ファミリーメンバーを招待',
  'earn.inviteMember.subtitle': '20KCCを稼ぐ',
  'earn.attendEvent.title': 'ファミリーイベントに参加',
  'earn.attendEvent.subtitle': '45KCCを稼ぐ',

  // ===================================
  // Create Event Screen
  // ===================================
  'createEvent.title': 'イベントを作成',
  'createEvent.saveDraft': '保存',
  'createEvent.addCoverPhoto': 'カバー写真を追加',
  'createEvent.uploadSupport': 'PNG、JPGファイルサポート',
  'createEvent.detailTitle': 'イベントの詳細',
  'createEvent.eventTitleLabel': 'イベントタイトル',
  'createEvent.eventTitleHint': 'タイトルを入力',
  'createEvent.locationLabel': 'ロケーション',
  'createEvent.locationHint': 'ロケーションアドレスを入力',
  'createEvent.descriptionLabel': '説明',
  'createEvent.descriptionHint': 'ここに書く...',
  'createEvent.startDateLabel': '開始日',
  'createEvent.endDateLabel': '終了日',
  'createEvent.timeLabel': '時間',
  'createEvent.timeHint': '時間を入力',
  'createEvent.inviteMemberTitle': 'ファミリーメンバーを招待',
  'createEvent.starts': '開始',
  'createEvent.ends': '終了',
  'createEvent.requestRSVP': 'RSVPをリクエスト',
  'createEvent.requestRSVPSub': 'ゲストは出席を確認する必要があります',
  'createEvent.sendReminders': 'リマインダーを送信',
  'createEvent.sendRemindersSub': '1日前にゲストに通知する',
  'createEvent.includeGiftExchange': 'ギフト交換を含める',
  'createEvent.includeGiftExchangeSub': '例：シークレットサンタやギフト交換',
  'createEvent.nextAddGift': '次へ＆ギフトを追加',
  'createEvent.createEventBtn': 'イベントを作成',
  'createEvent.eventCreatedTitle': 'イベント作成完了',
  'createEvent.eventCreatedMsg': 'イベントが正常に作成されました！',

  // ===================================
  // Feed & Posts
  // ===================================
  'feed.title': 'ファミリーフィード',
  'feed.myStory': 'マイストーリー',
  'feed.whatsHappening': '何が起こってるの？',
  'feed.createPost': '投稿を作成',
  'feed.archive': 'アーカイブ',
  'feed.writeCommentHint': 'コメントを書く...',
  'feed.viewComments': '@countコメントを表示',
  'feed.postAnonymously': 'ログインなしで投稿',
  'feed.allowComments': 'コメントを許可',
  'feed.saveToDevice': 'デバイスに保存',
  'feed.reportPost': '投稿を報告',
  'feed.archiveMenu': 'アーカイブ',
  'feed.reportMenu': '報告する',
  'feed.archiveMsg': '投稿がアーカイブに追加されました。',
  'feed.savedTitle': '保存済み',
  'feed.savedMsg': '投稿がコレクションに保存されました。',
  'feed.removedTitle': '削除済み',
  'feed.removedMsg': '投稿が保存から削除されました。',
  'feed.caughtUp': 'すべての投稿を見ました！',
  'feed.findMore': 'もっと家族を探す',
  'feed.writeComment': 'コメントを書く...',
  'createPost.successTitle': '成功',
  'createPost.successMsg': '投稿が正常に作成されました！',
  'createPost.errorTitle': 'エラー',
  'createPost.errorMsg': 'テキストを入力するか、メディアを追加してください。',
  'feed.savedCollection': '保存済みコレクション',
  'feed.noSavedPosts': '保存された投稿はまだありません',
  'feed.removeFromCollection': 'コレクションから削除',

  // ===================================
  // Post Settings
  // ===================================
  'postSettings.title': '投稿設定',
  'postSettings.postSettings': '投稿設定',
  'postSettings.whoCanSee': '誰があなたの投稿を見ることができますか？',
  'postSettings.visibility.public': '公衆',
  'postSettings.visibility.friends': '友達',
  'postSettings.visibility.friendsExcept': 'Except Friends',
  'postSettings.visibility.specificFriends': '特定の友達',
  'postSettings.whoCanComment': '誰がこの投稿にコメントできますか？',
  'postSettings.comments.followersOnly': 'あなたのフォロワーのみ',
  'postSettings.comments.friends': '友達',
  'postSettings.comments.chosenFriends': '選んだ友達',
  'postSettings.saveChanges': '変更を保存',

  // ===================================
  // Create Post
  // ===================================
  'createPost.title': '投稿を作成',
  'createPost.hint': '何を考えていますか？',
  'createPost.addMedia': 'メディアを追加',
  'createPost.tagPeople': 'タグ人物',
  'createPost.postButton': '投稿',

  // ===================================
  // Report
  // ===================================
  'report.title': '問題を報告',
  'report.anonymousHelp': 'あなたの報告は匿名です。何が起こっているかを私たちに知らせることで、ファミリーツリーコミュニティを安全に保つのに役立ってください。',
  'report.reasonTitle': '報告の理由',
  'report.spam': 'スパムです',
  'report.nudity': 'ヌーディティまたは性的活動',
  'report.hateSpeech': 'ヘイトスピーチまたはシンボル',
  'report.falseInfo': '虚偽情報',
  'report.harassment': 'ハラスメントまたはいじめ',
  'report.other': '他に何か',
  'report.additionalDetails': '追加詳細（オプション）',
  'report.describeIssue': '問題を説明して、私たちのレビューを支援してください',
  'report.submitReport': 'レポートを送信',
  'report.dialog.discardTitle': 'レポートを破棄しますか？',
  'report.dialog.discardBody': 'このレポートをキャンセルしてもよろしいですか？あなたの進捗は失われます。',
  'report.dialog.stay': 'いいえ、滞在',
  'report.dialog.discard': 'はい、破棄',

  // ===================================
  // Seller Dashboard
  // ===================================
  'seller.title': 'ダッシュボード',
  'seller.overview': '概要',
  'seller.totalRevenue': '総収益',
  'seller.orders': '注文',
  'seller.avgOrderValue': '平均注文値',
  'seller.products': '製品',
  'seller.topProducts': 'トップ製品',
  'seller.recentOrders': '最近の注文',
  'seller.orderId': '注文',
  'seller.noProducts': '表示する製品がありません。',
  'seller.noOrders': '最近の注文はありません。',
  'seller.noData': 'データ利用不可',

  // ===================================
  // Profile & Settings
  // ===================================
  'profile.title': '私のプロフィール',
  'profile.followers': 'フォロワー',
  'profile.following': 'フォロー中',
  'profile.editProfile': 'プロフィールを編集',
  'profile.addMember': 'メンバーを追加',
  'profile.addMemory': '思い出を追加',
  'profile.vitalStats': '重要な統計',
  'profile.stat.fullName': 'フルネーム',
  'profile.stat.born': '生まれた',
  'profile.stat.location': 'ロケーション',
  'profile.stat.occupation': '職業',
  'profile.familyMember': 'ファミリーメンバー',
  'profile.keyLifeEvents': '人生の主な出来事',
  'profile.viewMoreTimeline': 'タイムラインをもっと見る',
  'profile.memories': '思い出',
  'profile.shareProfile': 'プロフィールを共有',
  'profile.personal': '個人',
  'profile.business': 'ビジネス',
  'profile.posts': '投稿',
  'profile.photos': '写真',
  'profile.videos': 'ビデオ',
  'profile.tagged': 'タグ付き',
  'profile.myProfile': 'マイプロフィール',
  'profile.sellerDashboard': 'セラーダッシュボード',
  'profile.identityApproval': 'アイデンティティ承認',
  'profile.redeemCoins': 'コインを交換',
  'profile.settings': 'settings',
  'profile.logout': 'ログアウト',
  'profile.logoutConfirm': 'ログアウトしてもよろしいですか？',
  'profile.personalProfile': '個人プロフィール',
  'profile.roleAccess': 'あなたの役割と権限',
  'profile.viewDashboard': '私のセラーダッシュボードを表示',
  'profile.addProduct': '製品を追加',
  'profile.account': 'アカウント',
  'profile.personalInfo': '個人情報',
  'profile.personalInfoSub': '名前、メール、電話番号',
  'profile.privacy': 'プライバシーとセキュリティ',
  'profile.privacySub': 'ファミリーツリーの可視性、パスワード',
  'profile.notifications': '通知',
  'profile.notificationsSub': 'イベント、更新、メッセージ',
  'profile.darkMode': 'ダークモード',
  'profile.darkModeSub': 'アプリのテーマを切り替える',
  'profile.myOrders': 'マイ注文',
  'profile.myOrdersSub': '注文履歴、返品',
  'profile.myListings': 'マイリスティング',
  'profile.myListingsSub': '販売管理',
  'profile.privacyLocked': 'プライバシー：ロック済み',
  'profile.privacyUnlocked': 'プライバシー：ロック解除',
  'profile.message': 'メッセージ',
  'profile.viewFeed': 'フィードを見る',
  'profile.viewStory': 'ストーリーを見る',
  'profile.viewProfilePic': 'プロフィール画像を見る',
  'profile.viewUserFeed': 'ユーザーのフィードを見る',
  'profile.privacyLockedTitle': 'プライバシーロック 🔒',
  'profile.privacyUnlockedTitle': 'プライバシーロック解除 🔓',
  'profile.privacyLockedMsg': 'プロフィールは現在非公開です。',
  'profile.privacyUnlockedMsg': 'プロフィールは現在他の人に公開されています。',
  'profile.requestHistory': 'リクエスト履歴',
  'profile.requestHistorySub': 'リクエスト履歴を確認する',
  'profile.saveFeed': '保存されたフィード',
  'profile.saveFeedSub': '保存されたフィードコレクション',
  'profile.giftSwap': 'ギフト交換',
  'profile.giftSwapSub': 'あなたのギフト交換',
  'profile.displayMode': '表示モード',
  'profile.displayModeSub': '外観を調整 (明/暗)',
  'giftSwap.setRestrictions': '抽選の制限を設定する',
  'giftSwap.setRestrictionsSub': '特定のメンバーがお互いを引かないようにする',
  'giftSwap.restrictionsTitle': '制限',
  'giftSwap.restrictionsMsg': 'ここで管理者はAがBを引けないなどのルールを設定できます。',
  'giftSwap.successTitle': '成功',
  'giftSwap.createdMsg': 'ギフト交換イベントが正常に作成されました！',
  'profile.display': 'ディスプレイ',
  'profile.chooseAppearance': '外観を選択',
  'profile.lightMode': 'ライトモード',
  'profile.systemPref': 'システム設定',
  'profile.systemPrefSub': 'デバイスの設定に合わせる',

  // ===================================
  // Edit Profile
  // ===================================
  'editProfile.title': 'プロフィールを編集',
  'editProfile.changePhoto': '写真を変更',
  'editProfile.firstNameLabel': '名前',
  'editProfile.firstNameHint': '名前を入力',
  'editProfile.lastNameLabel': '姓',
  'editProfile.lastNameHint': '姓を入力',
  'editProfile.endDateLabel': '終了日',
  'editProfile.locationLabel': 'ロケーション',
  'editProfile.locationHint': 'ロケーションアドレスを入力',
  'editProfile.occupationLabel': '職業',
  'editProfile.occupationHint': '職業を入力',
  'editProfile.designationLabel': '指定',
  'editProfile.designationHint': '説明を入力',
  'editProfile.companyNameLabel': '会社名',
  'editProfile.companyNameHint': '会社名を入力',
  'editProfile.websiteLabel': 'ウェブサイト',
  'editProfile.websiteHint': 'あなたのウェブサイトを貼り付ける',
  'editProfile.linkedInLabel': 'LinkedIn',
  'editProfile.linkedInHint': 'LinkedInリンクを貼り付ける',
  'editProfile.instagramLabel': 'Instagram',
  'editProfile.instagramHint': 'Instagramリンクを貼り付ける',
  'editProfile.facebookLabel': 'Facebook',
  'editProfile.facebookHint': 'Facebookリンクを貼り付ける',
  'editProfile.otherLinkLabel': 'その他のリンク',
  'editProfile.otherLinkHint': '別のリンクを貼り付ける',
  'editProfile.addOtherLink': 'その他のリンクを追加',
  'editProfile.claimIdentity': 'アイデンティティを請求',

  // ===================================
  // Events
  // ===================================
  'event.status.attended': '出席',
  'event.status.notAttended': '参加していない',
  'event.status.joinnow': '今すぐ参加',
  'event.detailTitle': 'イベントの詳細',
  'event.hostedBy': 'ホストが',
  'event.areYouGoing': 'あなたは行く？',
  'event.responseRequired': '応答が必要',
  'event.going': '行く',

  // ===================================
  // Family Events
  // ===================================
  'familyEvents.title': 'ファミリーイベント',
  'familyEvents.findHint': 'イベントを見つける',
  'familyEvents.tabUpcoming': 'upcoming',
  'familyEvents.tabPast': '過去',

  // ===================================
  // Member List
  // ===================================
  'memberList.title': 'すべてのファミリーメンバー',
  'memberList.tabFamilies': 'ファミリー',
  'memberList.tabPeople': 'ピープル',
  'memberList.noMembers': 'メンバーが見つかりません',
  'memberList.present': 'プレゼント',
  'memberList.location': 'カリフォルニア、USA',

  // ===================================
  // Find Yourself
  // ===================================
  'findYourself.title': '自分自身を見つける',
  'findYourself.searchHint': '名前/誕生日で検索',
  'findYourself.bestMatches': 'ベストマッチ',
  'findYourself.foundCount': '@count 見つかった',
  'findYourself.notListed': 'リストされていませんか？プロフィールを作成してください',
  'findYourself.thisIsMe': 'これは私です',
  'findYourself.subtitle': '名前を検索して、アカウントを\n既存の家系図レコードにリンクします。',
  'findYourself.possibleMatches': '可能性のある一致',
  'findYourself.selectionReqTitle': '選択が必要です',
  'findYourself.selectionReqMsg': '最初にプロフィールを選択してください。',
  'findYourself.firstName': '名',
  'findYourself.lastName': '姓',
  'findYourself.gender': '性別',
  'findYourself.selectGender': '性別を選択',
  'findYourself.dob': '生年月日',
  'findYourself.yearOnly': '年のみ一致',
  'findYourself.searchBtn': '検索',
  'findYourself.clearBtn': 'クリア',
  'findYourself.initialMsg': '少なくとも1つのフィールドを入力して検索をタップしてください。',
  'findYourself.noResults': '結果が見つかりません',
  'findYourself.noResultsSub': '検索語句を調整するか、フィルターをクリアしてみてください。',
  'findYourself.resultsCount': '@count 件の結果が見つかりました',
  'findYourself.validationMsg': '検索するには少なくとも1つのフィールドを入力してください。',
  'findYourself.male': '男性',
  'findYourself.female': '女性',
  'findYourself.other': 'その他',
  'findYourself.firstNameHint': '名を入力',
  'findYourself.lastNameHint': '姓を入力',
  'findYourself.dobHint': '日付を選択',

  // ===================================
  // Find Member
  // ===================================
  'findMember.title': 'ファミリーメンバーを見つける',
  'findMember.searchHint': 'ファミリーメンバーを見つける',
  'findMember.lastViewed': '最後に表示された',

  // ===================================
  // Role & Access
  // ===================================
  'role.title': '役割とアクセス',
  'role.currentRole': '現在の役割：@role',
  'role.familySpace': 'スミスファミリースペース',
  'role.adminAccessTitle': '管理者アクセス',
  'role.adminAccessDesc': '管理者はファミリースペースを完全にコントロールできます。メンバーを管理し、設定を構成できます。',
  'role.permission.editTree': 'ファミリーツリーの編集',
  'role.permission.editTreeSub': 'プロフィールを追加編集または削除',
  'role.permission.memberMgmt': 'メンバー管理',
  'role.permission.memberMgmtSub': '新しいユーザーを招待して役割を割り当てる',
  'role.permission.spaceSettings': 'スペース設定',
  'role.permission.spaceSettingsSub': 'プライバシーと通知を変更',
  'role.permission.contentModeration': 'コンテンツモデレーション',
  'role.permission.contentModerationSub': 'アルバムと削除された投稿を管理',
  'role.warning': 'ファミリー作成者のみが所有権を転送するか、ファミリースペース全体を削除できます。',
  'role.changePermission': 'あなたの許可を変更する必要がありますか？',
  'role.contactCreator': 'ファミリー作成者に連絡',
  'role.saveAndCreate': '保存して作成',
  'role.limitedAccess': '制限付きアクセス',
  'role.limitedAccessDesc': '機密情報を見たり、ツリーを編集したりすることはできません。',
  'role.fullAccess': 'フルアクセス',
  'role.fullAccessDesc': 'すべての情報を表示したり、ファミリーツリーを編集したりできます。',
  'role.admin': '管理人',
  'role.member': 'メンバー',
  'role.guest': 'ゲスト',

  // ===================================
  // Family Space
  // ===================================
  'chooseSpace.welcome': 'Kincoreへようこそ！',
  'chooseSpace.subtitle': '家族の旅をどのように始めますか？以下のオプションを選択してください。',
  'chooseSpace.createTitle': '新しい家族スペースを作成',
  'chooseSpace.createSubtitle': '家族が繋がり、共有し、成長するための新しいスペースを設定します。',
  'chooseSpace.joinTitle': '既存のスペースに参加',
  'chooseSpace.joinSubtitle': '招待コードやリンクをお持ちですか？ここから家族メンバーに参加しましょう。',
  'chooseSpace.joinSnackbarTitle': 'スペースに参加',
  'chooseSpace.joinSnackbarMsg': 'スペース参加画面に移動中...',
  'createSpace.appBarTitle': '家族スペースを作成',
  'createSpace.welcome': 'Kincoreへようこそ！',
  'createSpace.subtitle': '家族メンバーと繋がり、共有し、成長するための専用スペースを設定します。',
  'createSpace.uploadPhoto': 'スペースの写真をアップロード',
  'createSpace.nameLabel': '家族スペース名',
  'createSpace.nameHint': '例：アンダーソン家',
  'createSpace.descLabel': '説明（任意）',
  'createSpace.descHint': '家族の短い紹介文を書いてください...',
  'createSpace.createBtn': 'スペースを作成',
  'createSpace.selectImageTitle': '画像を選択',
  'createSpace.selectImageMsg': '画像ピッカーがここに開きます。',
  'createSpace.validationErrorTitle': '検証エラー',
  'createSpace.validationErrorMsg': '家族スペース名を入力してください。',
  'createSpace.successTitle': '成功',
  'createSpace.successMsg': '家族スペース「@name」が正常に作成されました！',
  'chooseSpace.joinOptionsTitle': 'スペースに参加する',
  'chooseSpace.scanQr': 'QRコードをスキャン',
  'chooseSpace.scanQrSub': '家族のQRを使用してすぐに参加',
  'chooseSpace.joinUrl': 'URL経由で参加',
  'chooseSpace.joinUrlSub': '招待リンクを貼り付け',
  'chooseSpace.findYourself': '自分を見つける',
  'chooseSpace.findYourselfSub': '家系図で自分のプロフィールを検索',
  'joinOptions.title': 'スペースに参加する',
  'joinOptions.scanTitle': 'QRコードをスキャン',
  'joinOptions.scanSub': 'カメラまたはギャラリーから家族のQRをスキャン',
  'joinOptions.urlTitle': 'URL経由で参加',
  'joinOptions.urlSub': 'ここに招待リンクを貼り付けます',
  'joinOptions.findTitle': '自分を見つける',
  'joinOptions.findSub': '名前を検索してIDを要求する',
  'urlJoin.title': 'リンク経由で参加',
  'urlJoin.subtitle': '下に家族スペースの招待リンクを貼り付けてください。',
  'urlJoin.hint': 'ここにURLを貼り付けます...',
  'urlJoin.submit': 'スペースに参加',
  'scanner.title': 'QRコードをスキャン',
  'scanner.subtitle': 'フレーム内に家族のQRコードを合わせます',
  'scanner.galleryBtn': 'ギャラリーからアップロード',

  // ===================================
  // Role Access
  // ===================================
  'roleAccess.title': '役割とアクセス',
  'roleAccess.manager': 'マネージャー',
  'roleAccess.permissions': 'アクセス許可',
  'roleAccess.viewTree': 'ファミリーツリーを表示',
  'roleAccess.editTree': 'ファミリーツリーを編集',
  'roleAccess.addMembers': 'ファミリーメンバーを追加',
  'roleAccess.deleteMembers': 'ファミリーメンバーを削除',
  'roleAccess.manageRoles': '役割とアクセス許可を管理',
  'roleAccess.postFeed': 'ファミリーフィードに投稿',
  'roleAccess.viewMemories': '思い出を表示',
  'roleAccess.createEvents': 'イベントを作成',

  // ===================================
  // Role Selection
  // ===================================
  'roleSelection.title': 'あなたの役割を選択',
  'roleSelection.grandparent': 'おじいちゃん、おばあちゃん',
  'roleSelection.parent': '親',
  'roleSelection.adult': '大人',
  'roleSelection.teenager': 'ティーンエイジャー',
  'roleSelection.child': '子供',

  // ===================================
  // Identity Approval
  // ===================================
  'identity.title': 'アイデンティティ承認',
  'identity.pendingRequests': 'ペンディングリクエスト',
  'identity.noRequests': 'ペンディングリクエストはありません',
  'identity.claiming': 'アイデンティティを請求',
  'identity.proof.photo': '写真証拠',
  'identity.proof.birth': '出生証明書',
  'identity.reject': '拒否',
  'identity.requestFrom': 'からのリクエスト',
  'identity.approve': '承認',
  'identity.decline': '下す',
  'identity.statusTitle': 'アイデンティティステータス',
  'identity.claimPending': 'クレーム保留中',
  'identity.status.pending': '保留中',
  'identity.status.description': 'ジョセフ祖先の請求を受け取りました。これは通常24〜48時間かかります。',
  'identity.submittedOn': 'で提出',
  'identity.relationship': 'リレーション',
  'identity.relationshipValue': 'グランダ',
  'identity.verificationProgress': '検証の進行状況',
  'identity.progress.submitted': 'リクエスト送信',
  'identity.progress.submittedSub': 'あなたの書類が受け取られました',
  'identity.progress.inProgress': '検証進行中',
  'identity.progress.inProgressSub': '私たちのチームがあなたのIDと関係の証拠を確認しています。',
  'identity.progress.decision': '最終決定',
  'identity.progress.decisionSub': '承認または詳細情報の要求。',
  'identity.addProof': '追加の証拠をアップロード',
  'identity.addProofPhoto': '追加の証拠写真を追加',
  'identity.backToProfile': 'プロフィールに戻る',
  'requestHistory.requestApproved': 'リクエスト承認済み',
  'requestHistory.dataChange': 'データ変更',
  'requestHistory.requestSubmitted': 'リクエスト送信済み',
  'requestHistory.adminComment': '「メールで提供された出生証明書で確認済み。」',
  'requestHistory.reviewedBy': '@admin (管理者) によって確認されました',
  'requestHistory.changeTo': ' から次へ変更 ',
  'requestHistory.dummyApprovedTime': '2025年10月22日/午前10時30分',
  'requestHistory.dummySubmittedTime': '2023年10月20日 / あなた',

  // ===================================
  // Space Management
  // ===================================
  'space.switch': 'スペースを切り替える',
  'space.current': '現在のスペース',
  'space.other': 'その他のスペース',
  'space.confirmSwitch': 'スイッチを確認',
  'space.switchedTo': 'これで@spaceNameにいます',
  'space.online': 'オンライン',
  'space.members': '@count メンバー',
  'space.active': 'アクティブ',

  // ===================================
  // Generation Screen
  // ===================================
  'generation.title': '世代',
  'generation.noData': 'データが見つかりません',
  'generation.genSuffix': '@level 世代',
  'generation.members': 'メンバー',
  'generation.generation': '世代',
  'generation.years': '年',

  // ===================================
  // Gift & Draw Screens
  // ===================================
  'gift.letsDraw': 'くじを引きましょう！',
  'gift.surpriseBegin': 'サプライズをお始めください！',
  'gift.spinning': '回転...',
  'gift.spinWheel': 'ホイールを回転',
  'gift.exchangeDetails': 'ギフト交換の詳細',
  'gift.senderName': 'ギフト送信者の名前',
  'gift.receiverName': 'ギフト受信者の名前',
  'gift.exchangeName': 'ギフト交換に名前を付ける',
  'gift.selectDate': '日付を選択',
  'gift.budget': 'ギフト予算',
  'gift.addNote': 'メモを追加',
  'gift.addGiftPhoto': 'ギフト写真を追加',
  'gift.uploadSupport': 'PNG、JPGファイルサポート',
  'gift.sendGift': 'ギフトを送信',
  'gift.addGiftExchange': 'ギフト交換を追加',
  'gift.eventDetails': 'イベントの詳細',
  'gift.eventName': 'イベント名',
  'gift.festivalType': 'フェスティバルタイプ',
  'gift.description': '説明',
  'gift.scope': 'スコープ',
  'gift.deadlines': '期限',
  'gift.signupDeadline': 'サインアップ期限',
  'gift.drawDeadline': '引き分け期限',
  'gift.giftDeadline': 'ギフト期限',
  'gift.budgetPreference': '予算と好み',
  'gift.budgetRange': '予算範囲：₹@value',
  'gift.preferredGiftType': '好みのギフトタイプ',
  'gift.anonymity': '匿名性',
  'gift.anonymitySub': '参加者を秘密に保つ',
  'gift.createExchange': 'ギフト交換を作成',
  'gift.swapTitle': 'ギフトスワップ',
  'gift.yourName': 'あなたの名前',
  'gift.addFriendName': '友人の名前を追加',
  'gift.friendName': '友人の名前',
  'gift.addMore': '+ もっと追加',
  'gift.draw': '描く',
  'giftSwap.eventDashboard': 'イベントダッシュボード',
  'giftSwap.budgetDate': '予算: @amount • @date',
  'giftSwap.drawResults': '抽選結果',
  'giftSwap.reshuffle': '再シャッフル',
  'giftSwap.reshuffleMsg': '制限に基づいてペアを再抽選しています...',
  'giftSwap.adminViewOnly': '誰が誰を引いたかは、あなた(管理者)だけが見ることができます。',
  'giftSwap.backToHome': 'ホーム画面に戻る',
  'gift.selectParticipant': '選択',
  'gift.selectParticipantsTitle': '参加者を選択',
  'gift.done': '完了',

  // ===================================
  // Checkout & Order History
  // ===================================
  'checkout.title': 'チェックアウト',
  'checkout.selectedProduct': '選択された製品',
  'checkout.shippingAddress': '配送先住所',
  'checkout.addressName': '家',
  'checkout.addressDetail': '郵便局の近く、velnath chowk、Junagadh',
  'checkout.paymentMethod': '支払い方法',
  'checkout.payment.card': 'クレジット/デビットカード',
  'checkout.payment.upi': 'UPI',
  'checkout.payment.netbanking': 'ネットバンキング',
  'checkout.applyRewards': 'リワードを適用',
  'checkout.applyKcc': 'KCCコインを適用',
  'checkout.apply': '申し込む',
  'checkout.youHaveKcc': 'あなたは{count} KCCコインを持っています',
  'checkout.billDetails': '請求の詳細',
  'checkout.subtotal': '小計',
  'checkout.shippingFee': '配送料金',
  'checkout.tax': '税金（{percent}％）',
  'checkout.totalAmount': '合計金額',
  'checkout.total': '合計',
  'checkout.placeOrder': '注文を配置',
  'checkout.proceedingSnackbar': '支払いにリダイレクト中...',
  'checkout.emptyCartSnackbar': '最初にいくつかのアイテムを追加してください！',
  'trackOrder.title': '注文を追跡',
  'trackOrder.orderId': '注文ID',
  'trackOrder.expectedDelivery': '配達予定',
  'trackOrder.trackingHistory': '追跡履歴',
  'trackOrder.stepPlaced': '注文完了',
  'trackOrder.stepPayment': '支払い確認済み',
  'trackOrder.stepShipped': '発送済み',
  'trackOrder.stepOutForDelivery': '配達中',
  'trackOrder.stepDelivered': '配達済み',
  'trackOrder.expectedToday': '本日予定',
  'trackOrder.pending': '保留中',

  // ===================================
  // Invoice Screen
  // ===================================
  'invoice.title': '請求書',
  'invoice.downloadingTitle': 'ダウンロード',
  'invoice.downloadingMsg': '請求書のPDFをダウンロードしています...',
  'invoice.taxInvoice': '納税記録 / 供給請求書',
  'invoice.orderId': '注文ID',
  'invoice.orderDate': '注文日',
  'invoice.paymentMode': '支払い方法',
  'invoice.status': 'ステータス',
  'invoice.paid': '支払い済み',
  'invoice.shippingDetails': '配送詳細',
  'invoice.orderSummary': '注文の概要',
  'invoice.shippingFee': '送料',
  'invoice.tax': '税金 (10%)',
  'invoice.totalAmount': '合計金額',
  'invoice.downloadPdf': 'PDFをダウンロード',

  // ===================================
  // Scanner Screen
  // ===================================
  'scanner.connect': '大切な人とつながる',
  'scanner.instruction': '招待リンクまたはコードを入力して\n家族のスペースに参加してください。',
  'scanner.inviteLinkLabel': '招待リンク',
  'scanner.inviteLinkHint': 'https://family.app/join/....',
  'scanner.joinBtn': 'スペースに参加',
  'scanner.myLink': 'マイリンク',
  'scanner.copiedTitle': 'リンクをコピーしました',
  'scanner.copiedMsg': 'リンクがクリップボードにコピーされました。',
  'scanner.or': 'または',
  'scanner.shareBtn': 'QRコードを共有',
  'scanner.shareText': 'やあ！私のリンクを使ってKincoreの家族スペースに参加してね: @link',
  'scanner.shareSubject': 'Kincoreで家族スペースに参加する',
  'scanner.askAdmin': '家族の管理者にプロフィール設定からQRコードを\n見せてもらってください。',

  // ===================================
  // Cart
  // ===================================
  'cart.title': 'マイカート',
  'cart.empty': 'あなたのカートは空です',
  'cart.buyNow': '今すぐ購入',
  'cart.remove': '削除',

  // ===================================
  // Order History
  // ===================================
  'orderHistory.title': '注文履歴',
  'orderHistory.searchHint': '注文IDまたは製品で検索',
  'orderHistory.netQty': 'ネット数量。1',
  'orderHistory.trackOrder': 'トラックオーダー',
  'orderHistory.status.shipped': '出荷',
  'orderHistory.status.current': '現在',
  'orderHistory.status.ago': '2日前',

  // ===================================
  // Security & Privacy
  // ===================================
  'security.title': 'セキュリティとロック',
  'security.lockProfile': 'ロックプロフィール',
  'security.lockProfileSub': '確認されたファミリーメンバーのみがタイムラインの写真と投稿を見ることができます。',
  'security.searchVisibility': '検索可視性',
  'security.visibility.everyone': 'みんな',
  'security.visibility.friends': 'Friends of Friends',
  'security.visibility.family': 'ファミリーのみ',
  'security.contactPrivacy': 'プライバシーに連絡',
  'security.hideEmail': 'メールを隠す',
  'security.hideEmailSub': 'メールはあなた以外は誰にも隠されます。',
  'security.hidePhone': '電話番号を隠す',
  'security.hidePhoneSub': 'あなたの連絡先は他のユーザーには表示されません。',
  'security.saveChanges': '変更を保存',

  // ===================================
  // Kinship Calculator
  // ===================================
  'kinship.resultTitle': '親族関係の結果',
  'kinship.path': 'パス',
  'kinship.details': 'details',
  'kinship.meaning': '意味',
  'kinship.meaningSub': '人の母の母。',
  'kinship.englishTerm': '英語の用語',
  'kinship.englishTermSub': '曾祖母',
  'kinship.newCalculation': '新しい計算',
  'kinship.editPath': 'パスを編集',
  'kinship.pathTitle': '関係パス',
  'kinship.selectPath': 'パスを選択',
  'kinship.addNextStep': '次のステップを追加',
  'kinship.calculate': '関係を計算',

  // ===================================
  // Migration Map
  // ===================================
  'migration.mapTitle': '移行マップ',
  'migration.historyTitle': '移行履歴',
  'migration.findMember': 'ファミリーメンバーを見つける',
  'migration.arrivalYear': '到着：@year',
  'migration.reason': '移行の理由',
  'migration.familyMemberCount': 'ファミリーメンバー（@count）',
  'migration.viewHistory': '移行履歴を表示',
  'migration.timeline.familyMigration': 'シュミット家の移住',
  'migration.timeline.from': 'から',
  'migration.timeline.to': 'に',
  'migration.timeline.viewRoute': 'ルートを表示',

  // ===================================
  // Claim Identity
  // ===================================
  'claim.title': 'アイデンティティを請求',
  'claim.description': 'プライベートファミリーデータにアクセスして、ツリーに貢献するため\n安全にあなたのアイデンティティを確認してください。',
  'claim.tab.verify': 'コードを確認',
  'claim.tab.confirm': '確認',
  'claim.tab.submit': '送信',
  'claim.inviteCode': '招待コード',
  'claim.inviteCodeHint': 'あなたの招待から8桁の英数字コードを入力してください。',
  'claim.profileMatch': 'プロフィールマッチが見つかりました',
  'claim.thisIsMe': 'はい、これは私です',
  'claim.confirmProfile': 'このプロフィールのデータが正確であることを確認します',
  'claim.verifyOwnership': '所有権を確認',
  'claim.emailHint': 'あなたのメールアドレスを入力してください',
  'claim.govId': 'Government ID（オプション）',
  'claim.addGovId': 'Government IDの写真を追加',
  'claim.submitClaim': 'クレームを送信',

  // ===================================
  // Request History
  // ===================================
  'requestHistory.title': 'リクエスト履歴',
  'requestHistory.thisMonth': 'この月',
  'requestHistory.birthdateUpdate': '誕生日の更新',

  // ===================================
  // Change Relationship
  // ===================================
  'changeRelationship.title': '関係を変更',
  'changeRelationship.add': '追加',
  'changeRelationship.remove': '削除',
  'changeRelationship.detailTitle': '関係の詳細',
  'changeRelationship.typeHint': 'リレーションタイプ',
  'changeRelationship.personHint': '関連する人を選択',
  'changeRelationship.reasonHint': '変更の理由（必須）',
  'changeRelationship.supportDocs': 'サポートドキュメント',
  'changeRelationship.security': 'あなたのドキュメントは安全に保存され、確認目的でファミリー管理者に表示されます。',
  'changeRelationship.saveNext': '保存して次へ',

  'All': 'すべて',
  'Pending': '保留中',
  'Approved': '承認済み',
  'Rejected': '拒否されました',
};
