// lib/localization/ms_MY.dart
// Malay translations for Kincore app

const Map<String, String> msMY = {
  // ===================================
  // Common & General
  // ===================================
  'common.add': 'Tambah',
  'common.save': 'Simpan',
  'common.cancel': 'Batal',
  'common.delete': 'Padam',
  'common.edit': 'Edit',
  'common.viewAll': 'Lihat Semua',
  'common.select': 'Pilih',
  'common.search': 'Cari',
  'common.find': 'Cari',
  'common.publish': 'Terbitkan',
  'common.saveAndAdd': 'Simpan dan Tambah',
  'common.upload': 'Muat Naik',
  'common.addFile': 'Tambah Fail',
  'common.savePhotos': 'Simpan Foto',
  'common.saveMemory': 'Simpan Kenangan',
  'common.loading': 'Sedang Memuatkan...',
  'common.error': 'Ada yang tidak betul. Sila cuba sekali lagi.',
  'common.success': 'Berjaya',
  'common.productPublished': 'Produk Diterbitkan dengan Jayanya!',
  'common.yes': 'Ya',
  'common.no': 'Tidak',
  'common.maybe': 'Mungkin',
  'common.select_country': 'Pilih Negara',
  'common.submit': 'Hantar',
  'common.done': 'Selesai',
  'common.next': 'Seterusnya',
  'common.continue': 'Teruskan',
  'common.all': 'Semua',
  'common.seeAll': 'Lihat Semua',
  'common.father': 'Bapa',
  'common.mother': 'Ibu',
  'common.sister': 'Kakak Perempuan',
  'common.brother': 'Abang',
  'common.approved': 'Diluluskan',

  // ===================================
  // Auth Screen
  // ===================================
  'auth.kincore': 'Kincore',
  'auth.connect': 'Bersambung ke Akar Anda!',
  'auth.welcomeBack': 'Selamat Kembali!',
  'auth.detailsPrompt': 'Masukkan Butiran Anda untuk Masuk atau Buat Akaun.',
  'auth.signUp': 'Daftar',
  'auth.logIn': 'Log Masuk',
  'auth.nameLabel': 'Masukkan Nama Anda',
  'auth.nameHint': 'Nama Keluarga',
  'auth.emailLabel': 'Alamat E-mel',
  'auth.emailHint': 'abc@gmail.com',
  'auth.passwordLabel': 'Kata Laluan',
  'auth.passwordHint': '••••••••',
  'auth.confirmPasswordLabel': 'Sahkan Kata Laluan',
  'auth.forgotPassword': 'Terlupa Kata Laluan?',
  'auth.continueWith': 'Atau Teruskan dengan',
  'auth.google': 'Google',
  'auth.facebook': 'Facebook',
  'auth.back': 'Kembali',
  'auth.firstName': 'Nama Pertama',
  'auth.firstNameHint': 'Ali',
  'auth.lastName': 'Nama Akhir',
  'auth.lastNameHint': 'Ahmad',
  'auth.dob': 'Tarikh Lahir (Pilihan)',
  'auth.dobHint': 'HH/BB/TTTT',
  'auth.forgotPasswordTitle': 'Lupa Kata Laluan',
  'auth.forgotPasswordHeading': 'Lupa Kata Laluan?',
  'auth.forgotPasswordDesc': 'Jangan risau! Ia biasa berlaku. Sila masukkan alamat e-mel yang dikaitkan dengan akaun anda.',
  'auth.enterEmail': 'Masukkan e-mel anda',
  'auth.sending': 'Menghantar...',
  'auth.sendCode': 'Hantar Kod',
  'profile.logoutTitle': 'Log Keluar',
  'profile.logoutSuccessMsg': 'Berjaya log keluar',

  // ===================================
  // Home Screen
  // ===================================
  'home.title': 'Utama',
  'home.goodMorning': 'Pagi yang baik',
  'home.upcomingBirthdays': 'Hari jadi akan datang',
  'home.viewCalendar': 'Lihat Kalendar',
  'home.timeline': 'Garis Masa',
  'home.startBuilding': 'Mula Membina Pokok Keluarga Anda',
  'home.startBuildingDesc': 'Tambahkan Ahli Keluarga untuk Melihat Warisan Anda Berkembang.',
  'home.addFirstMember': 'Tambah Ahli Pertama',
  'home.recentMemories': 'Kenangan Terbaru',
  'home.noMemories': 'Tiada kenangan terbaru ditemui.',
  'home.addFirstMemory': 'Tambah Kenangan Pertama Anda',
  'home.upcomingEvents': 'Acara Akan Datang',
  'home.noEvents': 'Tiada acara akan datang.',
  'home.familyEvents': 'Acara Keluarga',
  'home.familyBio': 'Biografi Keluarga',
  'home.secretSanta': 'Santapun Rahsia',
  'home.kinshipCalculator': 'Kalkulator Hubungan',
  'home.identityApproval': 'Persetujuan Identiti',
  'home.migrationMap': 'Peta Migrasi',
  'home.quickModules': 'Modul Pantas',
  'home.calculator': 'Kalkulator',
  'home.giftSwap': 'Tukar Hadiah',
  'home.savedFeed': 'Suapan Disimpan',
  'home.exploreMore': 'Teroka Lebih Lanjut',
  'home.marketplace': 'Pasaran',
  'home.reels': 'Reels',

  // ===================================
  // Navigation
  // ===================================
  'nav.home': 'Utama',
  'nav.feed': 'Suapan',
  'nav.tree': 'Pokok',
  'nav.mall': 'Pusat Membeli Belah',
  'nav.profile': 'Profil',
  'nav.memory': 'Kenangan',
  'nav.family': 'Keluarga',
  'nav.events': 'Acara',

  // ===================================
  // Tree Screen
  // ===================================
  'tree.title': 'Klan Harrison',
  'tree.generations': '@count Generasi / @members Ahli',
  'tree.webContentView': 'Paparan Kandungan Web',
  'tree.allView': 'Semua Pandangan',
  'tree.directLinage': 'Keturunan Langsung',
  'tree.birthday': 'Hari Lahir',
  'tree.anniversary': 'Ulang Tahun',

  // ===================================
  // Family Bio Screen
  // ===================================
  'familyBio.addTitle': 'Tambah biografi keluarga',
  'familyBio.addMedia': 'Tambah Media',
  'familyBio.dragAndDrop': 'Seret dan lepaskan atau semak untuk muat naik',
  'familyBio.basicInfo': 'Maklumat Asas',
  'familyBio.storyName': 'Nama Cerita',
  'familyBio.location': 'Lokasi',
  'familyBio.birthDate': 'Tarikh Lahir',
  'familyBio.selectDate': 'Pilih Tarikh',
  'familyBio.storyBio': 'Cerita (Biografi)',
  'familyBio.addBioHint': 'Tambah biografi di sini...',
  'familyBio.publishBio': 'Terbitkan Biografi',
  'familyBio.title': 'Biografi keluarga',
  'familyBio.gallery': 'Galeri',
  'familyBio.nextInHistory': 'Seterusnya dalam Sejarah',
  'familyBio.existingMember': 'Ahli Keluarga Sedia Ada',
  'familyBio.theRoaringTwenties': 'Roaring Twenties',
  'familyBio.roaringTwentiesDate': '1920 - 1929',
  'familyBio.migrationStoryDate': '4 November 1920 · Sicilia ke New York',
  'familyBio.migrationStoryContent': 'Migrasi Besar, momen penting dalam sejarah, melihat berjuta-juta orang memulai perjalanan ke tanah baru, mencari peluang dan permulaan baru. Antara mereka adalah Maria Rossi, seorang wanita muda dari Sicilia, yang berlayar ke New York pada tahun 1920. Kisahnya, seperti banyak orang lain, adalah bukti keberanian, ketahanan, dan jiwa manusia yang tahan lama.',
  'familyBio.migrationStoryQuote': '"Perjalanan itu panjang dan melelahkan, tetapi harapan akan kehidupan yang lebih baik membuat kami maju." – Maria Rossi',
  'familyBio.errorTitle': 'Ralat',
  'familyBio.nameRequired': 'Nama Cerita diperlukan',
  'familyBio.successTitle': 'Berjaya',
  'familyBio.publishedMsg': 'Biografi Diterbitkan!',

  // ===================================
  // Market Place
  // ===================================
  'marketplace.title': 'Pasaran',
  'marketplace.searchHint': 'Cari produk, kategori...',
  'marketplace.bannerTitle': 'Jualan Musim Panas Sedang Berlangsung!',
  'marketplace.bannerSub': 'Cari tawaran terbaik berhampiran anda.',
  'marketplace.noProducts': 'Tiada produk ditemui!',
  'marketplace.catAll': 'Semua',
  'marketplace.catVehicles': 'Kenderaan',
  'marketplace.catProperty': 'Hartanah',
  'marketplace.catElectronics': 'Elektronik',
  'marketplace.catFurniture': 'Perabot',
  'marketplace.catFashion': 'Fesyen',
  'marketplace.msgAvailable': 'Hai, adakah ini masih ada?',
  'marketplace.timeJustNow': 'Baru sahaja',
  'marketplace.timeYesterday': 'Semalam',
  'marketplace.messages': 'Mesej',
  'marketplace.noMessages': 'Tiada mesej lagi.',

  // ===================================
  // Add Family Member
  // ===================================
  'addMember.title': 'Tambah Ahli Keluarga',
  'addMember.basicInfo': 'Maklumat Asas',
  'addMember.firstName': 'Nama',
  'addMember.lastName': 'Nama Keluarga',
  'addMember.gender': 'Jantina',
  'addMember.male': 'Lelaki',
  'addMember.female': 'Perempuan',
  'addMember.other': 'Lain-lain',
  'addMember.dateOfBirth': 'Tarikh Lahir',
  'addMember.dateFormatHint': 'MM/DD/YYYY',
  'addMember.relationshipSetup': 'Persediaan Hubungan',
  'addMember.relationshipType': 'Jenis Hubungan',
  'addMember.relationship.spouse': 'Pasangan',
  'addMember.relationship.sibling': 'Adik Beradik',
  'addMember.relationship.parent': 'Ibu Bapa',
  'addMember.findFamilyMember': 'Cari Ahli Keluarga',
  'addMember.spouseName': 'Nama Pasangan',
  'addMember.anniversaryDate': 'Tarikh Hari Jadi',
  'addMember.additionalDetail': 'Butiran Tambahan',
  'addMember.addLocation': 'Tambah lokasi',
  'addMember.occupation': 'Pekerjaan',
  'addMember.bioNotes': 'Biografi / Nota',
  'addMember.privacyVisibility': 'Privasi dan Keterlihatan',
  'addMember.visibleToAll': 'Boleh dilihat oleh semua ahli',
  'addMember.addParentsTitle': 'Tambah Ibu Bapa',
  'addMember.addOtherMember': 'Tambah Ahli Keluarga Lain',
  'addMember.placeOfBirth': 'Tempat Lahir',
  'addMember.currentLocation': 'Lokasi Semasa',
  'addMember.addChildTitle': 'Tambah Anak',
  'addMember.schoolAndCollege': 'Sekolah dan Kolej',
  'addMember.qualification': 'Kelayakan',
  'addMember.studyLocation': 'Lokasi Belajar',
  'addMember.changePhoto': 'Tukar Foto',
  'addMember.livingStatus': 'Status Hidup',
  'addMember.isAlive': 'Adakah orang itu masih hidup?',
  'addMember.alive': 'Hidup',
  'addMember.deceased': 'Meninggal',
  'addMember.phoneNumber': 'Nombor Telefon',
  'addMember.phoneHint': '00000 00000',

  // ===================================
  // Memory Screen
  // ===================================
  'memory.title': 'Kenangan',
  'memory.addTitle': 'Tambah Kenangan',
  'memory.tabAll': 'Semua',
  'memory.tabPhotos': 'Foto',
  'memory.tabVideos': 'Video',
  'memory.addMemoryPhotos': 'Tambah Foto Kenangan',
  'memory.addMemoryVideos': 'Tambah Video Kenangan',
  'memory.uploadSupport': 'Sokongan Fail PNG, JPG',

  // ===================================
  // K-Mall & Products
  // ===================================
  'mall.title': 'Pusat Membeli Belah',
  'mall.searchHint': 'Cari Produk',
  'mall.filter': 'Penapis',
  'mall.categories': 'Kategori',
  'mall.featured': 'Pilihan Terbaik',
  'mall.mostPopular': 'Paling Popular',
  'mall.onSale': 'Sedang Diskaun',
  'mall.wishlistTitle': 'Senarai Kehendak Saya',
  'mall.noItemsWishlist': 'Senarai kehendak anda kosong!',
  'mall.exploreProducts': 'Jelajahi Produk',
  'mall.productDetails': 'Butiran Produk',
  'mall.description': 'Penerangan',
  'mall.selectSize': 'Pilih Saiz',
  'mall.selectColor': 'Pilih Warna',
  'mall.quantity': 'Kuantiti',
  'mall.addToCart': 'Tambah ke Troli',
  'mall.buyNow': 'Beli Sekarang',
  'mall.reviews': 'Ulasan',
  'mall.noReviews': 'Tiada ulasan untuk produk ini lagi.',
  'mall.sellerInfo': 'Maklumat Penjual',
  'mall.viewShop': 'Lihat Kedai',
  'mall.relatedProducts': 'Produk Berkaitan',
  'mall.addedToCart': '@productName ditambahkan ke troli',
  'mall.filterPrice': 'Julat Harga',
  'mall.filterColor': 'Warna',
  'mall.filterGender': 'Jantina',
  'mall.category.fashion': 'Fesyen',
  'mall.category.electronics': 'Elektronik',
  'mall.category.appliances': 'Perkakas',
  'mall.category.beauty': 'Kecantikan',
  'mall.category.furniture': 'Perabot',
  'mall.banner.title': 'Koleksi Baru',
  'mall.banner.discount': '50% DISKAUN',
  'mall.banner.for': 'Untuk Kanak-kanak',
  'mall.productReview': '@rating (@count Ulasan)',
  'mall.tag.homeMade': 'Buatan Tangan',
  'mall.tag.newCollection': 'Koleksi baru',

  // ===================================
  // Add Product
  // ===================================
  'addProduct.title': 'Tambah Produk Baru',
  'addProduct.detailsPrompt': 'Masukkan semua butiran untuk menyenaraikan produk anda',
  'addProduct.uploadImagesTitle': 'Muat Naik Imej Produk',
  'addProduct.uploadImagesDesc': 'Gunakan imej resolusi tinggi yang jelas. Imej pertama akan menjadi sampul.',
  'addProduct.addMedia': 'Tambah Media',
  'addProduct.dragAndDrop': 'Seret dan lepaskan atau semak untuk muat naik',
  'addProduct.basicInfo': 'Maklumat Asas',
  'addProduct.productNameLabel': 'Nama Produk (diperlukan)',
  'addProduct.priceLabel': 'Harga',
  'addProduct.discountLabel': 'Diskaun %',
  'addProduct.descriptionLabel': 'Penerangan',
  'addProduct.sizeLabel': 'Saiz',
  'addProduct.conditionsLabel': 'Keadaan',
  'addProduct.brandNameLabel': 'Nama Jenama',
  'addProduct.profileLabel': 'Pilih Profil Anda',
  'addProduct.categoryLabel': 'Kategori',
  'addProduct.subCategoryLabel': 'Sub-Kategori',
  'addProduct.quantityLabel': 'Kuantiti',
  'addProduct.publishButton': 'Terbitkan Produk',

  // ===================================
  // Redeem Coin Screen
  // ===================================
  'redeem.title': 'Tebus Syiling KCC',
  'redeem.totalBalance': 'JUMLAH BAKI',
  'redeem.kccBalance': 'Baki KCC',
  'redeem.currency': 'KCC',
  'redeem.waysToRedeem': 'Cara Menebus',
  'redeem.waysToEarn': 'Cara Memperoleh',
  'redeem.recentActivity': 'Aktiviti Terbaru',
  'redeem.vintageCase': 'Kotak Vintaj',
  'redeem.kmallPurchase': 'Pembelian di Pusat Membeli Belah',
  'redeem.redeemedKcc': '-455 KCC',
  'redeem.shopAndSave': 'Beli dan Jimat',
  'redeem.redeemForCash': 'Tebus Tunai',
  'redeem.shopNow': 'Beli Sekarang',
  'redeem.redeemNow': 'Tebus Sekarang',
  'redeem.option.shop.title': 'Beli di Pusat Membeli Belah',
  'redeem.option.shop.description': 'Gunakan syiling untuk membeli produk warisan keluarga eksklusif.',
  'redeem.option.shop.button': 'Jelajahi Pusat Membeli Belah',
  'redeem.option.support.title': 'Sokong Keluarga',
  'redeem.option.support.description': 'Pindahkan syiling untuk menyokong saudara mara.',
  'redeem.option.support.button': 'Hantar Hadiah',
  'redeem.option.boost.title': 'Senarai Peningkatan',
  'redeem.option.boost.description': 'Promosikan produk anda untuk penjualan yang lebih besar.',
  'redeem.option.boost.button': 'Promosi Sekarang',
  'redeem.featuredRewards': 'Ganjaran Pilihan',
  'redeem.completeProfile': 'Lengkapkan profil anda',
  'redeem.earnKcc': 'Jana @points KCC',

  // ===================================
  // Coin Card Level
  // ===================================
  'profile.levelBadge': 'Tahap @level @title',

  // ===================================
  // Earn
  // ===================================
  'earn.referral': 'Rujuk Rakan',
  'earn.referralSub': 'Peroleh 20 KCC',
  'earn.completeProfile.title': 'Lengkapkan Profil Anda',
  'earn.completeProfile.subtitle': 'Peroleh 60KCC',
  'earn.addPhoto.title': 'Tambah Foto Keluarga',
  'earn.addPhoto.subtitle': 'Peroleh 20KCC',
  'earn.inviteMember.title': 'Jemput Ahli Keluarga',
  'earn.inviteMember.subtitle': 'Peroleh 20KCC',
  'earn.attendEvent.title': 'Hadir Acara Keluarga',
  'earn.attendEvent.subtitle': 'Peroleh 45KCC',

  // ===================================
  // Create Event Screen
  // ===================================
  'createEvent.title': 'Cipta Acara',
  'createEvent.saveDraft': 'Simpan',
  'createEvent.addCoverPhoto': 'Tambah Foto Sampul',
  'createEvent.uploadSupport': 'Sokongan Fail PNG, JPG',
  'createEvent.detailTitle': 'Butiran Acara',
  'createEvent.eventTitleLabel': 'Tajuk Acara',
  'createEvent.eventTitleHint': 'Masukkan Tajuk',
  'createEvent.locationLabel': 'Lokasi',
  'createEvent.locationHint': 'Masukkan Alamat Lokasi',
  'createEvent.descriptionLabel': 'Penerangan',
  'createEvent.descriptionHint': 'Tulis di sini...',
  'createEvent.startDateLabel': 'Tarikh Mula',
  'createEvent.endDateLabel': 'Tarikh Tamat',
  'createEvent.timeLabel': 'Masa',
  'createEvent.timeHint': 'Masukkan Masa',
  'createEvent.inviteMemberTitle': 'Jemput Ahli Keluarga',
  'createEvent.starts': 'Mula',
  'createEvent.ends': 'Tamat',
  'createEvent.requestRSVP': 'Minta RSVP',
  'createEvent.requestRSVPSub': 'Tetamu mesti mengesahkan kehadiran',
  'createEvent.sendReminders': 'Hantar Peringatan',
  'createEvent.sendRemindersSub': 'Beritahu tetamu 1 hari sebelum',
  'createEvent.includeGiftExchange': 'Termasuk Pertukaran Hadiah',
  'createEvent.includeGiftExchangeSub': 'cth. Secret Santa atau Tukar Hadiah',
  'createEvent.nextAddGift': 'Seterusnya & Tambah Hadiah',
  'createEvent.createEventBtn': 'Cipta Acara',
  'createEvent.eventCreatedTitle': 'Acara Dicipta',
  'createEvent.eventCreatedMsg': 'Acara Anda Berjaya Dicipta!',

  // ===================================
  // Feed & Posts
  // ===================================
  'feed.title': 'Suapan Keluarga',
  'feed.myStory': 'Cerita Saya',
  'feed.whatsHappening': 'Apa Sedang Berlaku?',
  'feed.createPost': 'Cipta Pos',
  'feed.archive': 'Arkib',
  'feed.writeCommentHint': 'Tulis ulasan...',
  'feed.viewComments': 'Lihat @count Ulasan',
  'feed.postAnonymously': 'Pos Secara Tanpa Nama',
  'feed.allowComments': 'Benarkan Ulasan',
  'feed.saveToDevice': 'Simpan ke Peranti',
  'feed.reportPost': 'Lapor Pos',
  'feed.archiveMenu': 'Arkib',
  'feed.reportMenu': 'Lapor',
  'feed.archiveMsg': 'Siaran ditambahkan ke arkib anda.',
  'feed.savedTitle': 'Disimpan',
  'feed.savedMsg': 'Siaran disimpan ke koleksi anda.',
  'feed.removedTitle': 'Dialih keluar',
  'feed.removedMsg': 'Siaran dialih keluar dari simpanan.',
  'feed.caughtUp': 'Anda sudah ketahui semuanya!',
  'feed.findMore': 'Cari lebih ramai ahli keluarga',
  'feed.writeComment': 'Tulis komen...',
  'createPost.successTitle': 'Berjaya',
  'createPost.successMsg': 'Siaran berjaya dicipta!',
  'createPost.errorTitle': 'Ralat',
  'createPost.errorMsg': 'Sila masukkan beberapa teks atau tambah media.',
  'feed.savedCollection': 'Koleksi Disimpan',
  'feed.noSavedPosts': 'Belum ada siaran yang disimpan',
  'feed.removeFromCollection': 'Alih keluar dari koleksi',

  // ===================================
  // Post Settings
  // ===================================
  'postSettings.title': 'Tetapan Pos',
  'postSettings.postSettings': 'Tetapan Pos',
  'postSettings.whoCanSee': 'Siapa Boleh Lihat Pos Anda?',
  'postSettings.visibility.public': 'Umum',
  'postSettings.visibility.friends': 'Kawan-kawan',
  'postSettings.visibility.friendsExcept': 'Kawan Kecuali',
  'postSettings.visibility.specificFriends': 'Kawan Tertentu',
  'postSettings.whoCanComment': 'Siapa Boleh Ulasan Pos Ini?',
  'postSettings.comments.followersOnly': 'Hanya Pengikut Anda',
  'postSettings.comments.friends': 'Kawan-kawan',
  'postSettings.comments.chosenFriends': 'Kawan Terpilih',
  'postSettings.saveChanges': 'Simpan Perubahan',

  // ===================================
  // Create Post
  // ===================================
  'createPost.title': 'Cipta Pos',
  'createPost.hint': 'Apakah yang Anda fikirkan?',
  'createPost.addMedia': 'Tambah media',
  'createPost.tagPeople': 'Tandai orang',
  'createPost.postButton': 'Pos',

  // ===================================
  // Report
  // ===================================
  'report.title': 'Lapor Masalah',
  'report.anonymousHelp': 'Laporan Anda Tanpa Nama. Bantu Kami Memastikan Komuniti Pokok Keluarga Selamat dengan Beritahu Kami Apa yang Sedang Berlaku.',
  'report.reasonTitle': 'Sebab Laporan',
  'report.spam': 'Ia Spam',
  'report.nudity': 'Ketelanjangan atau Aktiviti Seksual',
  'report.hateSpeech': 'Ucapan Kebencian atau Simbol',
  'report.falseInfo': 'Maklumat Palsu',
  'report.harassment': 'Gangguan atau Buli',
  'report.other': 'Sesuatu yang Lain',
  'report.additionalDetails': 'Butiran Tambahan (Pilihan)',
  'report.describeIssue': 'Sila Huraikan Masalah untuk Membantu Ulasan Kami',
  'report.submitReport': 'Hantar Laporan',
  'report.dialog.discardTitle': 'Buang Laporan?',
  'report.dialog.discardBody': 'Adakah anda pasti ingin membatalkan laporan ini? Kemajuan anda akan hilang.',
  'report.dialog.stay': 'Tidak, Tinggal',
  'report.dialog.discard': 'Ya, Buang',

  // ===================================
  // Seller Dashboard
  // ===================================
  'seller.title': 'Papan Pemuka',
  'seller.overview': 'Gambaran Keseluruhan',
  'seller.totalRevenue': 'Jumlah Pendapatan',
  'seller.orders': 'Pesanan',
  'seller.avgOrderValue': 'Nilai Pesanan Purata',
  'seller.products': 'Produk',
  'seller.topProducts': 'Produk Teratas',
  'seller.recentOrders': 'Pesanan Terbaru',
  'seller.orderId': 'Pesanan',
  'seller.noProducts': 'Tiada produk untuk dipaparkan.',
  'seller.noOrders': 'Tiada pesanan terbaru.',
  'seller.noData': 'Data Tidak Tersedia',

  // ===================================
  // Profile & Settings
  // ===================================
  'profile.title': 'Profil Saya',
  'profile.followers': 'Pengikut',
  'profile.following': 'Mengikuti',
  'profile.editProfile': 'Edit Profil',
  'profile.addMember': 'Tambah Ahli',
  'profile.addMemory': 'Tambah Kenangan',
  'profile.vitalStats': 'Statistik Vital',
  'profile.stat.fullName': 'Nama Lengkap',
  'profile.stat.born': 'Lahir',
  'profile.stat.location': 'Lokasi',
  'profile.stat.occupation': 'Pekerjaan',
  'profile.familyMember': 'Ahli Keluarga',
  'profile.keyLifeEvents': 'Peristiwa Utama Kehidupan',
  'profile.viewMoreTimeline': 'Lihat Garis Masa Lagi',
  'profile.memories': 'Kenangan',
  'profile.shareProfile': 'Kongsi Profil',
  'profile.personal': 'Peribadi',
  'profile.business': 'Perniagaan',
  'profile.posts': 'Pos',
  'profile.photos': 'Foto',
  'profile.videos': 'Video',
  'profile.tagged': 'Ditandai',
  'profile.myProfile': 'Profil Saya',
  'profile.sellerDashboard': 'Papan Pemuka Penjual',
  'profile.identityApproval': 'Persetujuan Identiti',
  'profile.redeemCoins': 'Tebus Syiling',
  'profile.settings': 'Tetapan',
  'profile.logout': 'Log Keluar',
  'profile.logoutConfirm': 'Adakah anda pasti ingin log keluar?',
  'profile.personalProfile': 'Profil Peribadi',
  'profile.roleAccess': 'Peranan & Kebenaran Anda',
  'profile.viewDashboard': 'Lihat Papan Pemuka Penjual Saya',
  'profile.addProduct': 'Tambah Produk',
  'profile.account': 'Akaun',
  'profile.personalInfo': 'Maklumat Peribadi',
  'profile.personalInfoSub': 'Nama, E-mel, Nombor Telefon',
  'profile.privacy': 'Privasi dan Keselamatan',
  'profile.privacySub': 'Keterlihatan Pokok Keluarga, Kata Laluan',
  'profile.notifications': 'Pemberitahuan',
  'profile.notificationsSub': 'Acara, Kemas Kini, Mesej',
  'profile.darkMode': 'Mod Gelap',
  'profile.darkModeSub': 'Togol Tema Aplikasi',
  'profile.myOrders': 'Pesanan Saya',
  'profile.myOrdersSub': 'Sejarah Pesanan, Pengembalian',
  'profile.myListings': 'Penyenaraian Saya',
  'profile.myListingsSub': 'Pengurusan untuk Dijual',
  'profile.privacyLocked': 'Privasi: Dikunci',
  'profile.privacyUnlocked': 'Privasi: Tidak Dikunci',
  'profile.message': 'Mesej',
  'profile.viewFeed': 'Lihat Suapan',
  'profile.viewStory': 'Lihat Cerita',
  'profile.viewProfilePic': 'Lihat Gambar Profil',
  'profile.viewUserFeed': 'Lihat Suapan Pengguna',
  'profile.privacyLockedTitle': 'Privasi Dikunci 🔒',
  'profile.privacyUnlockedTitle': 'Privasi Tidak Dikunci 🔓',
  'profile.privacyLockedMsg': 'Profil anda kini bersifat peribadi.',
  'profile.privacyUnlockedMsg': 'Profil anda kini boleh dilihat oleh orang lain.',
  'profile.requestHistory': 'Sejarah Permintaan',
  'profile.requestHistorySub': 'Semak Sejarah Permintaan Anda',
  'profile.saveFeed': 'Suapan Disimpan',
  'profile.saveFeedSub': 'Koleksi Suapan Disimpan',
  'profile.giftSwap': 'Tukar Hadiah',
  'profile.giftSwapSub': 'Tukar Hadiah Anda',
  'profile.displayMode': 'Mod Paparan',
  'profile.displayModeSub': 'Selaraskan penampilan (Cerah/Gelap)',
  'giftSwap.setRestrictions': 'Tetapkan Sekatan Cabutan',
  'giftSwap.setRestrictionsSub': 'Halang ahli tertentu daripada mencabut satu sama lain',
  'giftSwap.restrictionsTitle': 'Sekatan',
  'giftSwap.restrictionsMsg': 'Di sini pentadbir boleh menetapkan peraturan seperti A tidak boleh mencabut B.',
  'giftSwap.successTitle': 'Berjaya',
  'giftSwap.createdMsg': 'Acara Tukar Hadiah Berjaya Dicipta!',
  'profile.display': 'Paparan',
  'profile.chooseAppearance': 'Pilih Penampilan',
  'profile.lightMode': 'Mod Cerah',
  'profile.systemPref': 'Keutamaan Sistem',
  'profile.systemPrefSub': 'Selaraskan dengan tetapan peranti',

  // ===================================
  // Edit Profile
  // ===================================
  'editProfile.title': 'Edit Profil',
  'editProfile.changePhoto': 'Tukar Foto',
  'editProfile.firstNameLabel': 'Nama',
  'editProfile.firstNameHint': 'Masukkan Nama',
  'editProfile.lastNameLabel': 'Nama Keluarga',
  'editProfile.lastNameHint': 'Masukkan Nama Keluarga',
  'editProfile.endDateLabel': 'Tarikh Tamat',
  'editProfile.locationLabel': 'Lokasi',
  'editProfile.locationHint': 'Masukkan Alamat Lokasi',
  'editProfile.occupationLabel': 'Pekerjaan',
  'editProfile.occupationHint': 'Masukkan Pekerjaan',
  'editProfile.designationLabel': 'Penamaan',
  'editProfile.designationHint': 'Masukkan Penerangan',
  'editProfile.companyNameLabel': 'Nama Syarikat',
  'editProfile.companyNameHint': 'Masukkan Nama Syarikat',
  'editProfile.websiteLabel': 'Laman Web',
  'editProfile.websiteHint': 'Tampal Laman Web Anda',
  'editProfile.linkedInLabel': 'LinkedIn',
  'editProfile.linkedInHint': 'Tampal Pautan LinkedIn',
  'editProfile.instagramLabel': 'Instagram',
  'editProfile.instagramHint': 'Tampal Pautan Instagram',
  'editProfile.facebookLabel': 'Facebook',
  'editProfile.facebookHint': 'Tampal Pautan Facebook',
  'editProfile.otherLinkLabel': 'Pautan Lain',
  'editProfile.otherLinkHint': 'Tampal Pautan Lain',
  'editProfile.addOtherLink': 'Tambah Pautan Lain',
  'editProfile.claimIdentity': 'Tuntut Identiti',

  // ===================================
  // Events
  // ===================================
  'event.status.attended': 'Hadir',
  'event.status.notAttended': 'Tidak Hadir',
  'event.status.joinnow': 'Sertai Sekarang',
  'event.detailTitle': 'Butiran Acara',
  'event.hostedBy': 'DIANJURKAN OLEH',
  'event.areYouGoing': 'Adakah anda pergi?',
  'event.responseRequired': 'Respons Diperlukan',
  'event.going': 'Pergi',

  // ===================================
  // Family Events
  // ===================================
  'familyEvents.title': 'Acara Keluarga',
  'familyEvents.findHint': 'Cari Acara',
  'familyEvents.tabUpcoming': 'Akan Datang',
  'familyEvents.tabPast': 'Lalu',

  // ===================================
  // Member List
  // ===================================
  'memberList.title': 'Semua Ahli Keluarga',
  'memberList.tabFamilies': 'Keluarga',
  'memberList.tabPeople': 'Orang',
  'memberList.noMembers': 'Tiada ahli ditemui',
  'memberList.present': 'Hadir',
  'memberList.location': 'California, USA',

  // ===================================
  // Find Yourself
  // ===================================
  'findYourself.title': 'Cari Diri Anda',
  'findYourself.searchHint': 'Cari Nama/Hari Jadi',
  'findYourself.bestMatches': 'Padanan Terbaik',
  'findYourself.foundCount': '@count Ditemui',
  'findYourself.notListed': 'Tidak Disenaraikan? Sila Buat Profil',
  'findYourself.thisIsMe': 'Ini Saya',
  'findYourself.subtitle': 'Cari nama anda untuk memautkan akaun anda ke\nrekod salasilah keluarga yang sedia ada.',
  'findYourself.possibleMatches': 'Padanan yang Mungkin',
  'findYourself.selectionReqTitle': 'Pemilihan Diperlukan',
  'findYourself.selectionReqMsg': 'Sila pilih profil anda terlebih dahulu.',
  'findYourself.firstName': 'Nama Pertama',
  'findYourself.lastName': 'Nama Akhir',
  'findYourself.gender': 'Jantina',
  'findYourself.selectGender': 'Pilih Jantina',
  'findYourself.dob': 'Tarikh Lahir',
  'findYourself.yearOnly': 'Padanan tahun sahaja',
  'findYourself.searchBtn': 'Cari',
  'findYourself.clearBtn': 'Kosongkan',
  'findYourself.initialMsg': 'Masukkan sekurang-kurangnya satu medan dan ketik Cari.',
  'findYourself.noResults': 'Tiada Hasil Ditemui',
  'findYourself.noResultsSub': 'Cuba laraskan istilah carian anda atau kosongkan penapis.',
  'findYourself.resultsCount': '@count Hasil Ditemui',
  'findYourself.validationMsg': 'Sila masukkan sekurang-kurangnya satu medan untuk mencari.',
  'findYourself.male': 'Lelaki',
  'findYourself.female': 'Perempuan',
  'findYourself.other': 'Lain-lain',
  'findYourself.firstNameHint': 'Masukkan nama pertama',
  'findYourself.lastNameHint': 'Masukkan nama akhir',
  'findYourself.dobHint': 'Pilih tarikh',

  // ===================================
  // Find Member
  // ===================================
  'findMember.title': 'Cari Ahli Keluarga',
  'findMember.searchHint': 'Cari Ahli Keluarga',
  'findMember.lastViewed': 'Dilihat Terakhir',

  // ===================================
  // Role & Access
  // ===================================
  'role.title': 'Peranan dan Akses',
  'role.currentRole': 'Peranan Semasa: @role',
  'role.familySpace': 'Ruang Keluarga Smith',
  'role.adminAccessTitle': 'Akses Pentadbir',
  'role.adminAccessDesc': 'Pentadbir Mempunyai Kawalan Penuh Atas Ruang Keluarga. Mereka Boleh Menguruskan Ahli dan Mengkonfigurasi Tetapan.',
  'role.permission.editTree': 'Penyuntingan Pokok Keluarga',
  'role.permission.editTreeSub': 'Tambah Edit Atau Padam Profil Mana-mana',
  'role.permission.memberMgmt': 'Pengurusan Ahli',
  'role.permission.memberMgmtSub': 'Jemput Pengguna Baru dan Tetapkan Peranan',
  'role.permission.spaceSettings': 'Tetapan Ruang',
  'role.permission.spaceSettingsSub': 'Tukar Privasi dan Pemberitahuan',
  'role.permission.contentModeration': 'Penyederhanaan Kandungan',
  'role.permission.contentModerationSub': 'Urus Album dan Siaran yang Dipadamkan',
  'role.warning': 'Hanya Pencipta Keluarga Boleh Memindahkan Pemilikan Atau Padamkan Seluruh Ruang Keluarga.',
  'role.changePermission': 'Adakah Anda Perlu Mengubah Kebenaran Anda?',
  'role.contactCreator': 'Hubungi Pencipta Keluarga',
  'role.saveAndCreate': 'Simpan dan Cipta',
  'role.limitedAccess': 'Akses Terhad',
  'role.limitedAccessDesc': 'Tidak Boleh Melihat Maklumat Sulit Atau Edit Pokok.',
  'role.fullAccess': 'Akses Penuh',
  'role.fullAccessDesc': 'Boleh Melihat Semua Maklumat dan Edit Pokok Keluarga.',
  'role.admin': 'Pentadbir',
  'role.member': 'Ahli',
  'role.guest': 'Tetamu',

  // ===================================
  // Family Space
  // ===================================
  'chooseSpace.welcome': 'Selamat datang ke Kincore!',
  'chooseSpace.subtitle': 'Bagaimana anda ingin memulakan perjalanan keluarga anda? Pilih pilihan di bawah.',
  'chooseSpace.createTitle': 'Cipta Ruang Keluarga Baharu',
  'chooseSpace.createSubtitle': 'Sediakan ruang baharu untuk keluarga anda berhubung, berkongsi dan berkembang.',
  'chooseSpace.joinTitle': 'Sertai Ruang Sedia Ada',
  'chooseSpace.joinSubtitle': 'Ada kod jemputan atau pautan? Sertai ahli keluarga anda di sini.',
  'chooseSpace.joinSnackbarTitle': 'Sertai Ruang',
  'chooseSpace.joinSnackbarMsg': 'Menavigasi ke Skrin Sertai Ruang...',
  'createSpace.appBarTitle': 'Cipta Ruang Keluarga',
  'createSpace.welcome': 'Selamat datang ke Kincore!',
  'createSpace.subtitle': 'Sediakan ruang khusus untuk berhubung, berkongsi dan berkembang bersama ahli keluarga anda.',
  'createSpace.uploadPhoto': 'Muat Naik Foto Ruang',
  'createSpace.nameLabel': 'Nama Ruang Keluarga',
  'createSpace.nameHint': 'Cth., Keluarga Anderson',
  'createSpace.descLabel': 'Penerangan (Pilihan)',
  'createSpace.descHint': 'Tulis biodata ringkas untuk keluarga anda...',
  'createSpace.createBtn': 'Cipta Ruang',
  'createSpace.selectImageTitle': 'Pilih Imej',
  'createSpace.selectImageMsg': 'Pemilih imej akan dibuka di sini.',
  'createSpace.validationErrorTitle': 'Ralat Pengesahan',
  'createSpace.validationErrorMsg': 'Sila masukkan Nama Ruang Keluarga anda.',
  'createSpace.successTitle': 'Berjaya',
  'createSpace.successMsg': 'Ruang Keluarga \'@name\' berjaya dicipta!',
  'chooseSpace.joinOptionsTitle': 'Sertai Ruang',
  'chooseSpace.scanQr': 'Imbas Kod QR',
  'chooseSpace.scanQrSub': 'Sertai serta-merta menggunakan QR keluarga',
  'chooseSpace.joinUrl': 'Sertai melalui URL',
  'chooseSpace.joinUrlSub': 'Tampal pautan jemputan',
  'chooseSpace.findYourself': 'Cari Diri Anda',
  'chooseSpace.findYourselfSub': 'Cari profil anda dalam salasilah keluarga',
  'joinOptions.title': 'Sertai Ruang',
  'joinOptions.scanTitle': 'Imbas Kod QR',
  'joinOptions.scanSub': 'Imbas QR keluarga dari kamera atau galeri',
  'joinOptions.urlTitle': 'Sertai melalui URL',
  'joinOptions.urlSub': 'Tampal pautan jemputan di sini',
  'joinOptions.findTitle': 'Cari Diri Anda',
  'joinOptions.findSub': 'Cari nama anda dan tuntut identiti anda',
  'urlJoin.title': 'Sertai melalui Pautan',
  'urlJoin.subtitle': 'Tampal pautan jemputan ruang keluarga di bawah.',
  'urlJoin.hint': 'Tampal URL di sini...',
  'urlJoin.submit': 'Sertai Ruang',
  'scanner.title': 'Imbas Kod QR',
  'scanner.subtitle': 'Selaraskan kod QR keluarga di dalam bingkai',
  'scanner.galleryBtn': 'Muat naik dari Galeri',

  // ===================================
  // Role Access
  // ===================================
  'roleAccess.title': 'Peranan dan Akses',
  'roleAccess.manager': 'Pengurus',
  'roleAccess.permissions': 'Kebenaran',
  'roleAccess.viewTree': 'Lihat Pokok Keluarga',
  'roleAccess.editTree': 'Edit Pokok Keluarga',
  'roleAccess.addMembers': 'Tambah Ahli Keluarga',
  'roleAccess.deleteMembers': 'Padam Ahli Keluarga',
  'roleAccess.manageRoles': 'Urus Peranan dan Kebenaran',
  'roleAccess.postFeed': 'Pos di Suapan Keluarga',
  'roleAccess.viewMemories': 'Lihat Kenangan',
  'roleAccess.createEvents': 'Cipta Acara',

  // ===================================
  // Role Selection
  // ===================================
  'roleSelection.title': 'Pilih Peranan Anda',
  'roleSelection.grandparent': 'Datuk Nenek',
  'roleSelection.parent': 'Ibu Bapa',
  'roleSelection.adult': 'Dewasa',
  'roleSelection.teenager': 'Remaja',
  'roleSelection.child': 'Kanak-kanak',

  // ===================================
  // Identity Approval
  // ===================================
  'identity.title': 'Persetujuan Identiti',
  'identity.pendingRequests': 'Permintaan Belum Selesai',
  'identity.noRequests': 'Tiada permintaan belum selesai',
  'identity.claiming': 'MENUNTUT IDENTITI',
  'identity.proof.photo': 'Bukti Fotografi',
  'identity.proof.birth': 'Sijil Kelahiran',
  'identity.reject': 'Tolak',
  'identity.requestFrom': 'Permintaan Dari',
  'identity.approve': 'Luluskan',
  'identity.decline': 'Tolak',
  'identity.statusTitle': 'Status Identiti',
  'identity.claimPending': 'Tuntutan Belum Selesai',
  'identity.status.pending': 'Belum Selesai',
  'identity.status.description': 'Kami Telah Menerima Tuntutan Anda untuk Joseph Nenek Moyang. Ini Biasanya Mengambil 24-48 Jam.',
  'identity.submittedOn': 'Diserahkan pada',
  'identity.relationship': 'Perhubungan',
  'identity.relationshipValue': 'Datuk',
  'identity.verificationProgress': 'Kemajuan Pengesahan',
  'identity.progress.submitted': 'Permintaan Diserahkan',
  'identity.progress.submittedSub': 'Dokumen Anda Diterima',
  'identity.progress.inProgress': 'Pengesahan Sedang Berlangsung',
  'identity.progress.inProgressSub': 'Pasukan Kami Memeriksa ID dan Bukti Perhubungan Anda.',
  'identity.progress.decision': 'Keputusan Akhir',
  'identity.progress.decisionSub': 'Kelulusan Atau Permintaan Maklumat Lanjut.',
  'identity.addProof': 'Muat Naik Bukti Tambahan',
  'identity.addProofPhoto': 'Tambah Foto Bukti Tambahan',
  'identity.backToProfile': 'Kembali ke Profil',
  'requestHistory.requestApproved': 'Permintaan Diluluskan',
  'requestHistory.dataChange': 'Perubahan Data',
  'requestHistory.requestSubmitted': 'Permintaan Dihantar',
  'requestHistory.adminComment': '“Disahkan dengan sijil kelahiran yang diberikan melalui e-mel.”',
  'requestHistory.reviewedBy': 'Disemak oleh @admin (Pentadbir)',
  'requestHistory.changeTo': ' tukar kepada ',
  'requestHistory.dummyApprovedTime': '22 Okt 2025/10:30 Pagi',
  'requestHistory.dummySubmittedTime': '20 Okt 2023 / anda',

  // ===================================
  // Space Management
  // ===================================
  'space.switch': 'Tukar Ruang',
  'space.current': 'Ruang Semasa',
  'space.other': 'Ruang Lain',
  'space.confirmSwitch': 'Sahkan Tukar',
  'space.switchedTo': 'Anda Kini Di @spaceName',
  'space.online': 'Dalam Talian',
  'space.members': '@count Ahli',
  'space.active': 'Aktif',

  // ===================================
  // Generation Screen
  // ===================================
  'generation.title': 'Generasi',
  'generation.noData': 'Tiada Data Ditemui',
  'generation.genSuffix': '@level Generasi',
  'generation.members': 'Ahli',
  'generation.generation': 'Generasi',
  'generation.years': 'Tahun',

  // ===================================
  // Gift & Draw Screens
  // ===================================
  'gift.letsDraw': 'Mari Kita Sertai!',
  'gift.surpriseBegin': 'Biarkan Kejutan Bermula!',
  'gift.spinning': 'Berputar...',
  'gift.spinWheel': 'Putaran Roda',
  'gift.exchangeDetails': 'Butiran Pertukaran Hadiah',
  'gift.senderName': 'Nama Pengirim Hadiah',
  'gift.receiverName': 'Nama Penerima Hadiah',
  'gift.exchangeName': 'Namai Pertukaran Hadiah Anda',
  'gift.selectDate': 'Pilih Tarikh',
  'gift.budget': 'Bajet Hadiah',
  'gift.addNote': 'Tambah Nota',
  'gift.addGiftPhoto': 'Tambah Foto Hadiah',
  'gift.uploadSupport': 'Sokongan Fail PNG, JPG',
  'gift.sendGift': 'Hantar Hadiah',
  'gift.addGiftExchange': 'Tambah Pertukaran Hadiah',
  'gift.eventDetails': 'Butiran Acara',
  'gift.eventName': 'Nama Acara',
  'gift.festivalType': 'Jenis Perayaan',
  'gift.description': 'Penerangan',
  'gift.scope': 'Skop',
  'gift.deadlines': 'Tarikh Akhir',
  'gift.signupDeadline': 'Tarikh Akhir Mendaftar',
  'gift.drawDeadline': 'Tarikh Akhir Sertai',
  'gift.giftDeadline': 'Tarikh Akhir Hadiah',
  'gift.budgetPreference': 'Bajet dan Keutamaan',
  'gift.budgetRange': 'Julat Bajet: ₹@value',
  'gift.preferredGiftType': 'Jenis Hadiah Pilihan',
  'gift.anonymity': 'Tanpa Nama',
  'gift.anonymitySub': 'Pastikan Peserta Kekal Rahsia',
  'gift.createExchange': 'Cipta Pertukaran Hadiah',
  'gift.swapTitle': 'Pertukaran Hadiah',
  'gift.yourName': 'Nama Anda',
  'gift.addFriendName': 'Tambah Nama Kawan',
  'gift.friendName': 'Nama Kawan',
  'gift.addMore': '+ Tambah Lagi',
  'gift.draw': 'Sertai',
  'giftSwap.eventDashboard': 'Papan Pemuka Acara',
  'giftSwap.budgetDate': 'Belanjawan: @amount • @date',
  'giftSwap.drawResults': 'Keputusan Cabutan',
  'giftSwap.reshuffle': 'Rombak',
  'giftSwap.reshuffleMsg': 'Menyusun semula pasangan berdasarkan sekatan...',
  'giftSwap.adminViewOnly': 'Hanya anda (Pentadbir) boleh melihat siapa yang mencabut siapa.',
  'giftSwap.backToHome': 'Kembali ke Skrin Utama',
  'gift.selectParticipant': 'Pilih',
  'gift.selectParticipantsTitle': 'Pilih Peserta',
  'gift.done': 'Selesai',

  // ===================================
  // Checkout & Order History
  // ===================================
  'checkout.title': 'Semakan',
  'checkout.selectedProduct': 'Produk Terpilih',
  'checkout.shippingAddress': 'Alamat Penghantaran',
  'checkout.addressName': 'Rumah',
  'checkout.addressDetail': 'Berhampiran Pejabat Pos, velnath chowk, Junagadh',
  'checkout.paymentMethod': 'Kaedah Pembayaran',
  'checkout.payment.card': 'Kad Kredit/Debit',
  'checkout.payment.upi': 'UPI',
  'checkout.payment.netbanking': 'Perbankan Bersih',
  'checkout.applyRewards': 'Guna Ganjaran',
  'checkout.applyKcc': 'Guna Syiling KCC',
  'checkout.apply': 'Guna',
  'checkout.youHaveKcc': 'Anda Mempunyai {count} Syiling KCC',
  'checkout.billDetails': 'Butiran Bil',
  'checkout.subtotal': 'Jumlah Kecil',
  'checkout.shippingFee': 'Yuran Penghantaran',
  'checkout.tax': 'Cukai ({percent}%)',
  'checkout.totalAmount': 'Jumlah Total',
  'checkout.total': 'JUMLAH',
  'checkout.placeOrder': 'Buat Pesanan',
  'checkout.proceedingSnackbar': 'Mengalihkan ke pembayaran...',
  'checkout.emptyCartSnackbar': 'Tambahkan beberapa item terlebih dahulu!',
  'trackOrder.title': 'Jejak Pesanan',
  'trackOrder.orderId': 'ID Pesanan',
  'trackOrder.expectedDelivery': 'Jangkaan Penghantaran',
  'trackOrder.trackingHistory': 'Sejarah Jejaki',
  'trackOrder.stepPlaced': 'Pesanan Dibuat',
  'trackOrder.stepPayment': 'Pembayaran Disahkan',
  'trackOrder.stepShipped': 'Pesanan Dihantar',
  'trackOrder.stepOutForDelivery': 'Dalam Perjalanan',
  'trackOrder.stepDelivered': 'Dihantar',
  'trackOrder.expectedToday': 'Dijangka Hari Ini',
  'trackOrder.pending': 'Menunggu',

  // ===================================
  // Invoice Screen
  // ===================================
  'invoice.title': 'Invois',
  'invoice.downloadingTitle': 'Muat Turun',
  'invoice.downloadingMsg': 'PDF Invois sedang dimuat turun...',
  'invoice.taxInvoice': 'Invois Cukai / Bil Bekalan',
  'invoice.orderId': 'ID Pesanan',
  'invoice.orderDate': 'Tarikh Pesanan',
  'invoice.paymentMode': 'Mod Pembayaran',
  'invoice.status': 'Status',
  'invoice.paid': 'Telah Dibayar',
  'invoice.shippingDetails': 'Butiran Penghantaran',
  'invoice.orderSummary': 'Ringkasan Pesanan',
  'invoice.shippingFee': 'Bayaran Penghantaran',
  'invoice.tax': 'Cukai (10%)',
  'invoice.totalAmount': 'Jumlah Keseluruhan',
  'invoice.downloadPdf': 'Muat Turun PDF',

  // ===================================
  // Scanner Screen
  // ===================================
  'scanner.connect': 'Berhubung Dengan Orang Tersayang',
  'scanner.instruction': 'Masukkan Pautan Jemputan ATAU kod Untuk Menyertai\nRuang Keluarga Anda.',
  'scanner.inviteLinkLabel': 'Pautan Jemputan',
  'scanner.inviteLinkHint': 'https://family.app/join/....',
  'scanner.joinBtn': 'Sertai Ruang',
  'scanner.myLink': 'Pautan Saya',
  'scanner.copiedTitle': 'Pautan Disalin',
  'scanner.copiedMsg': 'Pautan anda telah disalin ke papan keratan.',
  'scanner.or': 'ATAU',
  'scanner.shareBtn': 'Kongsi Kod QR',
  'scanner.shareText': 'Hai! Sertai ruang keluarga saya di Kincore menggunakan pautan saya: @link',
  'scanner.shareSubject': 'Sertai Ruang Keluarga saya di Kincore',
  'scanner.askAdmin': 'Minta Pentadbir keluarga untuk Menunjukkan kepada anda Kod QR\nmereka Dari Tetapan Profil Mereka.',

  // ===================================
  // Cart
  // ===================================
  'cart.title': 'Troli Saya',
  'cart.empty': 'Troli anda kosong',
  'cart.buyNow': 'Beli Sekarang',
  'cart.remove': 'Buang',

  // ===================================
  // Order History
  // ===================================
  'orderHistory.title': 'Sejarah Pesanan',
  'orderHistory.searchHint': 'Cari mengikut ID pesanan atau produk',
  'orderHistory.netQty': 'Kuantiti Bersih. 1',
  'orderHistory.trackOrder': 'Jejak Pesanan',
  'orderHistory.status.shipped': 'Dihantar',
  'orderHistory.status.current': 'Semasa',
  'orderHistory.status.ago': '2 hari yang lalu',

  // ===================================
  // Security & Privacy
  // ===================================
  'security.title': 'Keselamatan dan Kunci',
  'security.lockProfile': 'Kunci Profil',
  'security.lockProfileSub': 'Hanya ahli keluarga yang disahkan boleh melihat foto dan siaran anda di garis masa anda.',
  'security.searchVisibility': 'Keterlihatan Carian',
  'security.visibility.everyone': 'Semua Orang',
  'security.visibility.friends': 'Kawan-kawan Kawan',
  'security.visibility.family': 'Keluarga Sahaja',
  'security.contactPrivacy': 'Privasi Hubungi',
  'security.hideEmail': 'Sembunyikan E-mel',
  'security.hideEmailSub': 'Emel anda akan disembunyikan daripada semua orang kecuali anda.',
  'security.hidePhone': 'Sembunyikan Nombor Telefon',
  'security.hidePhoneSub': 'Nombor hubungan anda tidak akan dapat dilihat oleh pengguna lain.',
  'security.saveChanges': 'Simpan Perubahan',

  // ===================================
  // Kinship Calculator
  // ===================================
  'kinship.resultTitle': 'Hasil Hubungan',
  'kinship.path': 'Jalan',
  'kinship.details': 'Butiran',
  'kinship.meaning': 'Maksud',
  'kinship.meaningSub': 'Ibu kepada ibu seseorang.',
  'kinship.englishTerm': 'Istilah Bahasa Inggeris',
  'kinship.englishTermSub': 'Nenek dari pihak ibu',
  'kinship.newCalculation': 'Pengiraan Baru',
  'kinship.editPath': 'Edit Jalan',
  'kinship.pathTitle': 'Jalan Perhubungan',
  'kinship.selectPath': 'Pilih Jalan',
  'kinship.addNextStep': 'Tambah Langkah Seterusnya',
  'kinship.calculate': 'Kira Hubungan',

  // ===================================
  // Migration Map
  // ===================================
  'migration.mapTitle': 'Peta Migrasi',
  'migration.historyTitle': 'Sejarah Migrasi',
  'migration.findMember': 'Cari Ahli Keluarga',
  'migration.arrivalYear': 'Ketibaan: @year',
  'migration.reason': 'Sebab Migrasi',
  'migration.familyMemberCount': 'Ahli Keluarga (@count)',
  'migration.viewHistory': 'Lihat Sejarah Migrasi',
  'migration.timeline.familyMigration': 'Migrasi Keluarga Schmidt',
  'migration.timeline.from': 'Dari',
  'migration.timeline.to': 'Kepada',
  'migration.timeline.viewRoute': 'Lihat Rute',

  // ===================================
  // Claim Identity
  // ===================================
  'claim.title': 'Tuntut Identiti',
  'claim.description': 'Untuk Mengakses Data Keluarga Peribadi dan Menyumbang ke Pokok,\nSila Sahkan Identiti Anda dengan Selamat.',
  'claim.tab.verify': 'Sahkan Kod',
  'claim.tab.confirm': 'Sahkan',
  'claim.tab.submit': 'Hantar',
  'claim.inviteCode': 'Kod Jemputan',
  'claim.inviteCodeHint': 'Masukkan Kod Alfanumerik 8 Digit Dari Jemputan Anda.',
  'claim.profileMatch': 'PADANAN PROFIL DITEMUI',
  'claim.thisIsMe': 'Ya, Ini Saya',
  'claim.confirmProfile': 'Saya Mengesahkan Bahawa Data Profil Ini Tepat',
  'claim.verifyOwnership': 'Sahkan Pemilikan',
  'claim.emailHint': 'Masukkan Alamat E-mel Anda',
  'claim.govId': 'ID Kerajaan (Pilihan)',
  'claim.addGovId': 'Tambah Foto ID Kerajaan',
  'claim.submitClaim': 'Hantar Tuntutan',

  // ===================================
  // Request History
  // ===================================
  'requestHistory.title': 'Sejarah Permintaan',
  'requestHistory.thisMonth': 'Bulan Ini',
  'requestHistory.birthdateUpdate': 'Kemaskini Tarikh Lahir',

  // ===================================
  // Change Relationship
  // ===================================
  'changeRelationship.title': 'Tukar Perhubungan',
  'changeRelationship.add': 'Tambah',
  'changeRelationship.remove': 'Buang',
  'changeRelationship.detailTitle': 'Butiran Perhubungan',
  'changeRelationship.typeHint': 'Jenis hubungan',
  'changeRelationship.personHint': 'Pilih Orang Berkaitan',
  'changeRelationship.reasonHint': 'Sebab Perubahan (Diperlukan)',
  'changeRelationship.supportDocs': 'Dokumen Sokongan',
  'changeRelationship.security': 'Dokumen Anda Disimpan dengan Selamat dan Boleh Dilihat oleh Pentadbir Keluarga untuk Tujuan Pengesahan.',
  'changeRelationship.saveNext': 'Simpan dan Seterusnya',

  'All': 'Semua',
  'Pending': 'Menunggu',
  'Approved': 'Diluluskan',
  'Rejected': 'Ditolak',
};
