/// Malay (Bahasa Melayu) translations for Kincore app
/// Terjemahan dalam Bahasa Melayu
const Map<String, String> msMY_ = {
  /// ===================== COMMON & GENERAL =====================
  'app.name': 'Kincore',
  'btn.confirm': 'Sahkan',
  'btn.cancel': 'Batal',
  'btn.save': 'Simpan',
  'btn.delete': 'Padam',
  'btn.edit': 'Edit',
  'btn.next': 'Seterusnya',
  'btn.back': 'Kembali',
  'btn.submit': 'Hantar',
  'btn.skip': 'Langkau',
  'btn.done': 'Selesai',
  'btn.continue': 'Teruskan',
  'btn.clear': 'Kosongkan',
  'btn.upload': 'Muat Naik',
  'btn.view_all': 'Lihat Semua',
  'btn.no_stay': 'Tidak, Tinggal',
  'btn.yes_discard': 'Ya, Buang',
  'btn.approve': 'Luluskan',
  'btn.decline': 'Tolak',
  'msg.loading': 'Memuatkan...',
  'msg.error': 'Sesuatu berlaku salah',
  'msg.success': 'Berjaya!',
  'msg.confirm_action': 'Anda pasti?',

  /// ===================== LANGUAGE SELECTION =====================
  'lang.select_title': 'Pilih Bahasa Anda',
  'lang.select_desc': 'Pilih bahasa pilihan anda untuk memulakan.',
  'lang.confirm_btn': 'Sahkan Bahasa',
  'lang.english': 'English',
  'lang.chinese': '中文',
  'lang.spanish': 'Español',
  'lang.malay': 'Bahasa Melayu',
  'lang.japanese': '日本語',

  /// ===================== AUTHENTICATION =====================
  'auth.app_title': 'Kincore',
  'auth.app_tagline': 'Bersambung Dengan Akar Keluarga Anda!',
  'auth.welcome_back': 'Selamat Kembali!',
  'auth.form_desc': 'Masukkan butiran anda untuk log masuk atau buat akaun.',
  'auth.signup_tab': 'Daftar',
  'auth.login_tab': 'Log Masuk',
  'auth.email_label': 'Alamat E-mel',
  'auth.email_hint': 'abc@gmail.com',
  'auth.password_label': 'Kata Laluan',
  'auth.password_hint': '••••••••',
  'auth.confirm_password_label': 'Sahkan Kata Laluan',
  'auth.name_label': 'Nama Penuh',
  'auth.name_hint': 'Ahmad bin Rashid',
  'auth.phone_label': 'Nombor Telefon',
  'auth.phone_hint': 'Masukkan nombor telefon',
  'auth.terms_agreement': 'Saya setuju dengan Syarat dan Ketentuan',
  'auth.terms_desc':
      'Dengan mendaftar, anda menerima syarat dan dasar privasi kami.',
  'auth.forgot_password': 'Lupa Kata Laluan?',
  'auth.dont_have_account': 'Tidak ada akaun?',
  'auth.already_have_account': 'Sudah ada akaun?',
  'auth.signup_btn': 'Daftar',
  'auth.login_btn': 'Log Masuk',
  'auth.otp_verify': 'Sahkan OTP',
  'auth.resend_otp': 'Hantar Semula OTP',
  'auth.otp_sent': 'OTP telah dihantar ke e-mel anda',
  'auth.google' : 'Google',
  'auth.facebook' : 'Facebook',
  'auth.continue' : 'Or Continue With',


  /// ===================== SPLASH SCREEN =====================
  'splash.loading': 'Memuatkan pokok keluarga anda...',

  /// ===================== DASHBOARD & NAVIGATION =====================
  'nav.home': 'Laman Utama',
  'nav.family': 'Keluarga',
  'nav.events': 'Acara',
  'nav.feed': 'Suapan',
  'nav.profile': 'Profil',
  'nav.tree': 'Pokok',
  'nav.mall': 'Pusat Membeli-belah',
  'nav.memory': 'Kenangan',

  /// ===================== HOME SCREEN =====================
  'home.welcome': 'Selamat datang ke Pokok Keluarga Anda',
  'home.quick_actions': 'Tindakan Cepat',
  'home.recent_activity': 'Aktiviti Terbaru',
  'home.upcoming_events': 'Acara Akan Datang',
  'home.bio' : 'Family Bio',
  'home.secret_santa' : 'Secret Santa',
  'home.kinship_calc' : 'Kinship Calculator',
  'home.identity_Approval' : 'Identity Approval',
  'home.map' : "Migration Map",

  /// ===================== FAMILY MEMBERS =====================
  'family.add_member': 'Tambah Ahli Keluarga',
  'family.member_list': 'Ahli Keluarga',
  'family.total_members': 'Jumlah Ahli',
  'family.generations': 'Generasi',
  'family.first_name': 'Nama Pertama',
  'family.last_name': 'Nama Keluarga',
  'family.date_of_birth': 'Tarikh Lahir',
  'family.place_of_birth': 'Tempat Lahir',
  'family.gender': 'Jantina',
  'family.gender_male': 'Lelaki',
  'family.gender_female': 'Perempuan',
  'family.gender_other': 'Lain-lain',
  'family.living_status': 'Status Hidup',
  'family.is_alive': 'Adakah orang ini masih hidup?',
  'family.alive': 'Hidup',
  'family.deceased': 'Meninggal Dunia',
  'family.spouse_name': 'Nama Pasangan',
  'family.anniversary_date': 'Tarikh Ulang Tahun',
  'family.occupation': 'Pekerjaan',
  'family.current_location': 'Lokasi Semasa',
  'family.school_college': 'Sekolah & Kolej',
  'family.qualification': 'Kelayakan',
  'family.study_location': 'Lokasi Pengajian',
  'family.bio': 'Biografi',
  'family.add_location': 'Tambah',
  'family.relationship': 'Hubungan',
  'family.parent': 'Ibu Bapa',
  'family.child': 'Anak',
  'family.sibling': 'Adik Beradik',
  'family.spouse': 'Pasangan',
  'family.edit_member': 'Edit Ahli Keluarga',
  'family.delete_member': 'Padam Ahli',
  'family.confirm_delete': 'Adakah anda pasti ingin memadamkan ahli ini?',

  /// ===================== ADD CHILD SCREEN =====================
  'child.add_child': 'Tambah Anak',
  'child.select_parents': 'Pilih Ibu Bapa',
  'child.birth_details': 'Butiran Kelahiran',

  /// ===================== ADD PARENTS SCREEN =====================
  'parents.add_parents': 'Tambah Ibu Bapa',
  'parents.father': 'Bapa',
  'parents.mother': 'Ibu',

  /// ===================== EVENTS =====================
  'event.title': 'Acara',
  'event.create_event': 'Buat Acara',
  'event.family_events': 'Acara Keluarga',
  'event.event_name': 'Nama Acara',
  'event.event_date': 'Tarikh',
  'event.event_time': 'Masa',
  'event.event_location': 'Lokasi',
  'event.event_description': 'Penerangan',
  'event.event_type': 'Jenis Acara',
  'event.birthday': 'Hari Jadi',
  'event.anniversary': 'Ulang Tahun Perkahwinan',
  'event.wedding': 'Perkahwinan',
  'event.reunion': 'Perhimpunan Keluarga',
  'event.other': 'Lain-lain',
  'event.invite_guests': 'Jemput Tetamu',
  'event.rsvp': 'RSVP',
  'event.yes': 'Ya',
  'event.maybe': 'Mungkin',
  'event.no': 'Tidak',
  'event.rsvp_status': 'Status RSVP',
  'event.attending': 'Akan Hadir',
  'event.not_attending': 'Tidak Akan Hadir',
  'event.maybe_attending': 'Mungkin Akan Hadir',
  'event.view_details': 'Lihat Butiran',
  'event.edit_event': 'Edit Acara',
  'event.delete_event': 'Padam Acara',

  /// ===================== FEED SCREEN =====================
  'feed.title': 'Suapan Keluarga',
  'feed.create_post': 'Buat Pos',
  'feed.what_new': 'Apa yang baru?',
  'feed.share_moment': 'Kongsi momen dengan keluarga anda',
  'feed.post_content': 'Kandungan Pos',
  'feed.add_photo': 'Tambah Foto',
  'feed.add_video': 'Tambah Video',
  'feed.post': 'Pos',
  'feed.like': 'Suka',
  'feed.comment': 'Ulasan',
  'feed.share': 'Kongsi',
  'feed.edit_post': 'Edit Pos',
  'feed.delete_post': 'Padam Pos',
  'feed.repost_issue': 'Laporkan Isu',
  'feed.report_reason': 'Sebab Laporan',
  'feed.spam': 'Ia Spam',
  'feed.nudity': 'Ketelanjangan atau Aktiviti Seksual',
  'feed.hate_speech': 'Ucapan Kebencian atau Simbol',
  'feed.false_info': 'Maklumat Palsu',
  'feed.harassment': 'Gangguan atau Buli',
  'feed.something_else': 'Sesuatu yang lain',
  'feed.additional_details': 'Butiran Tambahan (Pilihan)',
  'feed.confirm_report': 'Adakah anda pasti ingin melaporkan pos ini?',

  /// ===================== MEMORY SCREEN =====================
  'memory.title': 'Kenangan',
  'memory.add_memory': 'Tambah Kenangan',
  'memory.upload_memory': 'Muat Naik Kenangan',
  'memory.memory_name': 'Nama Kenangan',
  'memory.memory_date': 'Tarikh',
  'memory.memory_description': 'Penerangan',
  'memory.photos': 'Foto',
  'memory.videos': 'Video',
  'memory.documents': 'Dokumen',
  'memory.select_tab': 'Pilih tab untuk muat naik fail',
  'memory.pick_files': 'Pilih Fail',
  'memory.no_files': 'Tiada fail dipilih',

  /// ===================== PROFILE SCREEN =====================
  'profile.title': 'Profil',
  'profile.edit_profile': 'Edit Profil',
  'profile.view_profile': 'Lihat Profil',
  'profile.my_profile': 'Profil Saya',
  'profile.settings': 'Tetapan',
  'profile.change_password': 'Tukar Kata Laluan',
  'profile.privacy_settings': 'Tetapan Privasi',
  'profile.notifications': 'Pemberitahuan',
  'profile.help': 'Bantuan & Sokongan',
  'profile.about': 'Tentang',
  'profile.logout': 'Log Keluar',
  'profile.confirm_logout': 'Adakah anda pasti ingin log keluar?',
  'profile.joined': 'Sertai pada',
  'profile.family_role': 'Peranan Keluarga',
  'profile.stats': 'Statistik',

  /// ===================== K-MALL SCREEN =====================
  'mall.title': 'K-Pusat Membeli-belah',
  'mall.coins_balance': 'Baki Syiling',
  'mall.redeem_coins': 'Tukar Syiling',
  'mall.categories': 'Kategori',
  'mall.featured': 'Dipaparkan',
  'mall.on_sale': 'Dalam Jualan',
  'mall.my_purchases': 'Pembelian Saya',
  'mall.add_to_cart': 'Tambah ke Troli',
  'mall.buy_now': 'Beli Sekarang',
  'mall.price': 'Harga',
  'mall.coins': 'Syiling',
  'mall.no_items': 'Tiada item tersedia',

  /// ===================== REDEEM COINS =====================
  'redeem.title': 'Tukar Syiling',
  'redeem.available_coins': 'Syiling Tersedia',
  'redeem.redeem_options': 'Pilihan Pertukaran',
  'redeem.gift_cards': 'Kad Hadiah',
  'redeem.cash_back': 'Pulangan Tunai',
  'redeem.vouchers': 'Baucar',
  'redeem.discount_codes': 'Kod Diskaun',
  'redeem.enter_amount': 'Masukkan Jumlah',
  'redeem.confirm_redeem': 'Sahkan Pertukaran',
  'redeem.success': 'Ditukar dengan berjaya!',
  'redeem.failed': 'Pertukaran gagal',

  /// ===================== TREE VIEW =====================
  'tree.title': 'Pokok Keluarga',
  'tree.tree_view': 'Kandungan Pokok Keluarga Web',
  'tree.generation_count': 'Generasi / Ahli',
  'tree.zoom_in': 'Zum Masuk',
  'tree.zoom_out': 'Zum Keluar',
  'tree.reset_zoom': 'Tetap Semula Zum',
  'tree.search_member': 'Cari ahli keluarga...',

  /// ===================== SWITCH SPACE =====================
  'space.title': 'Tukar Ruang',
  'space.family_spaces': 'Ruang Keluarga',
  'space.active_space': 'Ruang Aktif',
  'space.create_space': 'Buat Ruang Baru',
  'space.space_name': 'Nama Ruang',
  'space.current_space' : 'Current Space',
  'space.other_space' : 'Other Space',
  'space.confirm' : 'Confirm Switch',
  'space.switched' : 'Space Switched',
  'space.members': 'Ahli',
  'space.invite_family': 'Jemput Ahli Keluarga',

  /// ===================== ROLE SELECTION =====================
  'role.title': 'Pilih Peranan Anda',
  'role.select_role': 'Apakah peranan anda dalam keluarga?',
  'role.grandparent': 'Datuk/Nenek',
  'role.parent': 'Ibu Bapa',
  'role.adult': 'Dewasa',
  'role.teenager': 'Remaja',
  'role.child': 'Kanak-kanak',

  /// ===================== VALIDATION & ERRORS =====================
  'error.required_field': 'Medan ini diperlukan',
  'error.invalid_email': 'Sila masukkan e-mel yang sah',
  'error.password_mismatch': 'Kata laluan tidak sama',
  'error.weak_password': 'Kata laluan terlalu lemah',
  'error.network_error': 'Ralat rangkaian. Sila periksa sambungan anda.',
  'error.server_error': 'Ralat pelayan. Sila cuba lagi kemudian.',
  'error.invalid_input': 'Input tidak sah',
  'error.file_too_large': 'Fail terlalu besar',
  'error.unsupported_format': 'Format fail tidak disokong',

  /// ===================== SUCCESS MESSAGES =====================
  'success.profile_updated': 'Profil dikemas kini dengan berjaya',
  'success.member_added': 'Ahli keluarga ditambah dengan berjaya',
  'success.member_updated': 'Ahli keluarga dikemas kini dengan berjaya',
  'success.member_deleted': 'Ahli keluarga dipadamkan',
  'success.event_created': 'Acara dibuat dengan berjaya',
  'success.post_created': 'Pos dibuat dengan berjaya',
  'success.memory_added': 'Kenangan ditambah dengan berjaya',
  'success.saved': 'Disimpan dengan berjaya',
  'success.deleted': 'Dipadamkan dengan berjaya',

  /// ===================== HINTS & PLACEHOLDERS =====================
  'hint.search': 'Cari...',
  'hint.enter_name': 'Masukkan nama penuh',
  'hint.enter_email': 'Masukkan e-mel anda',
  'hint.enter_password': 'Masukkan kata laluan',
  'hint.select_date': 'MM/DD/YYYY',
  'hint.add_location': 'Tambah lokasi',
  'hint.write_comment': 'Tulis ulasan...',
  'hint.write_message': 'Tulis mesej...',


  /// ===================== SCANNER / JOIN SPACE =====================

  'scanner.title': 'Connect With Loved Ones',
  'scanner.subtitle':
  'Enter an invite link or code to join\nyour family\'s space.',

  'scanner.invite_link.label': 'Invite Link',
  'scanner.invite_link.hint': 'https://family.app/join/....',

  'scanner.join_space': 'Join Space',
  'scanner.or': 'OR',

  'scanner.share_qr': 'Share QR Code',

  'scanner.footer':
  'Ask a family admin to show you their QR\ncode from their profile settings.',


  ///=================coins=============================

  'coin.total_balance' : 'TOTAL BALANCE',
  'coin.redeem_coin' : 'Redeem Coins',
};
