// lib/localization/zh_CN.dart
// Simplified Chinese translations for Kincore app

const Map<String, String> zhCN = {
  // ===================================
  // Common & General
  // ===================================
  'common.add': '添加',
  'common.save': '保存',
  'common.cancel': '取消',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.viewAll': '全部查看',
  'common.select': '选择',
  'common.search': '搜索',
  'common.find': '查找',
  'common.publish': '发布',
  'common.saveAndAdd': '保存并添加',
  'common.upload': '上传',
  'common.addFile': '添加文件',
  'common.savePhotos': '保存照片',
  'common.saveMemory': '保存记忆',
  'common.loading': '加载中...',
  'common.error': '出现错误，请重试。',
  'common.success': '成功',
  'common.productPublished': '产品发布成功！',
  'common.yes': '是',
  'common.no': '否',
  'common.maybe': '也许',
  'common.select_country': '选择国家',
  'common.submit': '提交',
  'common.done': '完成',
  'common.next': '下一步',
  'common.continue': '继续',
  'common.all': '全部',
  'common.seeAll': '查看全部',
  'common.father': '父亲',
  'common.mother': '母亲',
  'common.sister': '姐妹',
  'common.brother': '兄弟',
  'common.approved': '已批准',

  // ===================================
  // Auth Screen
  // ===================================
  'auth.kincore': 'Kincore',
  'auth.connect': '连接到你的根源！',
  'auth.welcomeBack': '欢迎回来！',
  'auth.detailsPrompt': '输入您的详细信息以登录或创建帐户。',
  'auth.signUp': '注册',
  'auth.logIn': '登录',
  'auth.nameLabel': '输入您的姓名',
  'auth.nameHint': '名字 姓氏',
  'auth.emailLabel': '电子邮件地址',
  'auth.emailHint': 'abc@gmail.com',
  'auth.passwordLabel': '密码',
  'auth.passwordHint': '••••••••',
  'auth.confirmPasswordLabel': '确认密码',
  'auth.forgotPassword': '忘记密码？',
  'auth.continueWith': '或继续使用',
  'auth.google': 'Google',
  'auth.facebook': 'Facebook',
  'auth.back': '返回',
  'auth.firstName': '名字',
  'auth.firstNameHint': '约翰 (John)',
  'auth.lastName': '姓氏',
  'auth.lastNameHint': '多伊 (Doe)',
  'auth.dob': '出生日期（可选）',
  'auth.dobHint': '日/月/年 (DD/MM/YYYY)',
  'auth.forgotPasswordTitle': '忘记密码',
  'auth.forgotPasswordHeading': '忘记密码？',
  'auth.forgotPasswordDesc': '别担心！这很正常。请输入与您的帐户关联的电子邮件地址。',
  'auth.enterEmail': '输入您的电子邮件',
  'auth.sending': '发送中...',
  'auth.sendCode': '发送验证码',
  'profile.logoutTitle': '登出',
  'profile.logoutSuccessMsg': '已成功登出',

  // ===================================
  // Home Screen
  // ===================================
  'home.title': '首页',
  'home.goodMorning': '早上好',
  'home.upcomingBirthdays': '即将到来的生日',
  'home.viewCalendar': '查看日历',
  'home.timeline': '时间轴',
  'home.startBuilding': '开始构建您的家族树',
  'home.startBuildingDesc': '添加家族成员，见证您的遗产增长。',
  'home.addFirstMember': '添加第一个成员',
  'home.recentMemories': '最近的记忆',
  'home.noMemories': '未找到最近的记忆。',
  'home.addFirstMemory': '添加您的第一个记忆',
  'home.upcomingEvents': '即将到来的事件',
  'home.noEvents': '没有即将到来的事件。',
  'home.familyEvents': '家庭活动',
  'home.familyBio': '家族传记',
  'home.secretSanta': '秘密圣诞老人',
  'home.kinshipCalculator': '亲属关系计算器',
  'home.identityApproval': '身份批准',
  'home.migrationMap': '迁移地图',
  'home.quickModules': '快捷模块',
  'home.calculator': '计算器',
  'home.giftSwap': '礼物交换',
  'home.savedFeed': '已保存的动态',
  'home.exploreMore': '探索更多',
  'home.marketplace': '商城',
  'home.reels': '短视频',

  // ===================================
  // Navigation
  // ===================================
  'nav.home': '首页',
  'nav.feed': '动态',
  'nav.tree': '树',
  'nav.mall': '商城',
  'nav.profile': '个人资料',
  'nav.memory': '记忆',
  'nav.family': '家族',
  'nav.events': '事件',

  // ===================================
  // Tree Screen
  // ===================================
  'tree.title': '哈里森一族',
  'tree.generations': '@count 代 / @members 成员',
  'tree.webContentView': '网页内容视图',
  'tree.allView': '全部视图',
  'tree.directLinage': '直系血亲',
  'tree.birthday': '生日',
  'tree.anniversary': '纪念日',

  // ===================================
  // Family Bio Screen
  // ===================================
  'familyBio.addTitle': '添加家族传记',
  'familyBio.addMedia': '添加媒体',
  'familyBio.dragAndDrop': '拖放或浏览以上传',
  'familyBio.basicInfo': '基本信息',
  'familyBio.storyName': '故事名称',
  'familyBio.location': '位置',
  'familyBio.birthDate': '出生日期',
  'familyBio.selectDate': '选择日期',
  'familyBio.storyBio': '故事（传记）',
  'familyBio.addBioHint': '在这里添加传记...',
  'familyBio.publishBio': '发布传记',
  'familyBio.title': '家族传记',
  'familyBio.gallery': '画廊',
  'familyBio.nextInHistory': '历史中的下一个',
  'familyBio.existingMember': '现有家族成员',
  'familyBio.theRoaringTwenties': '咆哮的二十年代',
  'familyBio.roaringTwentiesDate': '1920 - 1929',
  'familyBio.migrationStoryDate': '1920年11月4日 · 西西里到纽约',
  'familyBio.migrationStoryContent': '大迁移是历史上的关键时刻，数百万人踏上寻求机会和新生活的旅程。其中包括来自西西里的年轻女性玛丽亚·罗西，她于1920年启航前往纽约。她的故事和许多其他故事一样，是勇气、韧性和永恒人类精神的见证。',
  'familyBio.migrationStoryQuote': '"这段旅程很长很艰难，但对美好生活的希望支撑我们前进。" – 玛丽亚·罗西',
  'familyBio.errorTitle': '错误',
  'familyBio.nameRequired': '故事名称是必填项',
  'familyBio.successTitle': '成功',
  'familyBio.publishedMsg': '传记已发布！',

  // ===================================
  // Market Place
  // ===================================
  'marketplace.title': '商城',
  'marketplace.searchHint': '搜索产品、类别...',
  'marketplace.bannerTitle': '夏季特卖进行中！',
  'marketplace.bannerSub': '发现您附近的最佳优惠。',
  'marketplace.noProducts': '未找到产品！',
  'marketplace.catAll': '全部',
  'marketplace.catVehicles': '车辆',
  'marketplace.catProperty': '房产',
  'marketplace.catElectronics': '电子产品',
  'marketplace.catFurniture': '家具',
  'marketplace.catFashion': '时尚',
  'marketplace.msgAvailable': '你好，这个还在吗？',
  'marketplace.timeJustNow': '刚刚',
  'marketplace.timeYesterday': '昨天',
  'marketplace.messages': '消息',
  'marketplace.noMessages': '暂无消息。',

  // ===================================
  // Add Family Member Screens
  // ===================================
  'addMember.title': '添加家族成员',
  'addMember.basicInfo': '基本信息',
  'addMember.firstName': '名字',
  'addMember.lastName': '姓氏',
  'addMember.gender': '性别',
  'addMember.male': '男性',
  'addMember.female': '女性',
  'addMember.other': '其他',
  'addMember.dateOfBirth': '出生日期',
  'addMember.dateFormatHint': 'MM/DD/YYYY',
  'addMember.relationshipSetup': '关系设置',
  'addMember.relationshipType': '关系类型',
  'addMember.relationship.spouse': '配偶',
  'addMember.relationship.sibling': '兄弟姐妹',
  'addMember.relationship.parent': '父母',
  'addMember.findFamilyMember': '查找家族成员',
  'addMember.spouseName': '配偶名称',
  'addMember.anniversaryDate': '周年纪念日',
  'addMember.additionalDetail': '额外详情',
  'addMember.addLocation': '添加位置',
  'addMember.occupation': '职业',
  'addMember.bioNotes': '传记/笔记',
  'addMember.privacyVisibility': '隐私和可见性',
  'addMember.visibleToAll': '对所有成员可见',
  'addMember.addParentsTitle': '添加父母',
  'addMember.addOtherMember': '添加其他家族成员',
  'addMember.placeOfBirth': '出生地',
  'addMember.currentLocation': '当前位置',
  'addMember.addChildTitle': '添加孩子',
  'addMember.schoolAndCollege': '学校和大学',
  'addMember.qualification': '资格',
  'addMember.studyLocation': '学习地点',
  'addMember.changePhoto': '更改照片',
  'addMember.livingStatus': '生活状况',
  'addMember.isAlive': '此人仍然活着吗？',
  'addMember.alive': '活着',
  'addMember.deceased': '已故',
  'addMember.phoneNumber': '电话号码',
  'addMember.phoneHint': '00000 00000',

  // ===================================
  // Memory Screen
  // ===================================
  'memory.title': '记忆',
  'memory.addTitle': '添加记忆',
  'memory.tabAll': '全部',
  'memory.tabPhotos': '照片',
  'memory.tabVideos': '视频',
  'memory.addMemoryPhotos': '添加记忆照片',
  'memory.addMemoryVideos': '添加记忆视频',
  'memory.uploadSupport': '支持 PNG、JPG 文件',

  // ===================================
  // K-Mall & Products
  // ===================================
  'mall.title': '商城',
  'mall.searchHint': '查找产品',
  'mall.filter': '筛选',
  'mall.categories': '分类',
  'mall.featured': '精选',
  'mall.mostPopular': '最受欢迎',
  'mall.onSale': '在售',
  'mall.wishlistTitle': '我的心愿单',
  'mall.noItemsWishlist': '您的心愿单是空的！',
  'mall.exploreProducts': '浏览产品',
  'mall.productDetails': '产品详情',
  'mall.description': '描述',
  'mall.selectSize': '选择尺寸',
  'mall.selectColor': '选择颜色',
  'mall.quantity': '数量',
  'mall.addToCart': '加入购物车',
  'mall.buyNow': '立即购买',
  'mall.reviews': '评论',
  'mall.noReviews': '此产品还没有评论。',
  'mall.sellerInfo': '卖家信息',
  'mall.viewShop': '查看商店',
  'mall.relatedProducts': '相关产品',
  'mall.addedToCart': '@productName 已添加到购物车',
  'mall.filterPrice': '价格范围',
  'mall.filterColor': '颜色',
  'mall.filterGender': '性别',
  'mall.category.fashion': '时尚',
  'mall.category.electronics': '电子产品',
  'mall.category.appliances': '电器',
  'mall.category.beauty': '美容',
  'mall.category.furniture': '家具',
  'mall.banner.title': '新系列',
  'mall.banner.discount': '五折优惠',
  'mall.banner.for': '儿童专用',
  'mall.productReview': '@rating （@count 条评论）',
  'mall.tag.homeMade': '手工制作',
  'mall.tag.newCollection': '新系列',

  // ===================================
  // Add Product
  // ===================================
  'addProduct.title': '添加新产品',
  'addProduct.detailsPrompt': '输入所有详情以列出您的产品',
  'addProduct.uploadImagesTitle': '上传产品图像',
  'addProduct.uploadImagesDesc': '使用清晰、高分辨率的图像。第一张图像将是封面。',
  'addProduct.addMedia': '添加媒体',
  'addProduct.dragAndDrop': '拖放或浏览以上传',
  'addProduct.basicInfo': '基本信息',
  'addProduct.productNameLabel': '产品名称（必需）',
  'addProduct.priceLabel': '价格',
  'addProduct.discountLabel': '折扣%',
  'addProduct.descriptionLabel': '描述',
  'addProduct.sizeLabel': '尺寸',
  'addProduct.conditionsLabel': '条件',
  'addProduct.brandNameLabel': '品牌名称',
  'addProduct.profileLabel': '选择您的个人资料',
  'addProduct.categoryLabel': '分类',
  'addProduct.subCategoryLabel': '子分类',
  'addProduct.quantityLabel': '数量',
  'addProduct.publishButton': '发布产品',

  // ===================================
  // Redeem Coin Screen
  // ===================================
  'redeem.title': '兑换 KCC 硬币',
  'redeem.totalBalance': '总余额',
  'redeem.kccBalance': 'KCC 余额',
  'redeem.currency': 'KCC',
  'redeem.waysToRedeem': '兑换方式',
  'redeem.waysToEarn': '赚取方式',
  'redeem.recentActivity': '最近活动',
  'redeem.vintageCase': '复古箱',
  'redeem.kmallPurchase': '商城购买',
  'redeem.redeemedKcc': '-455 KCC',
  'redeem.shopAndSave': '购物并节省',
  'redeem.redeemForCash': '兑现',
  'redeem.shopNow': '立即购物',
  'redeem.redeemNow': '立即兑换',
  'redeem.option.shop.title': '商城购物',
  'redeem.option.shop.description': '使用硬币购买独家家族遗产产品。',
  'redeem.option.shop.button': '浏览商城',
  'redeem.option.support.title': '支持家族',
  'redeem.option.support.description': '转账硬币以支持亲戚。',
  'redeem.option.support.button': '送礼',
  'redeem.option.boost.title': '提升列表',
  'redeem.option.boost.description': '推广您的产品以获得更高的销售。',
  'redeem.option.boost.button': '立即推广',
  'redeem.featuredRewards': '精选奖励',
  'redeem.completeProfile': '完善您的个人资料',
  'redeem.earnKcc': '赚取 @points KCC',

  // ===================================
  // Coin Card Level
  // ===================================
  'profile.levelBadge': '等级 @level @title',

  // ===================================
  // Earn
  // ===================================
  'earn.referral': '邀请朋友',
  'earn.referralSub': '赚取 20 KCC',
  'earn.completeProfile.title': '完成您的个人资料',
  'earn.completeProfile.subtitle': '赚取 60KCC',
  'earn.addPhoto.title': '添加家族照片',
  'earn.addPhoto.subtitle': '赚取 20KCC',
  'earn.inviteMember.title': '邀请家族成员',
  'earn.inviteMember.subtitle': '赚取 20KCC',
  'earn.attendEvent.title': '参加家族活动',
  'earn.attendEvent.subtitle': '赚取 45KCC',

  // ===================================
  // Create Event Screen
  // ===================================
  'createEvent.title': '创建事件',
  'createEvent.saveDraft': '保存',
  'createEvent.addCoverPhoto': '添加封面照片',
  'createEvent.uploadSupport': '上传 PNG、JPG 文件',
  'createEvent.detailTitle': '活动详情',
  'createEvent.eventTitleLabel': '事件标题',
  'createEvent.eventTitleHint': '输入标题',
  'createEvent.locationLabel': '位置',
  'createEvent.locationHint': '输入地址位置',
  'createEvent.descriptionLabel': '描述',
  'createEvent.descriptionHint': '在这里写...',
  'createEvent.startDateLabel': '开始日期',
  'createEvent.endDateLabel': '结束日期',
  'createEvent.timeLabel': '时间',
  'createEvent.timeHint': '输入时间',
  'createEvent.inviteMemberTitle': '邀请家族成员',
  'createEvent.starts': '开始',
  'createEvent.ends': '结束',
  'createEvent.requestRSVP': '请求回复 (RSVP)',
  'createEvent.requestRSVPSub': '客人必须确认出席',
  'createEvent.sendReminders': '发送提醒',
  'createEvent.sendRemindersSub': '提前 1 天通知客人',
  'createEvent.includeGiftExchange': '包括礼物交换',
  'createEvent.includeGiftExchangeSub': '例如：神秘圣诞老人或礼物交换',
  'createEvent.nextAddGift': '下一步并添加礼物',
  'createEvent.createEventBtn': '创建活动',
  'createEvent.eventCreatedTitle': '活动已创建',
  'createEvent.eventCreatedMsg': '您的活动已成功创建！',

  // ===================================
  // Feed & Posts
  // ===================================
  'feed.title': '家族动态',
  'feed.myStory': '我的故事',
  'feed.whatsHappening': '发生了什么？',
  'feed.createPost': '创建帖子',
  'feed.archive': '存档',
  'feed.writeCommentHint': '写一条评论...',
  'feed.viewComments': '查看所有 @count 条评论',
  'feed.postAnonymously': '匿名发布',
  'feed.allowComments': '允许评论',
  'feed.saveToDevice': '保存到设备',
  'feed.reportPost': '举报帖子',
  'feed.archiveMenu': '归档',
  'feed.reportMenu': '举报',
  'feed.archiveMsg': '帖子已添加到您的归档中。',
  'feed.savedTitle': '已保存',
  'feed.savedMsg': '帖子已保存到您的收藏夹。',
  'feed.removedTitle': '已移除',
  'feed.removedMsg': '帖子已从保存中移除。',
  'feed.caughtUp': '您已看完所有动态！',
  'feed.findMore': '查找更多家庭成员',
  'feed.writeComment': '写评论...',
  'createPost.successTitle': '成功',
  'createPost.successMsg': '帖子创建成功！',
  'createPost.errorTitle': '错误',
  'createPost.errorMsg': '请输入一些文本或添加媒体。',
  'feed.savedCollection': '已保存的收藏',
  'feed.noSavedPosts': '暂无保存的帖子',
  'feed.removeFromCollection': '从收藏中移除',

  // ===================================
  // Post Settings
  // ===================================
  'postSettings.title': '帖子设置',
  'postSettings.postSettings': '帖子设置',
  'postSettings.whoCanSee': '谁能看到您的帖子？',
  'postSettings.visibility.public': '公开',
  'postSettings.visibility.friends': '朋友',
  'postSettings.visibility.friendsExcept': '除了朋友',
  'postSettings.visibility.specificFriends': '特定朋友',
  'postSettings.whoCanComment': '谁可以对此帖子进行评论？',
  'postSettings.comments.followersOnly': '仅您的粉丝',
  'postSettings.comments.friends': '朋友',
  'postSettings.comments.chosenFriends': '选定的朋友',
  'postSettings.saveChanges': '保存更改',

  // ===================================
  // Create Post
  // ===================================
  'createPost.title': '创建帖子',
  'createPost.hint': '你想说什么？',
  'createPost.addMedia': '添加媒体',
  'createPost.tagPeople': '标记人物',
  'createPost.postButton': '发布',

  // ===================================
  // Report
  // ===================================
  'report.title': '举报问题',
  'report.anonymousHelp': '您的举报是匿名的。通过告诉我们发生了什么，帮助我们保持家族树社区的安全。',
  'report.reasonTitle': '举报原因',
  'report.spam': '这是垃圾邮件',
  'report.nudity': '色情或性活动',
  'report.hateSpeech': '仇恨言论或符号',
  'report.falseInfo': '虚假信息',
  'report.harassment': '骚扰或欺凌',
  'report.other': '其他',
  'report.additionalDetails': '其他详情（可选）',
  'report.describeIssue': '请描述问题以帮助我们审核',
  'report.submitReport': '提交举报',
  'report.dialog.discardTitle': '放弃举报？',
  'report.dialog.discardBody': '您确定要取消此举报吗？您的进度将丢失。',
  'report.dialog.stay': '否，保留',
  'report.dialog.discard': '是，放弃',

  // ===================================
  // Seller Dashboard
  // ===================================
  'seller.title': '仪表板',
  'seller.overview': '概述',
  'seller.totalRevenue': '总收入',
  'seller.orders': '订单',
  'seller.avgOrderValue': '平均订单价值',
  'seller.products': '产品',
  'seller.topProducts': '热门产品',
  'seller.recentOrders': '最近订单',
  'seller.orderId': '订单',
  'seller.noProducts': '没有要显示的产品。',
  'seller.noOrders': '没有最近的订单。',
  'seller.noData': '没有可用数据',

  // ===================================
  // Profile & Settings
  // ===================================
  'profile.title': '我的个人资料',
  'profile.followers': '粉丝',
  'profile.following': '关注',
  'profile.editProfile': '编辑个人资料',
  'profile.addMember': '添加成员',
  'profile.addMemory': '添加记忆',
  'profile.vitalStats': '基本统计',
  'profile.stat.fullName': '全名',
  'profile.stat.born': '出生',
  'profile.stat.location': '位置',
  'profile.stat.occupation': '职业',
  'profile.familyMember': '家族成员',
  'profile.keyLifeEvents': '关键人生事件',
  'profile.viewMoreTimeline': '查看更多时间轴',
  'profile.memories': '记忆',
  'profile.shareProfile': '分享个人资料',
  'profile.personal': '个人',
  'profile.business': '商业',
  'profile.posts': '帖子',
  'profile.photos': '照片',
  'profile.videos': '视频',
  'profile.tagged': '被标记',
  'profile.myProfile': '我的个人资料',
  'profile.sellerDashboard': '卖家控制台',
  'profile.identityApproval': '身份批准',
  'profile.redeemCoins': '兑换硬币',
  'profile.settings': '设置',
  'profile.logout': '登出',
  'profile.logoutConfirm': '您确定要登出吗？',
  'profile.personalProfile': '个人资料',
  'profile.roleAccess': '您的角色和权限',
  'profile.viewDashboard': '查看我的卖家仪表板',
  'profile.addProduct': '添加产品',
  'profile.account': '账户',
  'profile.personalInfo': '个人信息',
  'profile.personalInfoSub': '名字、电子邮件、电话号码',
  'profile.privacy': '隐私和安全',
  'profile.privacySub': '家族树可见性、密码',
  'profile.notifications': '通知',
  'profile.notificationsSub': '事件、更新、消息',
  'profile.darkMode': '深色模式',
  'profile.darkModeSub': '切换应用程序主题',
  'profile.myOrders': '我的订单',
  'profile.myOrdersSub': '订单历史、退货',
  'profile.myListings': '我的列表',
  'profile.myListingsSub': '出售管理',
  'profile.privacyLocked': '隐私：已锁定',
  'profile.privacyUnlocked': '隐私：未锁定',
  'profile.message': '留言',
  'profile.viewFeed': '查看动态',
  'profile.viewStory': '查看故事',
  'profile.viewProfilePic': '查看头像',
  'profile.viewUserFeed': '查看用户动态',
  'profile.privacyLockedTitle': '隐私已锁定 🔒',
  'profile.privacyUnlockedTitle': '隐私已解锁 🔓',
  'profile.privacyLockedMsg': '您的个人资料现在是私密的。',
  'profile.privacyUnlockedMsg': '您的个人资料现在对他人可见。',
  'profile.requestHistory': '请求历史',
  'profile.requestHistorySub': '查看您的请求历史',
  'profile.saveFeed': '已保存动态',
  'profile.saveFeedSub': '已保存动态收藏',
  'profile.giftSwap': '礼物交换',
  'profile.giftSwapSub': '您的礼物交换',
  'profile.displayMode': '显示模式',
  'profile.displayModeSub': '调整外观 (亮/暗)',
  'profile.display': '显示',
  'profile.chooseAppearance': '选择外观',
  'profile.lightMode': '浅色模式',
  'profile.systemPref': '系统首选项',
  'profile.systemPrefSub': '根据设备设置进行调整',

  // ===================================
  // Edit Profile
  // ===================================
  'editProfile.title': '编辑个人资料',
  'editProfile.changePhoto': '更改照片',
  'editProfile.firstNameLabel': '名字',
  'editProfile.firstNameHint': '输入名字',
  'editProfile.lastNameLabel': '姓氏',
  'editProfile.lastNameHint': '输入姓氏',
  'editProfile.endDateLabel': '结束日期',
  'editProfile.locationLabel': '位置',
  'editProfile.locationHint': '输入地址位置',
  'editProfile.occupationLabel': '职业',
  'editProfile.occupationHint': '输入职业',
  'editProfile.designationLabel': '职称',
  'editProfile.designationHint': '输入描述',
  'editProfile.companyNameLabel': '公司名称',
  'editProfile.companyNameHint': '输入公司名称',
  'editProfile.websiteLabel': '网站',
  'editProfile.websiteHint': '粘贴您的网站',
  'editProfile.linkedInLabel': '领英',
  'editProfile.linkedInHint': '粘贴领英链接',
  'editProfile.instagramLabel': 'Instagram',
  'editProfile.instagramHint': '粘贴 Instagram 链接',
  'editProfile.facebookLabel': '脸书',
  'editProfile.facebookHint': '粘贴脸书链接',
  'editProfile.otherLinkLabel': '其他链接',
  'editProfile.otherLinkHint': '粘贴其他链接',
  'editProfile.addOtherLink': '添加其他链接',
  'editProfile.claimIdentity': '声称身份',

  // ===================================
  // Events
  // ===================================
  'event.status.attended': '已参加',
  'event.status.notAttended': '未参加',
  'event.status.joinnow': '立即加入',
  'event.detailTitle': '活动详情',
  'event.hostedBy': '主办方',
  'event.areYouGoing': '你要去吗？',
  'event.responseRequired': '需要回应',
  'event.going': '去',

  // ===================================
  // Family Events
  // ===================================
  'familyEvents.title': '家族活动',
  'familyEvents.findHint': '查找活动',
  'familyEvents.tabUpcoming': '即将到来',
  'familyEvents.tabPast': '过去',

  // ===================================
  // Member List
  // ===================================
  'memberList.title': '所有家族成员',
  'memberList.tabFamilies': '家族',
  'memberList.tabPeople': '人物',
  'memberList.noMembers': '未找到成员',
  'memberList.present': '在场',
  'memberList.location': '加州，美国',

  // ===================================
  // Find Yourself
  // ===================================
  'findYourself.title': '找到自己',
  'findYourself.searchHint': '查找姓名/出生日期',
  'findYourself.bestMatches': '最佳匹配',
  'findYourself.foundCount': '找到 @count',
  'findYourself.notListed': '未列出？请创建资料',
  'findYourself.thisIsMe': '这是我',
  'findYourself.subtitle': '搜索您的名字以将您的帐户连接到\n现有的家谱记录。',
  'findYourself.possibleMatches': '可能的匹配项',
  'findYourself.selectionReqTitle': '需要选择',
  'findYourself.selectionReqMsg': '请先选择您的个人资料。',
  'findYourself.firstName': '名字',
  'findYourself.lastName': '姓氏',
  'findYourself.gender': '性别',
  'findYourself.selectGender': '选择性别',
  'findYourself.dob': '出生日期',
  'findYourself.yearOnly': '仅匹配年份',
  'findYourself.searchBtn': '搜索',
  'findYourself.clearBtn': '清除',
  'findYourself.initialMsg': '请至少输入一个字段，然后点击搜索。',
  'findYourself.noResults': '未找到结果',
  'findYourself.noResultsSub': '请尝试调整搜索词或清除过滤器。',
  'findYourself.resultsCount': '找到 @count 个结果',
  'findYourself.validationMsg': '请至少输入一个字段进行搜索。',
  'findYourself.male': '男',
  'findYourself.female': '女',
  'findYourself.other': '其他',
  'findYourself.firstNameHint': '输入名字',
  'findYourself.lastNameHint': '输入姓氏',
  'findYourself.dobHint': '选择日期',

  // ===================================
  // Find Member
  // ===================================
  'findMember.title': '查找家族成员',
  'findMember.searchHint': '查找家族成员',
  'findMember.lastViewed': '最后查看',

  // ===================================
  // Role & Access
  // ===================================
  'role.title': '角色和访问权限',
  'role.currentRole': '当前角色：@role',
  'role.familySpace': '史密斯家族空间',
  'role.adminAccessTitle': '管理权限',
  'role.adminAccessDesc': '管理员对家族空间拥有完全控制权。他们可以管理成员和配置设置。',
  'role.permission.editTree': '家族树编辑',
  'role.permission.editTreeSub': '添加、编辑或删除任何个人资料',
  'role.permission.memberMgmt': '成员管理',
  'role.permission.memberMgmtSub': '邀请新用户并分配角色',
  'role.permission.spaceSettings': '空间设置',
  'role.permission.spaceSettingsSub': '更改隐私和通知',
  'role.permission.contentModeration': '内容审核',
  'role.permission.contentModerationSub': '管理相册和删除的帖子',
  'role.warning': '只有家族创始人可以转移所有权或删除整个家族空间。',
  'role.changePermission': '需要更改您的权限吗？',
  'role.contactCreator': '联系家族创始人',
  'role.saveAndCreate': '保存并创建',
  'role.limitedAccess': '有限访问',
  'role.limitedAccessDesc': '无法查看敏感信息或编辑树。',
  'role.fullAccess': '完全访问',
  'role.fullAccessDesc': '可以查看所有信息和编辑家族树。',
  'role.admin': '管理员',
  'role.member': '成员',
  'role.guest': '客人',

  // ===================================
  // Family Space
  // ===================================
  'chooseSpace.welcome': '欢迎来到 Kincore！',
  'chooseSpace.subtitle': '您想如何开始您的家庭之旅？在下方选择一个选项。',
  'chooseSpace.createTitle': '创建新的家庭空间',
  'chooseSpace.createSubtitle': '为您的家庭建立一个全新的空间来连接、分享和成长。',
  'chooseSpace.joinTitle': '加入现有空间',
  'chooseSpace.joinSubtitle': '有邀请码或链接吗？在这里加入您的家庭成员。',
  'chooseSpace.joinSnackbarTitle': '加入空间',
  'chooseSpace.joinSnackbarMsg': '正在导航至加入空间屏幕...',
  'createSpace.appBarTitle': '创建家庭空间',
  'createSpace.welcome': '欢迎来到 Kincore！',
  'createSpace.subtitle': '建立一个专属空间，与您的家庭成员连接、分享和成长。',
  'createSpace.uploadPhoto': '上传空间照片',
  'createSpace.nameLabel': '家庭空间名称',
  'createSpace.nameHint': '例如：安德森家族',
  'createSpace.descLabel': '描述（可选）',
  'createSpace.descHint': '为您的家庭写一段简短的传记...',
  'createSpace.createBtn': '创建空间',
  'createSpace.selectImageTitle': '选择图片',
  'createSpace.selectImageMsg': '图片选择器将在此处打开。',
  'createSpace.validationErrorTitle': '验证错误',
  'createSpace.validationErrorMsg': '请输入您的家庭空间名称。',
  'createSpace.successTitle': '成功',
  'createSpace.successMsg': '家庭空间“@name”创建成功！',
  'chooseSpace.joinOptionsTitle': '加入空间',
  'chooseSpace.scanQr': '扫描二维码',
  'chooseSpace.scanQrSub': '使用家庭二维码立即加入',
  'chooseSpace.joinUrl': '通过 URL 加入',
  'chooseSpace.joinUrlSub': '粘贴邀请链接',
  'chooseSpace.findYourself': '找到你自己',
  'chooseSpace.findYourselfSub': '在主页树中搜索您的个人资料',
  'joinOptions.title': '加入空间',
  'joinOptions.scanTitle': '扫描二维码',
  'joinOptions.scanSub': '从相机或图库扫描家庭二维码',
  'joinOptions.urlTitle': '通过 URL 加入',
  'joinOptions.urlSub': '在此处粘贴邀请链接',
  'joinOptions.findTitle': '找到你自己',
  'joinOptions.findSub': '搜索您的名字并认领您的身份',
  'urlJoin.title': '通过链接加入',
  'urlJoin.subtitle': '在下方粘贴家庭空间邀请链接以立即加入。',
  'urlJoin.hint': '在此处粘贴网址...',
  'urlJoin.submit': '加入空间',
  'scanner.title': '扫描二维码',
  'scanner.subtitle': '将家庭二维码对准框内进行扫描',
  'scanner.galleryBtn': '从图库上传',

  // ===================================
  // Role Access
  // ===================================
  'roleAccess.title': '角色和访问权限',
  'roleAccess.manager': '经理',
  'roleAccess.permissions': '权限',
  'roleAccess.viewTree': '查看家族树',
  'roleAccess.editTree': '编辑家族树',
  'roleAccess.addMembers': '添加家族成员',
  'roleAccess.deleteMembers': '删除家族成员',
  'roleAccess.manageRoles': '管理角色和权限',
  'roleAccess.postFeed': '发布到家族动态',
  'roleAccess.viewMemories': '查看记忆',
  'roleAccess.createEvents': '创建活动',

  // ===================================
  // Role Selection
  // ===================================
  'roleSelection.title': '选择您的角色',
  'roleSelection.grandparent': '祖父母',
  'roleSelection.parent': '父母',
  'roleSelection.adult': '成人',
  'roleSelection.teenager': '青少年',
  'roleSelection.child': '孩子',

  // ===================================
  // Identity Approval
  // ===================================
  'identity.title': '身份批准',
  'identity.pendingRequests': '待处理请求',
  'identity.noRequests': '没有待处理的请求',
  'identity.claiming': '声称身份',
  'identity.proof.photo': '照片证明',
  'identity.proof.birth': '出生证明',
  'identity.reject': '拒绝',
  'identity.requestFrom': '请求来自',
  'identity.approve': '批准',
  'identity.decline': '拒绝',
  'identity.statusTitle': '身份状态',
  'identity.claimPending': '声明待处理',
  'identity.status.pending': '待处理',
  'identity.status.description': '我们已收到您对约瑟夫祖先的声明。这通常需要 24-48 小时。',
  'identity.submittedOn': '提交于',
  'identity.relationship': '关系',
  'identity.relationshipValue': '祖父',
  'identity.verificationProgress': '验证进度',
  'identity.progress.submitted': '请求已提交',
  'identity.progress.submittedSub': '您的文件已收到',
  'identity.progress.inProgress': '验证进行中',
  'identity.progress.inProgressSub': '我们的团队正在审查您的身份证和关系证明。',
  'identity.progress.decision': '最终决定',
  'identity.progress.decisionSub': '批准或要求更多信息。',
  'identity.addProof': '上传额外证明',
  'identity.addProofPhoto': '添加额外证明照片',
  'identity.backToProfile': '返回个人资料',
  'requestHistory.requestApproved': '请求已批准',
  'requestHistory.dataChange': '数据更改',
  'requestHistory.requestSubmitted': '请求已提交',
  'requestHistory.adminComment': '“已通过电子邮件提供的出生证明进行验证。”',
  'requestHistory.reviewedBy': '由 @admin (管理员) 审核',
  'requestHistory.changeTo': ' 更改为 ',
  'requestHistory.dummyApprovedTime': '2025年10月22日/上午10:30',
  'requestHistory.dummySubmittedTime': '2023年10月20日 / 您',

  // ===================================
  // Space Management
  // ===================================
  'space.switch': '切换空间',
  'space.current': '当前空间',
  'space.other': '其他空间',
  'space.confirmSwitch': '确认切换',
  'space.switchedTo': '您现在在 @spaceName',
  'space.online': '在线',
  'space.members': '@count 成员',
  'space.active': '活跃',

  // ===================================
  // Generation Screen
  // ===================================
  'generation.title': '代数',
  'generation.noData': '未找到数据',
  'generation.genSuffix': '第 @level 代',
  'generation.members': '成员',
  'generation.generation': '代数',
  'generation.years': '年',

  // ===================================
  // Gift & Draw Screens
  // ===================================
  'gift.letsDraw': '我们来抽签吧！',
  'gift.surpriseBegin': '让惊喜开始吧！',
  'gift.spinning': '旋转中...',
  'gift.spinWheel': '转轮',
  'gift.exchangeDetails': '礼物交换详情',
  'gift.senderName': '礼物赠送者的名字',
  'gift.receiverName': '礼物接收者的名字',
  'gift.exchangeName': '命名您的礼物交换',
  'gift.selectDate': '选择日期',
  'gift.budget': '礼物预算',
  'gift.addNote': '添加备注',
  'gift.addGiftPhoto': '添加礼物照片',
  'gift.uploadSupport': '上传 PNG、JPG 文件',
  'gift.sendGift': '发送礼物',
  'gift.addGiftExchange': '添加礼物交换',
  'gift.eventDetails': '活动详情',
  'gift.eventName': '活动名称',
  'gift.festivalType': '节日类型',
  'gift.description': '描述',
  'gift.scope': '范围',
  'gift.deadlines': '截止日期',
  'gift.signupDeadline': '注册截止日期',
  'gift.drawDeadline': '抽签截止日期',
  'gift.giftDeadline': '礼物截止日期',
  'gift.budgetPreference': '预算和偏好',
  'gift.budgetRange': '预算范围：₹@value',
  'gift.preferredGiftType': '首选礼物类型',
  'gift.anonymity': '匿名性',
  'gift.anonymitySub': '保持参与者秘密',
  'gift.createExchange': '创建礼物交换',
  'gift.swapTitle': '礼物交换',
  'gift.yourName': '你的名字',
  'gift.addFriendName': '添加朋友的名字',
  'gift.friendName': '朋友的名字',
  'gift.addMore': '+ 添加更多',
  'gift.draw': '抽签',
  'giftSwap.eventDashboard': '活动仪表板',
  'giftSwap.budgetDate': '预算：@amount • @date',
  'giftSwap.drawResults': '抽签结果',
  'giftSwap.reshuffle': '重新洗牌',
  'giftSwap.reshuffleMsg': '根据限制重新抽取配对...',
  'giftSwap.adminViewOnly': '只有您（管理员）可以看到谁抽到了谁。',
  'giftSwap.backToHome': '返回主屏幕',
  'giftSwap.setRestrictions': '设置抽签限制',
  'giftSwap.setRestrictionsSub': '防止特定成员相互抽中',
  'giftSwap.restrictionsTitle': '限制',
  'giftSwap.restrictionsMsg': '管理员可以在此处设置规则，例如A不能抽到B。',
  'giftSwap.successTitle': '成功',
  'giftSwap.createdMsg': '礼物交换活动创建成功！',
  'gift.selectParticipant': '选择',
  'gift.selectParticipantsTitle': '选择参与者',
  'gift.done': '完成',

  // ===================================
  // Checkout & Order History
  // ===================================
  'checkout.title': '结账',
  'checkout.selectedProduct': '选定的产品',
  'checkout.shippingAddress': '送货地址',
  'checkout.addressName': '家',
  'checkout.addressDetail': '近邮局，velnath chowk，Junagadh',
  'checkout.paymentMethod': '支付方式',
  'checkout.payment.card': '信用卡/借记卡',
  'checkout.payment.upi': '统一支付接口',
  'checkout.payment.netbanking': '网上银行',
  'checkout.applyRewards': '应用奖励',
  'checkout.applyKcc': '应用 KCC 硬币',
  'checkout.apply': '应用',
  'checkout.youHaveKcc': '您有 {count} KCC 硬币',
  'checkout.billDetails': '账单详情',
  'checkout.subtotal': '小计',
  'checkout.shippingFee': '运费',
  'checkout.tax': '税收 ({percent}%)',
  'checkout.totalAmount': '总金额',
  'checkout.total': '总计',
  'checkout.placeOrder': '下单',
  'checkout.proceedingSnackbar': '重定向到支付...',
  'checkout.emptyCartSnackbar': '先添加一些项目！',
  'trackOrder.title': '追踪订单',
  'trackOrder.orderId': '订单 ID',
  'trackOrder.expectedDelivery': '预计送达',
  'trackOrder.trackingHistory': '追踪历史',
  'trackOrder.stepPlaced': '已下单',
  'trackOrder.stepPayment': '付款已确认',
  'trackOrder.stepShipped': '订单已发货',
  'trackOrder.stepOutForDelivery': '正在派送',
  'trackOrder.stepDelivered': '已送达',
  'trackOrder.expectedToday': '预计今天',
  'trackOrder.pending': '待定',

  // ===================================
  // Invoice Screen
  // ===================================
  'invoice.title': '发票',
  'invoice.downloadingTitle': '下载',
  'invoice.downloadingMsg': '发票 PDF 正在下载...',
  'invoice.taxInvoice': '税务发票 / 供应账单',
  'invoice.orderId': '订单 ID',
  'invoice.orderDate': '订单日期',
  'invoice.paymentMode': '付款方式',
  'invoice.status': '状态',
  'invoice.paid': '已付款',
  'invoice.shippingDetails': '配送详情',
  'invoice.orderSummary': '订单摘要',
  'invoice.shippingFee': '运费',
  'invoice.tax': '税 (10%)',
  'invoice.totalAmount': '总金额',
  'invoice.downloadPdf': '下载 PDF',

  // ===================================
  // Scanner Screen
  // ===================================
  'scanner.connect': '与亲人联系',
  'scanner.instruction': '输入邀请链接或代码以加入\n您的家庭空间。',
  'scanner.inviteLinkLabel': '邀请链接',
  'scanner.inviteLinkHint': 'https://family.app/join/....',
  'scanner.joinBtn': '加入空间',
  'scanner.myLink': '我的链接',
  'scanner.copiedTitle': '链接已复制',
  'scanner.copiedMsg': '您的链接已复制到剪贴板。',
  'scanner.or': '或',
  'scanner.shareBtn': '分享二维码',
  'scanner.shareText': '嘿！使用我的链接加入 Kincore 上的家庭空间：@link',
  'scanner.shareSubject': '在 Kincore 上加入我的家庭空间',
  'scanner.askAdmin': '请家庭管理员从他们的个人资料设置中\n向您展示他们的二维码。',

  // ===================================
  // Cart
  // ===================================
  'cart.title': '我的购物车',
  'cart.empty': '您的购物车是空的',
  'cart.buyNow': '立即购买',
  'cart.remove': '移除',

  // ===================================
  // Order History
  // ===================================
  'orderHistory.title': '订单历史',
  'orderHistory.searchHint': '按订单 ID 或产品搜索',
  'orderHistory.netQty': '净数量。1',
  'orderHistory.trackOrder': '追踪订单',
  'orderHistory.status.shipped': '已发货',
  'orderHistory.status.current': '当前',
  'orderHistory.status.ago': '2 天前',

  // ===================================
  // Security & Privacy
  // ===================================
  'security.title': '安全和锁定',
  'security.lockProfile': '锁定个人资料',
  'security.lockProfileSub': '只有确认的家族成员才能看到您的照片和时间轴上的帖子。',
  'security.searchVisibility': '搜索可见性',
  'security.visibility.everyone': '每个人',
  'security.visibility.friends': '朋友的朋友',
  'security.visibility.family': '仅家族',
  'security.contactPrivacy': '联系隐私',
  'security.hideEmail': '隐藏电子邮件',
  'security.hideEmailSub': '您的电子邮件将仅对您自己隐藏。',
  'security.hidePhone': '隐藏电话号码',
  'security.hidePhoneSub': '您的联系电话将对任何其他用户不可见。',
  'security.saveChanges': '保存更改',

  // ===================================
  // Kinship Calculator
  // ===================================
  'kinship.resultTitle': '亲属关系结果',
  'kinship.path': '路径',
  'kinship.details': '详情',
  'kinship.meaning': '含义',
  'kinship.meaningSub': '一个人的母亲的母亲。',
  'kinship.englishTerm': '英文术语',
  'kinship.englishTermSub': '外祖母',
  'kinship.newCalculation': '新计算',
  'kinship.editPath': '编辑路径',
  'kinship.pathTitle': '关系路径',
  'kinship.selectPath': '选择路径',
  'kinship.addNextStep': '添加下一步',
  'kinship.calculate': '计算关系',

  // ===================================
  // Migration Map
  // ===================================
  'migration.mapTitle': '迁移地图',
  'migration.historyTitle': '迁移历史',
  'migration.findMember': '查找家族成员',
  'migration.arrivalYear': '到达：@year',
  'migration.reason': '迁移原因',
  'migration.familyMemberCount': '家族成员（@count）',
  'migration.viewHistory': '查看迁移历史',
  'migration.timeline.familyMigration': '施密特家族迁移',
  'migration.timeline.from': '来自',
  'migration.timeline.to': '到',
  'migration.timeline.viewRoute': '查看路线',

  // ===================================
  // Claim Identity
  // ===================================
  'claim.title': '声称身份',
  'claim.description': '要访问私人家族数据并为树做出贡献，请安全地验证您的身份。',
  'claim.tab.verify': '验证代码',
  'claim.tab.confirm': '确认',
  'claim.tab.submit': '提交',
  'claim.inviteCode': '邀请代码',
  'claim.inviteCodeHint': '输入您邀请中的 8 位字母数字代码。',
  'claim.profileMatch': '找到个人资料匹配',
  'claim.thisIsMe': '是的，这是我',
  'claim.confirmProfile': '我确认此个人资料数据准确',
  'claim.verifyOwnership': '验证所有权',
  'claim.emailHint': '输入您的电子邮件地址',
  'claim.govId': '政府身份证（可选）',
  'claim.addGovId': '添加政府身份证照片',
  'claim.submitClaim': '提交声明',

  // ===================================
  // Request History
  // ===================================
  'requestHistory.title': '请求历史',
  'requestHistory.thisMonth': '这个月',
  'requestHistory.birthdateUpdate': '出生日期更新',

  // ===================================
  // Change Relationship
  // ===================================
  'changeRelationship.title': '更改关系',
  'changeRelationship.add': '添加',
  'changeRelationship.remove': '移除',
  'changeRelationship.detailTitle': '关系详情',
  'changeRelationship.typeHint': '关系类型',
  'changeRelationship.personHint': '选择相关人员',
  'changeRelationship.reasonHint': '变更原因（必需）',
  'changeRelationship.supportDocs': '支持文件',
  'changeRelationship.security': '您的文件被安全存储，对家族管理员可见，用于验证目的。',
  'changeRelationship.saveNext': '保存并下一步',

  'All': '全部',
  'Pending': '待处理',
  'Approved': '已批准',
  'Rejected': '已拒绝',
};
