// lib/localization/zh_CN.dart

const Map<String, String> zhCN_ = {
  // ===================================
  // Common & General
  // ===================================
  'common.add': '添加',
  'common.save': '保存',
  'common.cancel': '取消',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.viewAll': '全部查看',
  'common.select': '选择',
  'common.search': '搜索',
  'common.find': '查找',
  'common.publish': '发布',
  'common.saveAndAdd': '保存并添加',
  'common.upload': '上传',
  'common.addFile': '添加文件',
  'common.savePhotos': '保存照片',
  'common.saveMemory': '保存记忆',
  'common.loading': '加载中...',
  'common.error': '出现错误，请重试。',
  'common.success': '成功',
  'common.productPublished': '产品发布成功！',
  'common.yes': '是',
  'common.no': '否',
  'common.maybe': '也许',
  'common.select_country': '选择国家',
  'common.submit': '提交',
  'common.done': '完成',
  'common.next': '下一步',
  'common.continue': '继续',
  'common.all': '全部',
  'common.seeAll': '查看全部',
  'common.father': '父亲',
  'common.mother': '母亲',
  'common.sister': '姐妹',
  'common.brother': '兄弟',
  'common.approved': '已批准',

  // ===================================
  // Auth Screen
  // ===================================
  'auth.kincore': 'Kincore',
  'auth.connect': '连接到你的根源！',
  'auth.welcomeBack': '欢迎回来！',
  'auth.detailsPrompt': '输入您的详细信息以登录或创建帐户。',
  'auth.signUp': '注册',
  'auth.logIn': '登录',
  'auth.nameLabel': '输入您的姓名',
  'auth.nameHint': '名字 姓氏',
  'auth.emailLabel': '电子邮件地址',
  'auth.emailHint': 'abc@gmail.com',
  'auth.passwordLabel': '密码',
  'auth.passwordHint': '••••••••',
  'auth.confirmPasswordLabel': '确认密码',
  'auth.forgotPassword': '忘记密码？',
  'auth.continueWith': '或继续使用',
  'auth.google': 'Google',
  'auth.facebook': 'Facebook',

  // ===================================
  // Home Screen
  // ===================================
  'home.title': '首页',
  'home.goodMorning': '早上好',
  'home.upcomingBirthdays': '即将到来的生日',
  'home.viewCalendar': '查看日历',
  'home.timeline': '时间轴',
  'home.startBuilding': '开始构建您的家族树',
  'home.startBuildingDesc': '添加家族成员，见证您的遗产增长。',
  'home.addFirstMember': '添加第一个成员',
  'home.recentMemories': '最近的记忆',
  'home.noMemories': '未找到最近的记忆。',
  'home.addFirstMemory': '添加您的第一个记忆',
  'home.upcomingEvents': '即将到来的事件',
  'home.noEvents': '没有即将到来的事件。',
  'home.familyEvents': '家庭活动',
  'home.familyBio': '家族传记',
  'home.secretSanta': '秘密圣诞老人',
  'home.kinshipCalculator': '亲属关系计算器',
  'home.identityApproval': '身份批准',
  'home.migrationMap': '迁移地图',

  'nav.home': '首页',
  'nav.feed': '动态',
  'nav.tree': '家族树',
  'nav.mall': '商城',
  'nav.profile': '个人资料',
  'nav.memory': '回忆',
  'nav.family': '家庭',
  'nav.events': '活动',

  'tree.title': '哈里森家族',
  'tree.generations': '{count} 代 / {members} 位成员',

  'familyBio.addTitle': '添加家庭简介',
  'familyBio.addMedia': '添加媒体',
  'familyBio.dragAndDrop': '拖放或浏览以上传',
  'familyBio.basicInfo': '基本信息',
  'familyBio.storyName': '故事名称',
  'familyBio.location': '地点',
  'familyBio.birthDate': '出生日期',
  'familyBio.selectDate': '选择日期',
  'familyBio.storyBio': '故事（简介）',
  'familyBio.addBioHint': '在此添加简介...',
  'familyBio.publishBio': '发布简介',
  'familyBio.title': '家庭简介',
  'familyBio.gallery': '相册',
  'familyBio.nextInHistory': '历史下一章',
  'familyBio.existingMember': '现有家庭成员',
  'familyBio.theRoaringTwenties': '咆哮的二十年代',
  'familyBio.roaringTwentiesDate': '1920 - 1929',
  'familyBio.migrationStoryDate': '1920年11月4日 · 西西里到纽约',
  'familyBio.migrationStoryContent':
  '大迁徙是历史上的重要时刻，数百万人踏上前往新土地的旅程，寻求机会和新的开始。其中包括来自西西里的年轻女子玛丽亚·罗西，她于1920年前往纽约。她的故事展现了勇气、坚韧和不屈的人类精神。',
  'familyBio.migrationStoryQuote':
  '“旅程漫长而艰辛，但对美好生活的希望支撑着我们。”—— 玛丽亚·罗西',

  'addMember.title': '添加家庭成员',
  'addMember.basicInfo': '基本信息',
  'addMember.firstName': '名',
  'addMember.lastName': '姓',
  'addMember.gender': '性别',
  'addMember.male': '男',
  'addMember.female': '女',
  'addMember.other': '其他',
  'addMember.dateOfBirth': '出生日期',
  'addMember.dateFormatHint': '月/日/年',
  'addMember.relationshipSetup': '关系设置',
  'addMember.relationshipType': '关系类型',
  'addMember.relationship.spouse': '配偶',
  'addMember.relationship.sibling': '兄弟姐妹',
  'addMember.relationship.parent': '父母',
  'addMember.findFamilyMember': '查找家庭成员',
  'addMember.spouseName': '配偶姓名',
  'addMember.anniversaryDate': '纪念日',
  'addMember.additionalDetail': '附加信息',
  'addMember.addLocation': '添加地点',
  'addMember.occupation': '职业',
  'addMember.bioNotes': '简介 / 备注',
  'addMember.privacyVisibility': '隐私与可见性',
  'addMember.visibleToAll': '对所有成员可见',
  'addMember.addParentsTitle': '添加父母',
  'addMember.addOtherMember': '添加其他家庭成员',
  'addMember.placeOfBirth': '出生地',
  'addMember.currentLocation': '当前所在地',
  'addMember.addChildTitle': '添加孩子',
  'addMember.schoolAndCollege': '学校与大学',
  'addMember.qualification': '学历',
  'addMember.studyLocation': '学习地点',
  'addMember.changePhoto': '更换照片',
  'addMember.livingStatus': '生存状态',
  'addMember.isAlive': '此人是否仍然在世？',
  'addMember.alive': '在世',
  'addMember.deceased': '已故',
  'addMember.phoneNumber': '电话号码',
  'addMember.phoneHint': '00000 00000',

  'memory.title': '回忆',
  'memory.addTitle': '添加回忆',
  'memory.tabAll': '全部',
  'memory.tabPhotos': '照片',
  'memory.tabVideos': '视频',
  'memory.addMemoryPhotos': '添加回忆照片',
  'memory.addMemoryVideos': '添加回忆视频',
  'memory.uploadSupport': '支持上传 PNG、JPG 文件',

  'mall.title': '商城',
  'mall.searchHint': '查找产品',
  'mall.filter': '筛选',
  'mall.categories': '分类',
  'mall.featured': '精选',
  'mall.mostPopular': '最受欢迎',
  'mall.onSale': '促销中',
  'mall.wishlistTitle': '我的心愿单',
  'mall.noItemsWishlist': '您的心愿单为空！',
  'mall.exploreProducts': '探索产品',
  'mall.productDetails': '产品详情',
  'mall.description': '描述',
  'mall.selectSize': '选择尺寸',
  'mall.selectColor': '选择颜色',
  'mall.quantity': '数量',
  'mall.addToCart': '加入购物车',
  'mall.buyNow': '立即购买',
  'mall.reviews': '评论',
  'mall.noReviews': '暂无评论。',
  'mall.sellerInfo': '卖家信息',
  'mall.viewShop': '查看店铺',
  'mall.relatedProducts': '相关产品',
  'mall.addedToCart': '{productName} 已加入购物车',
  'mall.filterPrice': '价格范围',
  'mall.filterColor': '颜色',
  'mall.filterGender': '性别',
  'mall.category.fashion': '时尚',
  'mall.category.electronics': '电子产品',
  'mall.category.appliances': '家用电器',
  'mall.category.beauty': '美妆',
  'mall.category.furniture': '家具',
  'mall.banner.title': '新品系列',
  'mall.banner.discount': '五折优惠',
  'mall.banner.for': '儿童专区',
  'mall.productReview': '{rating}（{count} 条评论）',
  'mall.tag.homeMade': '手工制作',
  'mall.tag.newCollection': '新系列',

  'addProduct.title': '添加新产品',
  'addProduct.detailsPrompt': '请输入所有产品信息',
  'addProduct.uploadImagesTitle': '上传产品图片',
  'addProduct.uploadImagesDesc': '使用清晰的高分辨率图片，第一张为封面。',
  'addProduct.addMedia': '添加媒体',
  'addProduct.dragAndDrop': '拖放或浏览以上传',
  'addProduct.basicInfo': '基本信息',
  'addProduct.productNameLabel': '产品名称（必填）',
  'addProduct.priceLabel': '价格',
  'addProduct.discountLabel': '折扣%',
  'addProduct.descriptionLabel': '描述',
  'addProduct.sizeLabel': '尺寸',
  'addProduct.conditionsLabel': '商品状况',
  'addProduct.brandNameLabel': '品牌名称',
  'addProduct.profileLabel': '选择您的资料',
  'addProduct.categoryLabel': '分类',
  'addProduct.subCategoryLabel': '子分类',
  'addProduct.quantityLabel': '数量',
  'addProduct.publishButton': '发布产品',

  'redeem.title': '兑换 KCC 币',
  'redeem.totalBalance': '总余额',
  'redeem.kccBalance': 'KCC 余额',
  'redeem.currency': 'KCC',
  'redeem.waysToRedeem': '兑换方式',
  'redeem.waysToEarn': '获取方式',
  'redeem.recentActivity': '最近活动',
  'redeem.vintageCase': '复古箱',
  'redeem.kmallPurchase': '商城购买',
  'redeem.redeemedKcc': '-455 KCC',
  'redeem.shopAndSave': '购物省钱',
  'redeem.redeemForCash': '兑换现金',
  'redeem.shopNow': '立即购物',
  'redeem.redeemNow': '立即兑换',

  'earn.referral': '邀请好友',
  'earn.referralSub': '赚取 20 KCC',

  'createEvent.title': '创建活动',
  'createEvent.saveDraft': '保存',
  'createEvent.addCoverPhoto': '添加封面照片',
  'createEvent.uploadSupport': '支持上传 PNG、JPG 文件',
  'createEvent.detailTitle': '活动详情',
  'createEvent.eventTitleLabel': '活动标题',
  'createEvent.eventTitleHint': '输入标题',
  'createEvent.locationLabel': '地点',
  'createEvent.locationHint': '输入地址',
  'createEvent.descriptionLabel': '描述',
  'createEvent.descriptionHint': '在此输入...',
  'createEvent.startDateLabel': '开始日期',
  'createEvent.endDateLabel': '结束日期',
  'createEvent.timeLabel': '时间',
  'createEvent.timeHint': '输入时间',
  'createEvent.inviteMemberTitle': '邀请家庭成员',

  'feed.title': '家庭动态',
  'feed.myStory': '我的故事',
  'feed.whatsHappening': '发生了什么？',
  'feed.createPost': '创建帖子',
  'feed.archive': '存档',
  'feed.writeCommentHint': '写评论...',
  'feed.viewComments': '查看全部 {count} 条评论',
  'postSettings.title': '帖子设置',
  'postSettings.postSettings': '帖子设置',
  'postSettings.whoCanSee': '谁可以看到你的帖子？',
  'postSettings.visibility.public': '公开',
  'postSettings.visibility.friends': '好友',
  'postSettings.visibility.friendsExcept': '除部分好友',
  'postSettings.visibility.specificFriends': '指定好友',
  'postSettings.whoCanComment': '谁可以评论？',
  'postSettings.comments.followersOnly': '仅关注者',
  'postSettings.comments.friends': '好友',
  'postSettings.comments.chosenFriends': '选择的好友',
  'postSettings.saveChanges': '保存更改',
  'feed.postAnonymously': '匿名发布',
  'feed.allowComments': '允许评论',
  'feed.saveToDevice': '保存到设备',
  'feed.reportPost': '举报帖子',

  'createPost.title': '创建帖子',
  'createPost.hint': '你在想什么？',
  'createPost.addMedia': '添加媒体',
  'createPost.tagPeople': '标记成员',
  'createPost.postButton': '发布',

  'report.title': '举报问题',
  'report.anonymousHelp':
  '您的举报是匿名的。请告诉我们发生了什么，以帮助维护社区安全。',
  'report.reasonTitle': '举报原因',
  'report.spam': '垃圾信息',
  'report.nudity': '裸露或性行为',
  'report.hateSpeech': '仇恨言论或符号',
  'report.falseInfo': '虚假信息',
  'report.harassment': '骚扰或欺凌',
  'report.other': '其他',
  'report.additionalDetails': '附加说明（可选）',
  'report.describeIssue': '请描述问题以帮助审核',
  'report.submitReport': '提交举报',
  'report.dialog.discardTitle': '放弃举报？',
  'report.dialog.discardBody':
  '确定要取消举报吗？您的进度将丢失。',
  'report.dialog.stay': '否，继续',
  'report.dialog.discard': '是，放弃',

  'seller.title': '仪表板',
  'seller.overview': '概览',
  'seller.totalRevenue': '总收入',
  'seller.orders': '订单',
  'seller.avgOrderValue': '平均订单价值',
  'seller.products': '产品',
  'seller.topProducts': '热门产品',
  'seller.recentOrders': '最近订单',
  'seller.orderId': '订单',
  'seller.noProducts': '暂无产品。',
  'seller.noOrders': '暂无订单。',
  'seller.noData': '暂无数据',

  'profile.title': '我的资料',
  'profile.followers': '关注者',
  'profile.following': '关注中',
  'profile.editProfile': '编辑资料',
  'profile.addMember': '添加成员',
  'profile.addMemory': '添加回忆',
  'profile.vitalStats': '基本信息',
  'profile.stat.fullName': '姓名',
  'profile.stat.born': '出生',
  'profile.stat.location': '地点',
  'profile.stat.occupation': '职业',
  'profile.familyMember': '家庭成员',
  'profile.keyLifeEvents': '重要人生事件',
  'profile.viewMoreTimeline': '查看更多时间轴',
  'profile.memories': '回忆',
  'profile.shareProfile': '分享资料',
  'profile.personal': '个人',
  'profile.business': '商业',
  'profile.posts': '帖子',
  'profile.photos': '照片',
  'profile.videos': '视频',
  'profile.tagged': '被标记',
  'profile.myProfile': '我的资料',
  'profile.sellerDashboard': '卖家仪表板',
  'profile.identityApproval': '身份审核',
  'profile.redeemCoins': '兑换金币',
  'profile.settings': '设置',
  'profile.logout': '退出登录',
  'profile.logoutConfirm': '确定要退出吗？',

  'space.switch': '切换空间',
  'space.current': '当前空间',
  'space.other': '其他空间',
  'space.confirmSwitch': '确认切换',
  'space.switchedTo': '您现在位于 {spaceName}',
  'space.online': '在线',
  'space.members': '{count} 位成员',
  'space.active': '活跃',
};
